### ISSUE TITLE
Icon request: Hashicorp softwares (Hashistack : Nomad, Terraform, Consul, Vault)

### ISSUE THREAD

**Issue by scorsi** [devicons/devicon#1006]
### About the icon

Importants softwares used by big companies

### Links and sources

https://hashicorp.com/

Nomad : https://www.nomadproject.io/
Terraform : https://www.terraform.io/
Consul : https://www.consul.io/
Vault : https://www.vaultproject.io/

**Comment by Thomas-Boi** [comment]
Hi @scorsi can you split each of the software into its own Issue? This will make closing issues easier for us.
