### ISSUE TITLE
Icon request: Solidity

### ISSUE THREAD

**Issue by arneja-arnav** [devicons/devicon#1018]
### About the icon

Adding an icon for the Programming language Solidity

### Links and sources

https://docs.soliditylang.org/en/v0.8.11/

**Comment by BenSouchet** [comment]
The icon has already been added in this PR https://github.com/devicons/devicon/pull/985 in the next release the icon will be available (@Thomas-Boi maybe adding a "request:in-develop" label so we can see when a request is "done", I know you are working on a bot but a label that we can add by hand on issue is still easy and fast 🙂)

**Comment by arneja-arnav** [comment]
Alright, Thanks 😄 
Just so I know, when is the next release?

**Comment by Panquesito7** [comment]
> Just so I know, when is the next release?

It will be out soon. 🙂

**Comment by Thomas-Boi** [comment]
> Hi, the icon has already been added in this PR #985 in the next release the icon will be available.
> 
> (@Thomas-Boi maybe adding a "request:in-develop" label so we can see when a request is "done", I know you are working on a bot but a label that we can add by hand on issue is still easy and fast 🙂)

Yup, this is a feature that we've realized we need for the upcoming build. There is a label called `in-develop` but we haven't manually label the issues yet. When we have time, we'll be going over these issues one more time.
