### ISSUE TITLE
Icon request: WebAssembly

### ISSUE THREAD

**Issue by AvikRao** [devicons/devicon#1025]
### About the icon

WebAssembly is a rapidly emerging frontend technology for compiling and running low-level languages at near-native speeds from within the browser. Considering its projected growth and impact, I believe WASM would be a useful devicon.

### Links and sources

https://webassembly.org/
https://developer.mozilla.org/en-US/docs/WebAssembly
https://upload.wikimedia.org/wikipedia/commons/1/1f/WebAssembly_Logo.svg

**Comment by Thomas-Boi** [comment]
Closing since this is already requested in #367
