### ISSUE TITLE
Icon request: freeCode Camp

### ISSUE THREAD

**Issue by VikashPR** [devicons/devicon#1035]
### About the icon

freeCodeCamp is a learning platform with lot's of resources for the developers.

### Links and sources

https://www.freecodecamp.org

https://en.wikipedia.org/wiki/FreeCodeCamp

https://github.com/freeCodeCamp

### Additional information

freeCodeCamp is a non-profit organization that consists of an interactive learning web platform, an online community forum, online publications and local organisations that intend to make learning web development accessible to anyone.

**Comment by lunatic-fox** [comment]
#1432 discussion solves it!
