### ISSUE TITLE
Icon Request - UML

### ISSUE THREAD

**Issue by h3t1** [devicons/devicon#104]

**Comment by amino19** [comment]
@h3t1: Will you pl check, what's the official logo for MASM32 from [logodix.com](https://logodix.com/masm)?

Also, pl give me confirmation about [UML logo](https://upload.wikimedia.org/wikipedia/commons/d/d5/UML_logo.svg).

**Comment by Snailedlt** [comment]
UML is in develop. @h3t1 please make a new issue for assembly language. Remember, one issue per icon
