### ISSUE TITLE
Icon request: lenovo

### ISSUE THREAD

**Issue by chaosd3v** [devicons/devicon#1057]
### About the icon

Lenovo is one of the world's leading personal technology companies, producing innovative PCs and mobile internet devices. 

### Links and sources

The icon can be found in this official site: <a href="https://www.lenovo.com" target="_blank">https://www.lenovo.com</a>

### Additional information
It would be good to add other missing logo of similar type like apple, hp, ryzen, intel

**Comment by amacado** [comment]
Hello @chaosd3v,

this project's purpose is dedicated to development (tools/languages) and not tech companies per se. We have discussed this and created a guideline about icon requirements:

- https://github.com/devicons/devicon/discussions/353
- https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#iconRequirements

As far as I know lenovo does not provide dedicated development tools or resources. Feel free to prove me wrong by providing further information why lenovo would match our requirements. Till that point I'll close this icon request! 

Have a nice day! 😄
