### ISSUE TITLE
Icon request: JetBrains Rider

### ISSUE THREAD

**Issue by klemmchr** [devicons/devicon#1071]
### About the icon

JetBrains Rider is a cross-platform .NET IDE used by many .NET develops in favor of Visual Studio.

### Links and sources

https://www.jetbrains.com/rider/
https://www.jetbrains.com/company/brand/#logos-and-icons-product-logos

### Additional information

Other JetBrains IDEs like PHPStorm or PyCharm already made it into this repository so this would be a welcome addition.

**Comment by thehedgefrog** [comment]
Added in #1106.
