### ISSUE TITLE
[BUG] Website is not displaying the new icons from latest release

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#1091]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Usually, it should only take a few hours for the icons to show up on the website. However, it's been a day and nothing has shown up yet.

### Possible fixes or solutions

I'm not sure what's causing this issue. The tag number is correct (v2.15.1) and the css files that were pulled has the new icons in them (so is the `devicon.json`). Perhaps something to do with caching from the CDN? 

### Additional information

Changes might need to be merged into `master` for them to appear.

**Comment by amacado** [comment]
Hi @Thomas-Boi, can you give an example which icons do not show up?
I tested a couple from https://github.com/devicons/devicon/releases/tag/v2.15.0 and they all seem fine..

**Comment by Thomas-Boi** [comment]
Oh they shows up now 😆 It's crazy. Just 10 minutes earlier the icons didn't show up. I guess this is fixed now. Thanks @amacado
