### ISSUE TITLE
[feat/icon]: adobe cc

### ISSUE THREAD

**Issue by blassbasti** [devicons/devicon#110]
Hey thank you very much for all your hard work!
It would be great if the following icons would be added to the font:

Adobe Indesign
Adobe Premiere Pro
Adobe After Effects
Adobe Lightroom
Ableton Live
Avid Pro Tools
Avid Media Composer
VVVV
Pure Date
Max/MSP
Resolume

**Comment by Thomas-Boi** [comment]
Closed since this request contain multiple icons.
