### ISSUE TITLE
Mocha Icon Sizing

### ISSUE THREAD

**Issue by chadwithuhc** [devicons/devicon#112]
Howdy! 

The Mocha icon (`devicon-mocha-plain`) displays at proportions other than square (1:1) while the rest of the icons I've seen are using a 1:1 ratio. This is causing the icons to misalign when in a gridded format.

I believe this icon should be fixed to match the others for consistency. See screenshot of icons in a 3 column grid, with each icon being shown at 80px x 80px except the mocha icon.

<img width="498" alt="screen shot 2018-04-14 at 11 08 48 am" src="https://user-images.githubusercontent.com/259196/38770732-ba253db2-3fd4-11e8-872a-113f6395a364.png">

I've got a basic CSS fix for it at the moment.

Love,
Chad.

**Comment by Thomas-Boi** [comment]
Hello there,

This issue has been fixed in one of our recent commits. Thank you for letting us know of this issue and I hope that the new sizing is what you are looking for.

Cheers,
Thomas
