### ISSUE TITLE
[BUG] `bot:peek` image upload fails (403 response code imgur)

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#1124]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Sometimes the upload to imgur seems to fail, not sure about the reasons yet:

![image](https://user-images.githubusercontent.com/8781699/161067112-35b88578-1108-45af-8dec-9c0e8d6433a6.png)
https://github.com/devicons/devicon/runs/5771824897?check_suite_focus=true

The result is that `bot:peek` posts "env.MESSAGE" instead the images (see for example https://github.com/devicons/devicon/pull/1123#issuecomment-1084580296).

### Possible fixes or solutions

Revisit the https://github.com/devicons/public-upload-to-imgur project and see what's the problem

**Comment by Thomas-Boi** [comment]
Brief research shows that there's a new Bearer token in the docs.
![image](https://user-images.githubusercontent.com/43018778/161124566-75ed97c6-f717-440a-b803-18f0feb15299.png)

Since our request is failing with a 403 error (forbidden access), it seems like we might need a new token. I'll look more into this issue after 2 weeks.

**Comment by Panquesito7** [comment]
Has this been addressed?

**Comment by Snailedlt** [comment]
@Panquesito7 I'm not sure, but I haven't seen the issue pop up again in quite some time. @Thomas-Boi Did you ever fix this? If not, maybe it was fixed by another API update?

**Comment by Thomas-Boi** [comment]
I don't think we ever saw the problem again but I'm not sure. I can't really remember sorry.

**Comment by Snailedlt** [comment]
Okey, no worries 😊

**Comment by Panquesito7** [comment]
Well, I haven't seen this issue happening anymore.
Should we close it or keep it open just in case?

**Comment by Snailedlt** [comment]
Let's close it. We can re-open if it happens again :)
