### ISSUE TITLE
[ICON REQUEST]: JetBrains Products

### ISSUE THREAD

**Issue by Kek5chen** [devicons/devicon#1125]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

JetBrains has great products and provides them with great care.

### Links and sources

Here you can see the SVGs of all their developer tools:
https://www.jetbrains.com/products/

I've done a bit of own work but since contributing to this repository is very strict and I am afraid to make too many mistakes I forked it, placed some icons and pushed it to my fork. You can see the changes here:
https://github.com/Kek5chen/devicon/commit/0a06ff51f0a88db2549bd71d63a5c5a2f2dc39d8

Icons included:
[CLion](https://github.com/Kek5chen/devicon/blob/0a06ff51f0a88db2549bd71d63a5c5a2f2dc39d8/icons/clion/clion-original.svg)
[DataGrip](https://github.com/Kek5chen/devicon/blob/0a06ff51f0a88db2549bd71d63a5c5a2f2dc39d8/icons/datagrip/datagrip-original.svg)
[IntelliJ](https://github.com/Kek5chen/devicon/blob/0a06ff51f0a88db2549bd71d63a5c5a2f2dc39d8/icons/intellij/intellij-original.svg)
[PhpStorm](https://github.com/Kek5chen/devicon/blob/0a06ff51f0a88db2549bd71d63a5c5a2f2dc39d8/icons/phpstorm/phpstorm-original.svg)
[PyCharm](https://github.com/Kek5chen/devicon/blob/0a06ff51f0a88db2549bd71d63a5c5a2f2dc39d8/icons/pycharm/pycharm-original.svg)
[Rider](https://github.com/Kek5chen/devicon/blob/0a06ff51f0a88db2549bd71d63a5c5a2f2dc39d8/icons/rider/rider-original.svg)
[WebStorm](https://github.com/Kek5chen/devicon/blob/0a06ff51f0a88db2549bd71d63a5c5a2f2dc39d8/icons/webstorm/webstorm-original.svg)

Some icons i only updated, but I only updated the `original` files. The others, except `plain`, seemed outdated as there is no actual `wordmark` for the products officially available anywhere.

Would you like me to create a PR for maintainers to modify to suit the repository guidelines?

**Comment by Snailedlt** [comment]
Hey, create a PR so we can get this one going :)
Jetbrains icons definitely need updating

**Comment by Kek5chen** [comment]
Alright, i opened a pr. I do not know if everything matches what you were asking for but it should be a good starting point

**Comment by Snailedlt** [comment]
@kilian-paquier You wanna try to tackle this one?

**Comment by kilian-paquier** [comment]
My favorite products ❤️ Will take care of that one yep, I'll add "fleet" too, their next IDE (multilingual like IntelliJ)

**Comment by kilian-paquier** [comment]
@Kek5chen Hello, thank you for your contribution, even if it's in your fork repository. I'm going to use your original's icons (with small modifications) and tag you as co-author if it's ok for you.

**Comment by Kek5chen** [comment]
sure thing, thanks. i'm glad i could help somewhat. i'm also happy that i can finally close the repository.

**Comment by kilian-paquier** [comment]
Don't close it too soon, I didn't copy all the icons yet 😁

**Comment by Kek5chen** [comment]
of course not. i'll wait for this issue to be resolved first

**Comment by kilian-paquier** [comment]
@Snailedlt @Kek5chen Maybe we could defining a main color for our plain icons, instead of black ?

**Comment by Snailedlt** [comment]
@kilian-paquier If you do, make sure it's one from their color pallette here:
https://www.jetbrains.com/company/brand/

**Comment by kilian-paquier** [comment]
Ok I'm going to look into this.

Also, I found this : https://github.com/JetBrains/logos
I'm going to use those icons for the PR's, that's why I made "draft" the opened ones.

**Comment by Snailedlt** [comment]
@kilian-paquier yeah everything you need should be in that link I sent :)
TOS is there too

**Comment by kilian-paquier** [comment]
All PR's created

**Comment by Snailedlt** [comment]
So many 👀
