### ISSUE TITLE
[ICON REQUEST]: plotly

### ISSUE THREAD

**Issue by luizcarloscf** [devicons/devicon#1131]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

The front end for ML and data science models

### Links and sources

* [website](https://plotly.com/)
* [github](https://github.com/plotly)

**Comment by amacado** [comment]
As mentioned in https://github.com/devicons/devicon/pull/1134#pullrequestreview-937152386: Looking trough [plotly.com](https://plotly.com/) and the referenced repositories like https://github.com/plotly/dash I'm not sure if `plotly` matches our requirements for icons. For me it seems that "plotly" is the company name and `dash` is the (or one?) product by this company. To be honest: I have never heard of it yet so feel free to prove me wrong! I'll update my review in #1134 if this is solved! :)

**Comment by daczarne** [comment]
I think this is a common confusion between Plotly the company and plotly the tool/library (developed by its name-sake company). As a JS data viz library Plotly is equivalent to other libraries included in devicons (like Flask, or Pandas). The base JS implementation can be found [here](https://github.com/plotly/plotly.js). The library is also available for [Python](https://github.com/plotly/plotly.py), [R](https://github.com/plotly/plotly.R), [Julia](https://github.com/plotly/Plotly.jl).

The other product that is mentioned in #1131 is Dash. This is another product by the same company (Plotly), for building Dashboards. It uses a Flask backend and React components as its building blocks. It allows for any other Python library to be used in its backend (like Plotly.py or matplotlib for example).

**Comment by luizcarloscf** [comment]
@daczarne explained well!
The pull request was made thinking of plotly as a data viz library. However, the icon is a company icon. and the company have more than a product. But the only icon is this, as far as i researched. 

I don't know if this PR makes sense anymore (to match the repo requirements)

**Comment by amacado** [comment]
I tend to follow the explaination by @daczarne and agree on adding plotly because of the same named product. I'll leave this discussion open a couple more days to give others the chance for more feedback (f.e. by @Panquesito7, @Thomas-Boi).

**Comment by Snailedlt** [comment]
From what I can gather, I agree with @daczarne's explanation, seems like a nice addition for devicons.

**Comment by Panquesito7** [comment]
I agree with adding the icon. Looks like a developer-related tool. 👍

**Comment by Thomas-Boi** [comment]
Yup, seems like the request is specifically regarding the icon, not the repo
