### ISSUE TITLE
[ICON REQUEST]: OpenStack

### ISSUE THREAD

**Issue by luca-drf** [devicons/devicon#1136]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

OpenStack is the most widely used open source cloud platform (both private and public)

### Links and sources

Web:
- [Home](https://www.openstack.org/)
- [Wikipedia](https://en.wikipedia.org/wiki/OpenStack)

Icon resources:
- [Official Logo](https://www.openstack.org/brand/openstack-logo/logo-download/)
- [LogoDix](https://logodix.com/logos/63135)
- [Simple Icons SVG](https://simpleicons.org/icons/openstack.svg)

**Comment by luizcarloscf** [comment]
@Panquesito7 missing label "in-develop"?
