### ISSUE TITLE
[OTHER] JSON file formatter

### ISSUE THREAD

**Issue by daczarne** [devicons/devicon#1143]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### What would you like to share?

The `devicon.json` has multiple linting issues (which for me surfaced in [this commit](https://github.com/devicons/devicon/pull/1142/commits/04fabafa906fdcd56c77680c4cfbc9af3de9e919) thanks to VSCode auto-format on save feature).

Proposal
- Format the file
- Add the required formatting extension that contributors are expected to use for JSON files in this project. For VSCode users, this can be added to the project in the `.vscode/settings.json` file. This way, whenever the repo is cloned, VS Code will suggest the extension to the user (if needed) and utilize it for this project accordingly.

**Comment by Snailedlt** [comment]
@daczarne Does https://github.com/devicons/devicon/pull/1364 solve your issue, or do you think there's more to be done here?

**Comment by daczarne** [comment]
> @daczarne Does #1364 solve your issue, or do you think there's more to be done here?

@Snailedlt yes, adding `.editorconfig` is another way of addressing the issue for VS-Code users. Not sure if `.editorconfig` works with other IDEs though.

**Comment by Snailedlt** [comment]
@daczarne 
A lot of different editors and IDE's support .editorconfig out of the box: 
https://editorconfig.org/#pre-installed

Some of them do require you to download a plugin for it to work though: 
https://editorconfig.org/#download

I guess an improvement we could do is add the [extension for vscode](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) as a recommendation. If you want, feel free to make a PR doing just that :)

**Comment by daczarne** [comment]
@Snailedlt I was not aware that `.editorconfig` was available for so many IDEs (being a VS Code user myself). I think in this case this issue can be closed.

**Comment by Snailedlt** [comment]
The extension is still needed for vscode, so I think we can just change the issue to `add editorconfig vscode extension to workspace recommendations`.

I'll make a PR on it when I have time, unless you wanna do it yourself :)

**Comment by Snailedlt** [comment]
@daczarne

**Comment by daczarne** [comment]
@Snailedlt added the PR: https://github.com/devicons/devicon/pull/1478

**Comment by Snailedlt** [comment]
@daczarne Why did you close this? It's not fixed yet, right?
