### ISSUE TITLE
[ICON REQUEST]: influxDB

### ISSUE THREAD

**Issue by AMATEURTOSS** [devicons/devicon#1148]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

InfluxDB is the time series platform for developers

### Links and sources

* <a href="https://www.influxdata.com/products/influxdb-overview/">website</a>
* <a href="https://github.com/influxdata/influxdb">github</a>
* <a href="https://influxdata.github.io/branding/logo/downloads/">svg</a>

**Comment by Panquesito7** [comment]
Working on this. 🙂

**Comment by Snailedlt** [comment]
Looks like the wrong logos have been linked here. The link to `svg` is for the company logo. Here are the product logos: https://influxdata.github.io/branding/logo/brands/
