### ISSUE TITLE
[ICON REQUEST]: Netlify

### ISSUE THREAD

**Issue by RalphK66** [devicons/devicon#1159]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Extremely popular

### Links and sources

[netlify](https://www.netlify.com/)

**Comment by BenSouchet** [comment]
@Snailedlt Duplicate of #854

**Comment by Snailedlt** [comment]
@RalphK66 As mentioned above, this is a duplicate. Please go over to the other issue and vote for it instead :)
