### ISSUE TITLE
[ICON REQUEST]: <Cypress>

### ISSUE THREAD

**Issue by phileinSophos** [devicons/devicon#1162]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Cypress is a framework used for UI automation, an alternative to selenium

### Links and sources

https://www.cypress.io/

**Comment by amacado** [comment]
@phileinSophos please have a look at https://github.com/devicons/devicon/issues/223 and https://github.com/devicons/devicon/pull/1097. `cypressio` is already in our development branch.
