### ISSUE TITLE
[FEATURE REQUEST] Add alternative names

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1165]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

It would be much easier to find icons, if you could search for alternative names.

Take vscode for example.
Currently if I search for `Visual Studio Code`, or `visualstudiocode` nothing shows up. This is because the name of the icon is `vscode`.

The same is true for a lot of javascript frameworks and libraries, where they won't show up if you add `js` at the end

### Possible Solution

If an array of `altNames` was added to the devicon.json file, it could be added as a search field, and let us search through that list as well.

**Comment by Snailedlt** [comment]
@Thomas-Boi I think this is a duplicate of https://github.com/devicons/devicon/issues/327

**Comment by amacado** [comment]
@Snailedlt thanks for picking this issue up. If I got your idea right, #327 is a little different than your request. While #327 is about alias (which can be used in the font as css class) you are talking only about a search option on our website, right? For this purpose we might could use the already existing "tags" property in devicon.json. It's used like a keyword..  Does this satisfy your requirements?

https://github.com/devicons/devicon/wiki/Updating-the-%60devicon.json%60
```
// list of tags relating to the technology for search purpose (TBD)
"tags": string[], 
```

Currently the `tags` are not used but the website template could be adjusted to make use of it. What do you think?

**Comment by Snailedlt** [comment]
Yes, that is correct, I'm only talking about search. I don't think tags should be mixed with altnames, since tags are used more as categories, while altnames are just alternative names for the icon.

It would be nice to be able to search for tags. Though it would make it harder to search if we just added it normally, since there would be a lot more search results for some searches.

I think a better way to add it would be to add a "tag" filter. So you could filter by tags, and then search for the name/altname. If we do it this way, it would be nice to also add a list of "allowed" tags, so that we don't get a lot of similar tags like "javascript", "js", "jsframework", etc...

What do you think?

**Comment by Snailedlt** [comment]
@Thomas-Boi Thanks for that :)
The PR I have out now actually implements search already, so no need to add that :)
If this PR gets merged, you'll be able to search for altnames aswell as the normal names
