### ISSUE TITLE
[ICON REQUEST]: White GitHub Icon 

### ISSUE THREAD

**Issue by namanks2201** [devicons/devicon#1170]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Many people prefer dark mode over light mode these days and in dark mode, the dark logo of GitHub is a bit difficult to see. So it will be better if we add a white logo of the GitHub.

### Links and sources

https://github.com/namanks2201/namanks2201/blob/main/img/github.png?raw=true

**Comment by amacado** [comment]
You can change the color of the font (and svg) by CSS styling.
Here is a simple example which can be adjusted to your needs: https://codepen.io/amacado/pen/QWQWqvB

**Comment by namanks2201** [comment]
Thanks for replying, will look into it.
