### ISSUE TITLE
[ICON REQUEST]: C++

### ISSUE THREAD

**Issue by namanks2201** [devicons/devicon#1173]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Already there are icons for C++ but still I think the new icons needs to be added to the list since it looks better in comparison to the existing ones.

### Links and sources

https://github.com/namanks2201/namanks2201/blob/main/img/cpp.png?raw=true

**Comment by amacado** [comment]
Could you provide a official source for the updated icon?

**Comment by namanks2201** [comment]
What do you mean by official source? Like do I need to send you the link by
which I downloaded the file? I am unable to get what exactly you
are looking for.
