### ISSUE TITLE
[ICON REQUEST]: Solidworks

### ISSUE THREAD

**Issue by ndeangel** [devicons/devicon#1176]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Widely used CAD software

### Links and sources

https://www.solidworks.com/

**Comment by BenSouchet** [comment]
Currently Devicon do not accept [Computer-aided design tools and Softwares](https://en.wikipedia.org/wiki/Computer-aided_design) (AutoCAD, Solidworks, SketchUp, ...).

See the accepted categories here: https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F#not-allowed-not-exhaustive

There is the SVG icon, so if you want to add it manually, you can customize the font to add the icon [check here](https://github.com/devicons/devicon/wiki/How-We-Create-The-Icons).

![solidworks-original-wordmark](https://user-images.githubusercontent.com/17025808/181293732-fa117842-1b7b-4948-9226-07b4913a59e9.svg)

@Snailedlt I think this issue can be closed.
