### ISSUE TITLE
[ICON REQUEST]: Krita

### ISSUE THREAD

**Issue by hud0shnik** [devicons/devicon#1178]
### I have searched through the issues and didn't find my problem.

- [x] Confirm

### About the icon

Krita is a popular open source raster graphics editor

### Links and sources

- Logo: https://krita.org/wp-content/themes/krita-org-theme/images/krita-logo.png?v2022
- Github: https://github.com/KDE/krita
- Website: https://krita.org/

**Comment by BenSouchet** [comment]
Hi, according to the guideline :
https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F

The Krita does not enter in one of the category for devicon, since this is not related to code / dev.

**Comment by lunatic-fox** [comment]
Agree with @BenSouchet. 👍🏼
