### ISSUE TITLE
Icon Request: Spring Framework, Kotlin, Maven, Jenkins

### ISSUE THREAD

**Issue by zhacpalomares** [devicons/devicon#121]

**Comment by tsassi** [comment]
Also Ant, JSP, JSF, J2EE, JDK.

**Comment by henray** [comment]
+1

**Comment by dgarcia360** [comment]
+1

**Comment by iamclaytonray** [comment]
Please limit issues to one icon request, feature request, or bug. If you'd kindly update this issue and then file issues for other icons that are not yet filed, that would help me out a ton! I'm going to try to get some PRs merged in over the next few days and I'm currently triaging issues. Thanks for your contribution!
