### ISSUE TITLE
[FEATURE REQUEST] Show number of Icons on the website

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1218]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

Currently there's no way (at least afaik) to see how many icons there are on the website. It would be nice to see some stats.

### Possible Solution

I propose showing the number of icons in total, the average number of icons per logo, and the number of logos.

Something like this:

Logos: 111
Icons: 555
Avg. Icons per Logo: 5

### Additional information

It would be nice if these stats were also shown in the README.md

**Comment by Snailedlt** [comment]
Should also be possible to see how many hits/logos you get on a search :)

**Comment by kilian-paquier** [comment]
Hello @Snailedlt, where would you like the section to be ? Juste above the list of icons, under the search field ? At the right ? Left ? Or anywhere else ?

**Comment by Snailedlt** [comment]
@kilian-paquier Hi!
I was thinking either at the very top, or below the search field :)

Depends on if we wanna change it based on the current search or not

**Comment by kilian-paquier** [comment]
Seems good to me to update the value when a search is done, don't you think ? So, below the search field ? Right side ? Left side ?

**Comment by Snailedlt** [comment]
Yeah, underneath sounds good.

2s draft: 
![image](https://user-images.githubusercontent.com/43886029/177217838-1e6a02df-e3cb-4ef0-8854-f40bdaa59c40.png)

**Comment by kilian-paquier** [comment]
Hello @Snailedlt,

Here's a draft : 

![image](https://user-images.githubusercontent.com/107955904/178550166-a8012592-c5eb-4a2e-9463-1b52572929e0.png)

I'm just asking myself, what's the value of the average numbers ? While implementing it, I don't find any add value.
What's for you the difference (in your initial message) between icons and logos ?

**Comment by Snailedlt** [comment]
@kilian-paquier 
Looks good, but can we have the numbers side by side instead of underneath eachother? That way it doesn't take up too much space on the page.

I guess the value is for people to see the quality of our dataset. A larger average would indicate better quality. Making the number a float/double instead of an integer would provide more value I guess. 

As for what's the difference between a logo and an icon. I would consider the plain, original, line, original-wordmark, etc... All a part of the same logo. But each of them are different icons. So there's one logo for each brand, and one icon for each svg/image/font. In other words all brands have one logo, and each logo has one or multiple icons

**Comment by kilian-paquier** [comment]
Hello @Snailedlt, something like that ? I reused the current vocabulary, to avoid any ambiguity.

![image](https://user-images.githubusercontent.com/107955904/178713586-0aab93f6-1824-4c9e-aa9b-8e1705173197.png)

**Comment by kilian-paquier** [comment]
More @Snailedlt ?

![image](https://user-images.githubusercontent.com/107955904/178925005-7afbd1b8-a654-46ca-bcc1-a1e288de5b25.png)

**Comment by Snailedlt** [comment]
imo, yes! heheh :)

The divs can look something like this:
![image](https://user-images.githubusercontent.com/43886029/179083676-21e9b0b4-e334-400b-a2f2-06eeb368802a.png)

Each box can then have left aligned text
