### ISSUE TITLE
Request for new icon

### ISSUE THREAD

**Issue by Angelk90** [devicons/devicon#122]
@konpa : It would be possible to add the following icons:
Titanium
SQLite
Realm
Processing
Action Script
VB.NET
MatLab
Batch
Assembly
Assembly x86
Microcontrollers or Processors
blender

**Comment by Angelk90** [comment]
@konpa : Are there any news?

**Comment by Harshit369** [comment]
I would like to add a few more, the ones I need badly.
- Redux
- React-Native
- MobX (Though I know this one's not that famous)

Some Thanks in advance if I wasn't thankful already 😅🙏🏽

**Comment by amacado** [comment]
I'm closing this issue because our contribution guidelines require one icon per issue.
