### ISSUE TITLE
[ICON REQUEST]: Tauri

### ISSUE THREAD

**Issue by Robinerra** [devicons/devicon#1220]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Tauri is essentially Electron but lighter, utilizing a rust backend and a custom browser. It's small but gaining traction.

### Links and sources

https://tauri.app/
https://www.npmjs.com/package/tauri/v/0.1.5?activeTab=readme

Logos:

https://tauri.app/img/index/tauri_1_0_dark.svg
https://seeklogo.com/images/T/tauri-logo-39352BD5A1-seeklogo.com.png
https://github.com/tauri-apps/tauri/blob/HEAD/app-icon.png

**Comment by Snailedlt** [comment]
https://www.youtube.com/watch?v=-X8evddpu7M
