### ISSUE TITLE
[ICON REQUEST]: Update laravel

### ISSUE THREAD

**Issue by yzPeedro** [devicons/devicon#1221]
### Laravel new icon.

- [ ] Confirm

### About the icon

The Laravel icon that is in the devicons is the old icon and is not used anymore

### Links and sources

Laravel new icon: 
##
<a href="https://laravel.com/img/logomark.min.svg">
<img align="center" alt="Pedro-Laravel" height="40" width="38" src="https://laravel.com/img/logomark.min.svg">
</a>

**Comment by canaleal** [comment]
Hey Pedro, I can take a look at this later today. Here are the logo links incase someone else wants to give it a try.

Website:
https://laravel.com/

Github:
https://github.com/laravel

Brand:
https://github.com/laravel/art

Brand Legacy:
https://github.com/laravel/art/tree/master/legacy
