### ISSUE TITLE
[ICON REQUEST]: OpenCL & CUDA

### ISSUE THREAD

**Issue by RyanSweeney987** [devicons/devicon#1231]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Both are languages for parallel computing

### Links and sources

https://www.khronos.org/opencl/
https://developer.apple.com/licensing-trademarks/opencl/

https://developer.nvidia.com/cuda-toolkit
https://www.nvidia.com/en-gb/about-nvidia/legal-info/logo-brand-usage/
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuda

**Comment by amacado** [comment]
Please create separated issues for each icon. Thank you! :-) You can edit this to show only one icon and create a second issue for the other! :) This makes it more easy to track changes and the current development! :)

**Comment by RyanSweeney987** [comment]
I edited this one and added a new one as suggested :)
