### ISSUE TITLE
Add icon pack to Icomoon library

### ISSUE THREAD

**Issue by karanrajpal14** [devicons/devicon#124]
Hey @konpa,

Any chance you'd consider adding all these icons to the icomoon library like FontAwesome and the others? That way we could just pick the icons we needed from everywhere and use them. Would make the websites a tad lighter as well since we'd be downloading fewer files.

I know I can just download the SVGs and do them myself but I'd like to see the library there among the others. What do you think?

**Comment by iamclaytonray** [comment]
Hey @karanrajpal14! That's a great question! Let me do a little research and get back to you on this. Thanks for your feature request!

**Comment by BenSouchet** [comment]
I know it's a very old still open issue.
But three points: 
- icomoon is not open source, currently don't allow external contribution.
- The have specific license for there icons.
- The icons SVG files here on devicon have licenses, if we could add the icons to the icomoon library knowing that they have their own license, this would mean ignoring the licenses, and we will infringe the copyright of these icons.

@Thomas-Boi maybe this issue need to be closed :)
