### ISSUE TITLE
[ICON REQUEST]: Photopea 

### ISSUE THREAD

**Issue by canaleal** [devicons/devicon#1246]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Photopea is a web-based photo and graphics editor. It is used for image editing, making illustrations, web design or converting between different image formats. It's similar to GIMP and Photoshop.

### Links and sources

Official Tool:
https://www.photopea.com/

Github:
https://github.com/photopea

Logo Original:
https://github.com/photopea/photopea/blob/master/logo.svg

Logo Original Wordmark:
https://github.com/photopea/photopea/blob/master/wide.svg

**Comment by BenSouchet** [comment]
Hi, according to the guideline :
https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F

**Photopea** is a great alternative of Photoshop or Gimp but it's doesn't fall in one category related to code / dev.
