### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by Satyabrat35** [devicons/devicon#125]
Please add icons for the following:
1. Flask Python
2. SQlite
3. Sublime Text

**Comment by multinerd** [comment]
id also like to add [MS SQL ](https://marketplace.brainwavegrc.com/wp-content/uploads/bw_store_facet_images/bw_sqlserverrights_icon-900x0.png)

**Comment by iamclaytonray** [comment]
Hey @multinerd - would you mind opening a new issue for this request? Thanks!

@Satyabrat35 - Can you also edit this issue to include only one icon request and then add additional issues for additional icons that you would like to see land in a future release? Thanks!

**Comment by multinerd** [comment]
I've created the new request, #147

**Comment by amacado** [comment]
Closing this issue, since our updated guidelines require one issue for each icon :)
