### ISSUE TITLE
[ICON REQUEST]: Stripe

### ISSUE THREAD

**Issue by jeremyxwing** [devicons/devicon#1271]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

For developers who want to showcase their proficiency with or use of Stripe / the Stripe API

### Links and sources

https://brandfolder.com/s/h3jbwkqfhbv9s9k4b9qpt3x

### Additional information

As I see more developers using Devicons on their resume, it occurred to me that some may want to use a Stripe icon to showcase their proficiency with or use of Stripe / the Stripe API.

**Comment by amacado** [comment]
Hello @jeremyxwing, thank you for creating a issue. Unfortunately, if you read carefully trough our guide about [What Icons Do We Accept?](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F) you'll probably notice that Stripe does not fulfill our requirements. Yes, it provides an API, but nowadays almost every tool does provide an API, and we won't add my fridge's icon to this repository ;-) Same for stripe. It's main purpose is a payment gateway and not a development tool, language or related. I'll close this, but feel free to argue against it :)
