### ISSUE TITLE
[ICON REQUEST]: <Postman>

### ISSUE THREAD

**Issue by alexusbernard17** [devicons/devicon#1278]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Good back end API tool

### Links and sources

https://www.postman.com/

**Comment by kilian-paquier** [comment]
Already done, but not yet merged : #1237. There was also already an issue for postman #933 #159

**Comment by alexusbernard17** [comment]
thanks, how long will it take to be merged?

**Comment by kilian-paquier** [comment]
@alexusbernard17, it depends, when validated, it will be merged into develop. But you'll have to wait until the release to use the icons, which can be longer.

**Comment by Snailedlt** [comment]
duplicate of #933
