### ISSUE TITLE
[ICON REQUEST]: nano

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1279]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

GNU text editor in the terminal

### Links and sources

[Website](https://www.nano-editor.org/)

### Images

[PNG](https://commons.wikimedia.org/wiki/File:GNU-Nano-Logo.png)
![image](https://user-images.githubusercontent.com/43886029/180627718-8140c820-526e-42ac-9397-f41a3fd925dd.png)

[PNG Wordmark (not official)](https://www.maketecheasier.com/mastering-nano-text-editor/)
![image](https://user-images.githubusercontent.com/43886029/180627789-7aaa986c-e0ef-44a3-bc1e-97c70f833170.png)

[SVG](https://commons.wikimedia.org/wiki/File:Gnu-nano.svg)
SVG doesn't show properly for some reason, so click the link to see it
![image](https://upload.wikimedia.org/wikipedia/commons/8/8a/Gnu-nano.svg)

### Additional information

The original logo is just made out of ASCII art, so could be hard to find a good SVG for it.

### Original logo from the website

```
                :::                           The                 
  iLE88Dj.  :jD88888Dj:                                           
.LGitE888D.f8GjjjL8888E;        .d8888b.  888b    888 888     888 
iE   :8888Et.     .G8888.      d88P  Y88b 8888b   888 888     888 
;i    E888,        ,8888,      888    888 88888b  888 888     888 
      D888,        :8888:      888        888Y88b 888 888     888 
      D888,        :8888:      888  88888 888 Y88b888 888     888 
      D888,        :8888:      888    888 888  Y88888 888     888 
      D888,        :8888:      Y88b  d88P 888   Y8888 Y88b. .d88P 
      888W,        :8888:       "Y8888P88 888    Y888  "Y88888P"  
      W88W,        :8888:                                         
      W88W:        :8888:      88888b.   8888b.  88888b.   .d88b. 
      DGGD:        :8888:      888 "88b     "88b 888 "88b d88""88b
                   :8888:      888  888 .d888888 888  888 888  888
                   :W888:      888  888 888  888 888  888 Y88..88P
                   :8888:      888  888 "Y888888 888  888  "Y88P" 
                    E888i                                         
                    tW88D             Text Editor Homepage        
```

**Comment by BenSouchet** [comment]
I created these SVGs, pretty heavy files (128kB et 343kB) since for compatibility font characters need to be vectors / paths): 
![nano](https://user-images.githubusercontent.com/17025808/180998200-ea51c7d1-1b2b-4b4e-a298-142674201d26.svg)
![nanow](https://user-images.githubusercontent.com/17025808/180999766-79711140-fd5a-4efd-9bef-0572cfd1d7ce.svg)

**Comment by Snailedlt** [comment]
@BenSouchet Nice work!
How did you go about creating the icons? they look spot on

**Comment by BenSouchet** [comment]
@Snailedlt
With **Adobe Illustrator**, you have the possibility to convert text(s) to paths, then you export as SVG, after that I optimize the SVG via https://jakearchibald.github.io/svgomg/ , for me the best SVG optimizer available then I ensure the SVG is properly formatter (no `style=""`).

When I need to create vectors from scratch, I start with **Photoshop** (I know it's weird, but for me way faster than using illustrator) then I import paths to illustrator, apply colors, resize in a 128x128 canvas, then save as SVG and Optimize with **SVGOMG**.

**Comment by BenSouchet** [comment]
@Snailedlt 

I think **SVGOMG** is in between beginners and advance users, it's a very good tool to properly optimize SVG files.

If you want for the documentation the steps are:
1. Copy the full SVG code of the SVG you want to optimize
<img width="939" alt="01" src="https://user-images.githubusercontent.com/17025808/181004756-3d532b07-1656-4745-a1b1-20ac3706ace9.png">

2. Go to **SVGOMG**, on the left side click on _Paste markup_
<img width="458" alt="02" src="https://user-images.githubusercontent.com/17025808/181005150-0f3ede6f-9cba-4226-a50a-d2eb9ba96f69.png">
3. right-click and Paste
<img width="363" alt="03" src="https://user-images.githubusercontent.com/17025808/181005246-27dadcc4-08e6-47a0-9dcd-cec05629133f.png">
4. Now that the SVG has been loaded in the interface, it's time to set the parameters to use named "Features"
<img width="930" alt="04" src="https://user-images.githubusercontent.com/17025808/181006108-dd0b303e-3b0b-4705-af23-c81dff2d5855.png">

5. Disable **Compare gzipped**, and enable **Multipass**, dont touch the precision slidebar.  
Enable all the features **EXCEPT**:
- Remove xmlns
- Round/rewrite number lists
- Replace duplicate elements with links

6. Now click the copy button to copy to clipboard the SVG code.
<img width="286" alt="Screenshot 2022-07-26 at 14 38 09" src="https://user-images.githubusercontent.com/17025808/181007573-ed9d254d-07fb-4c2c-ac47-facdd9acf178.png">
7. Paste back in your SVG file the SVG code
<img width="551" alt="Screenshot 2022-07-26 at 14 39 30" src="https://user-images.githubusercontent.com/17025808/181007843-caa78000-8fca-451b-b25a-fee623dfed77.png">
8. Add an empty newline at end of file (to ensure compatibilty of SVG file)
<img width="630" alt="Screenshot 2022-07-26 at 14 40 40" src="https://user-images.githubusercontent.com/17025808/181008083-bcd7f769-5fce-497a-b8aa-0c4559a97984.png">

9. Save the file, it's done !

**Comment by BenSouchet** [comment]
There is also pretty good features in https://www.svgviewer.dev/ but these aren't activate by default:
You need to click on Options
<img width="384" alt="Screenshot 2022-07-26 at 14 45 26" src="https://user-images.githubusercontent.com/17025808/181009034-d3c5689f-afa5-47d0-bfa3-08f01073c1a9.png">

Then for example active the **convertStyleToAttrs**
<img width="213" alt="Screenshot 2022-07-26 at 14 46 18" src="https://user-images.githubusercontent.com/17025808/181009238-ffc8adc2-63b7-41db-98d7-581d98ccd7a1.png">

Or the **removeStyleElement**
<img width="196" alt="Screenshot 2022-07-26 at 14 46 28" src="https://user-images.githubusercontent.com/17025808/181009260-0544bde7-0534-4fa3-b4c2-edeb02c35f7c.png">
