### ISSUE TITLE
[ICON REQUEST]: bun

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1282]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Bun is a fast all-in-one JavaScript runtime

### Links and sources

[Website](https://bun.sh/)
[GitHub](https://github.com/oven-sh/bun)

### SVG Logo
![Logo](https://bun.sh/logo.svg)

**Comment by AmreshSinha** [comment]
I would love to work on this if no one is already working on the same.

**Comment by Snailedlt** [comment]
Please go ahead :) I don't think anyone else is working on it atm
