### ISSUE TITLE
[ICON REQUEST]: Elixir

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1283]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Elixir is a dynamic, functional language for building scalable and maintainable applications.

### Links and sources

https://elixir-lang.org/

### PNG (Official)
https://github.com/elixir-lang/elixir-lang.github.com/tree/main/downloads/logos
![image](https://github.com/elixir-lang/elixir-lang.github.com/blob/main/downloads/logos/elixir-horizontal.png?raw=true)
![image](https://github.com/elixir-lang/elixir-lang.github.com/blob/main/downloads/logos/elixir-vertical.png?raw=true)

### SVG (Unofficial)
https://icon-icons.com/icon/elixir-lang-logo/169207
![elixir_lang_logo_icon_169207](https://user-images.githubusercontent.com/43886029/180629261-384803c6-a968-40bb-bc86-2a0a3aecedf0.svg)

**Comment by BenSouchet** [comment]
Hi, Elixir already exists on devicon :)

**Comment by Snailedlt** [comment]
@BenSouchet You're right, lol! I typo'd and wrote `Elexir` every time, so couldn't find i in the code, issues, PR's or website. Why can't people just typo like I do? Would make it so much easier 😂
