### ISSUE TITLE
[BUG] sass miss tag `scss`

### ISSUE THREAD

**Issue by a3510377** [devicons/devicon#1295]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

sass miss tag `scss` in [devicon.json](https://github.com/devicons/devicon/blob/master/devicon.json#L4176-L4197)

### Possible fixes or solutions

in `tags` add "scss"

**Comment by Snailedlt** [comment]
Tags are used as categories now, but we have a new attribute called altname which is perfect for this case :)

Here's how `sass` looks in develop now: https://github.com/devicons/devicon/blob/f1f401a9dc007f79ae199f2e195b55ebeeff41ea/devicon.json#L6659

As you can see it has the altname `scss`, so I will be closing this issue as complete
