### ISSUE TITLE
[ICON REQUEST]: moleculer

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1300]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Progressive microservices framework for Node.js.

### Links and sources

Website -> https://moleculer.services/
Logos -> https://github.com/moleculerjs/branding/tree/master/logo

#### SVG's (official)
![](https://raw.githubusercontent.com/moleculerjs/branding/1c6ed7d38c121732cc6702b0318e47ae74b5b559/logo/logo.svg)
![](https://raw.githubusercontent.com/moleculerjs/branding/1c6ed7d38c121732cc6702b0318e47ae74b5b559/logo/logo-nocircle.svg)

#### PNG's (official)
![](https://raw.githubusercontent.com/moleculerjs/branding/master/logo/logo_with_text_horizontal.png)
![](https://raw.githubusercontent.com/moleculerjs/branding/master/logo/logo_with_text_horizontal_white.png)
![](https://raw.githubusercontent.com/moleculerjs/branding/master/logo/logo_with_text_vertical.png)
![](https://raw.githubusercontent.com/moleculerjs/branding/master/logo/logo_with_text_vertical_white.png)
![](https://raw.githubusercontent.com/moleculerjs/branding/master/logo/logo_sticker.png)

**Comment by Snailedlt** [comment]
related to #1296

**Comment by Snailedlt** [comment]
@kilian-paquier

**Comment by Snailedlt** [comment]
We should see if we can find (or make) one of the wordmark logos here

**Comment by kilian-paquier** [comment]
https://raw.githubusercontent.com/moleculerjs/branding/master/logo/logo_with_text_vertical.png

This one seems good, just need to find it in SVG

**Comment by Snailedlt** [comment]
Yeah agreed. Hopefully it's out there somewhere
