### ISSUE TITLE
[ICON REQUEST]: Cloudflare Workers

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1308]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Deploy serverless code instantly across the globe to give it exceptional performance, reliability, and scale.

### Links and sources

Website -> https://workers.cloudflare.com/
Cloudflare workers logos -> https://github.com/cloudflare/workers.cloudflare.com/tree/master/static/resources/logo

#### SVG (official from github)
logo-combination-mark-vertical.svg (original-wordmark)
![](https://raw.githubusercontent.com/cloudflare/workers.cloudflare.com/49f5f7ad7aa2be4bf2919e42fd818a8b1c439294/static/resources/logo/logo-combination-mark-vertical.svg)
logo.svg (original)
![](https://raw.githubusercontent.com/cloudflare/workers.cloudflare.com/49f5f7ad7aa2be4bf2919e42fd818a8b1c439294/static/resources/logo/logo.svg)
logo-monochromatic.svg (plain)
![](https://raw.githubusercontent.com/cloudflare/workers.cloudflare.com/49f5f7ad7aa2be4bf2919e42fd818a8b1c439294/static/resources/logo/logo-monochromatic.svg)
![]

**Comment by Snailedlt** [comment]
As previously mentioned by @izzqz in #785

**Comment by BenSouchet** [comment]
PR created :)
