### ISSUE TITLE
Request for icon

### ISSUE THREAD

**Issue by vikaskyadav** [devicons/devicon#131]
Request for Data Science libraries. IoT devices such as Raspberry Pi, Arduino etc.

**Comment by Berkmann18** [comment]
I second that.

**Comment by iamclaytonray** [comment]
Please update this issue with one of those icons and then file issues for other icons that are not yet filed. Thanks!

**Comment by amacado** [comment]
Closing this issue since it's invalid and no action was taken since two years to fix it. Feel free to reopen or create a new valid one :)
