### ISSUE TITLE
[FEATURE REQUEST] Check placement of new entries in `devicon.json`

### ISSUE THREAD

**Issue by BenSouchet** [devicons/devicon#1327]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

Currently when someone contribute to Devicon via a PR to add a new set of icons this person can add the new entry in the `devicon.json` file anywhere.

**But** ignoring the alphabetic order in the JSON file can lead to issues / bugs / mistakes and merge conflicts.

Normally the entries order in the `devicon.json` file should reflect as close as possible the automatic order of the `icons/` folder.

### Possible Solution

Add an element in the PR checklist
+
Add a required verification from the PR reviewer(s)
+
Add a line in the documentation ( https://github.com/devicons/devicon/wiki/Updating-the-%60devicon.json%60 )

### Additional information

This is a rather small enhancement but this can improve the robustness of the project, and the solution isn't heavy to add to the current pipeline / process.

Thanks

**Comment by Snailedlt** [comment]
Another possible solution (like we already discussed in the linked PR) is to create a github action that automatically lints the devicon.json file for you.

**Comment by Snailedlt** [comment]
> Add an element in the PR checklist

I'm not sure we have such a checklist yet, maybe we should make one and add it to the wiki?

**Comment by BenSouchet** [comment]
> > Add an element in the PR checklist
> 
> I'm not sure we have such a checklist yet, maybe we should make one and add it to the wiki?

I talk about this checklist:
<img width="815" alt="Screenshot 2022-07-28 at 20 15 32" src="https://user-images.githubusercontent.com/17025808/181608791-c7586373-ab4e-4618-bfc8-1c71b5218df8.png">
In the message / comment of the `peek:bot` ( check the message here https://github.com/devicons/devicon/pull/1324#issuecomment-1197142415 )

**Comment by Snailedlt** [comment]
@BenSouchet Ahh, okey! Yeah that makes sense.
Any idea where the code for the peek-bot is?

**Comment by BenSouchet** [comment]
@Snailedlt
Normally "bots" are Github Actions and actions are store as **workflow** in the folder `.github/workflows/`, for the specific message we are talking it's stored in the file: https://github.com/devicons/devicon/blob/develop/.github/workflows/post_peek_screenshot.yml

**Comment by Snailedlt** [comment]
@BenSouchet Thanks for both the insight and the direct link. Much appreciated!

**Comment by Snailedlt** [comment]
This is related btw: https://github.com/devicons/devicon/issues/987#issuecomment-1001154281
