### ISSUE TITLE
[ICON REQUEST]: <vala>

### ISSUE THREAD

**Issue by hydrasho** [devicons/devicon#1360]
### About the icon

Vala lang

### Links and sources

![image](https://user-images.githubusercontent.com/40312793/185816978-cc13be92-c245-4144-8927-9a99acd62e73.png)

https://gitlab.gnome.org/GNOME/vala
https://github.com/topics/vala?o=desc&s=updated

### Additional information

https://vala.dev/

vala is an easy-to-write programming language that transforms into C and then compiles with Gcc.
it is also the language of elementaryOs and applications/plugins under linux.

the icons should work on:
.vala and .vapi
the .vapi being the wrap lib for vala

**Comment by hydrasho** [comment]
it has been added ? I still don't see the icon ?

**Comment by PantheraRed** [comment]
@hydrasho. It has been added to [`develop`](https://github.com/devicons/devicon/tree/develop) branch and not released on `master` branch for use yet.
