### ISSUE TITLE
[ICON REQUEST]: powershell

### ISSUE THREAD

**Issue by pwnb0y** [devicons/devicon#1365]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Just because sometime people want to show in their readme.md file for their skill. If it is included in your project they can use it from here very easily

### Links and sources

https://raw.githubusercontent.com/PowerShell/PowerShell/master/assets/ps_black_64.svg

**Comment by pwnb0y** [comment]
I would love to work on this issue. Please assign it to me.

**Comment by BenSouchet** [comment]
Hi, as pointed in comment [here](https://github.com/devicons/devicon/pull/1366#issuecomment-1236400839) the icon already exists on the develop branch and will be available in the next version of Devicon.

**Comment by BenSouchet** [comment]
@Snailedlt I think this issue can be closed 🙂
