### ISSUE TITLE
[ICON REQUEST]: Apache Airflow

### ISSUE THREAD

**Issue by firqaaa** [devicons/devicon#1374]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

It is necessary tool for Data Engineer / ML Engineer

### Links and sources

https://airflow.apache.org

**Comment by weh** [comment]
Icon is already in development
- PR: https://github.com/devicons/devicon/pull/1412
- Issue: https://github.com/devicons/devicon/issues/1163

**Comment by Snailedlt** [comment]
Duplicate of #1163
