### ISSUE TITLE
[ICON REQUEST]: Cosmos DB

### ISSUE THREAD

**Issue by hgrafa** [devicons/devicon#1384]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Cosmos Databse API icon

### Links and sources

![icon](https://azurecomcdn.azureedge.net/cvt-4f90d6e2bf6b706b78e151f8a44e48efbca14b99a54e638b34d747b05bac2968/images/page/products/cosmosdb/dev-01-sql-api.svg)

[image reference](https://azurecomcdn.azureedge.net/cvt-4f90d6e2bf6b706b78e151f8a44e48efbca14b99a54e638b34d747b05bac2968/images/page/products/cosmosdb/dev-01-sql-api.svg)

### Additional information

[cosmos db](https://azure.microsoft.com/en-us/products/cosmos-db/#overview)

**Comment by Panquesito7** [comment]
Working on this. Thanks for making the issue. 👍
