### ISSUE TITLE
[OTHER] Release?

### ISSUE THREAD

**Issue by homotechsual** [devicons/devicon#1388]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### What would you like to share?

I've noticed a number of icons merged into Dev including some really useful additions like PowerShell, is there a threshhold required for a new release to go out or can this be done?

Loving the icons and the community behind them here :-)

**Comment by Panquesito7** [comment]
Hello! Thanks for being part of our community and for this suggestion. 😄 
We're planning to merge all the current icon PRs and later on make a release.

You can help us review to make the process faster.
Thanks for your patience. 🙂

**Comment by ConX** [comment]
Hi @Panquesito7, please let me know if you need any help with reviewing PRs, merging, or the release.

**Comment by PantheraRed** [comment]
Hello @ConX, feel free to [apply for maintainer](https://github.com/devicons/devicon/discussions/1436) or [ask questions regarding maintainer](https://github.com/devicons/devicon/issues/1471).

**Comment by canaleal** [comment]
This ticket is being closed because a new release has been made since it was created. You can view the latest release here: https://github.com/devicons/devicon/releases/tag/v2.16.0
