### ISSUE TITLE
[ICON REQUEST]: Quarkus name

### ISSUE THREAD

**Issue by JJDSNT** [devicons/devicon#1394]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Its a java framework

### Links and sources

[Official repo](https://github.com/quarkusio/quarkus)

<img src="https://camo.githubusercontent.com/62d4f160c458785b41aa5961dbf35295843fd582cb7a931e962c77d295bd23f9/68747470733a2f2f64657369676e2e6a626f73732e6f72672f717561726b75732f6c6f676f2f66696e616c2f504e472f717561726b75735f6c6f676f5f686f72697a6f6e74616c5f7267625f3132383070785f64656661756c742e706e672367682d6c696768742d6d6f64652d6f6e6c79">

**Comment by kilianpaquier** [comment]
Hello @JJDSNT, Quarkus was added to develop a few months ago : https://github.com/devicons/devicon/tree/develop/icons/quarkus

**Comment by canaleal** [comment]
Great catch @kilianpaquier, and nice suggestion @JJDSNT. 

Marking this issue as duplicate and closing.
