### ISSUE TITLE
[feat/icon]: Elasticsearch

### ISSUE THREAD

**Issue by issy123** [devicons/devicon#140]
something like this

![image](https://user-images.githubusercontent.com/9143253/47912437-f749bc00-de98-11e8-9669-e97f58b8be2e.png)

**Comment by iamclaytonray** [comment]
If you could, please file your issue (and any new issues) to the new repo/fork [here](https://github.com/iamclaytonray/devicon). Thanks!

**Comment by Dominic-Preap** [comment]
Any update?

**Comment by Panquesito7** [comment]
> Any update?

No, but if you want, I can make a PR to add this icon. 🙂

**Comment by Dominic-Preap** [comment]
Yes please, thank in advance.

**Comment by Panquesito7** [comment]
> Yes, please, thank in advance.

I'll work on it in some hours. Thanks. 🙂

**Comment by Dominic-Preap** [comment]
Any update so far 😉?

**Comment by BenSouchet** [comment]
This PR will cose the issue :) https://github.com/devicons/devicon/pull/1016
By the way this is also linked to https://github.com/devicons/devicon/issues/231

**Comment by BenSouchet** [comment]
For info there is currently a discussion to add or not the icon since elastic (the company behind elasticsearch) don't like that people use the glyph (the "E" icon) without the full brand wordmark ("elasticsearch") :(

**Comment by Thomas-Boi** [comment]
BenSouchet is correct. This is unfortunate. However, people can use the SVG from their [new branding page](https://brand.elastic.co/302f66895/p/06c73c-elastic-logo/b/35d033)
