### ISSUE TITLE
[feat/icon]: scikit-learn

### ISSUE THREAD

**Issue by avinash-mishra** [devicons/devicon#141]

**Comment by Berkmann18** [comment]
This (iirc) was already mentioned in #11

**Comment by iamclaytonray** [comment]
If you could, please file your issue (and any new issues) to the new repo/fork [here](https://github.com/iamclaytonray/devicon). Thanks!

**Comment by iamclaytonray** [comment]
Hello @avinash-mishra! Thanks for filing an issue! Please create individual issues for individual icons. Thanks!

**Comment by Thomas-Boi** [comment]
I'll be removing this since #449 is a better version
