### ISSUE TITLE
[ICON REQUEST]: p5.js

### ISSUE THREAD

**Issue by Chgv99** [devicons/devicon#1421]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

p5.js is a JavaScript library for creative coding. Widely popular for making generative art more accessible.

### Links and sources

https://p5js.org/
https://github.com/processing/p5.js
https://twitter.com/p5xjs
I haven't found the official logo uploaded by them, but their identity and graphic design was made by [Jerel Johnson](https://jereljohnson.com/)
https://seeklogo.com/vector-logo/441833/p5-js

**Comment by yeyeto2788** [comment]
Can I work on this one?

**Comment by yeyeto2788** [comment]
Any updates on this one?

**Comment by Chgv99** [comment]
> Can I work on this one?

Sorry for the late reply. Yes, you can work on this. 😊

**Comment by yeyeto2788** [comment]
Hey @Chgv99! Thanks for the reply but my message was for @Snailedlt or any other person able to assign tickets within this repo.

**Comment by Snailedlt** [comment]
@yeyeto2788 Yes ofc! :)
Feel free to just start working on it, since we usually don't assign issues to anyone. So next time you can just write a comment that you're working on it, and perhaps link to your branch or something so people can see if it's being actively worked on :)

**Comment by Snailedlt** [comment]
Official logo from their website:
![image](https://user-images.githubusercontent.com/43886029/196702613-a09b6cc1-0c0a-4b02-9fc6-fe9697329bff.png)

https://p5js.org/assets/img/p5js.svg
![](https://p5js.org/assets/img/p5js.svg)

**Comment by yeyeto2788** [comment]
That is exactly from where I took it from.
