### ISSUE TITLE
[ICON REQUEST]: GitHub Actions

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1423]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD. Build, test, and deploy your code right from GitHub. 

#### Website
https://github.com/features/actions

#### Official Logo
https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg
![](https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg)

**Comment by yeyeto2788** [comment]
Can I work on this one?

**Comment by Snailedlt** [comment]
@yeyeto2788 Yes sir!
Thanks in advance 💯
