### ISSUE TITLE
[ICON REQUEST]: IBM

### ISSUE THREAD

**Issue by esmiralha** [devicons/devicon#1430]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

IBM is a public cloud provider and a major player in the industry.

### Links and sources

https://www.ibm.com/brand/experience-guides/developer/resources/#logo

**Comment by Snailedlt** [comment]
IBM is a company, and not a developer tool, therefore it's out of scope for devicons.
[What icons do we accept?](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F#special-cases-see-this-discussion-for-more-details)
