### ISSUE TITLE
[BUG] devicon SVG preview is invisible on the website

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1434]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Because the website has a solid green background behind the SVG's in the preview box, icons that have the same color (devicon for example) become invisible.
![Screenshot_20221008_013243](https://user-images.githubusercontent.com/43886029/194675363-10199ada-034c-44ef-83a1-e7d68a0866d0.jpg)

### Possible fixes or solutions

Add option to change the background to a different color or a checkered background

**Comment by Panquesito7** [comment]
I think that's actually possible already.

![image](https://user-images.githubusercontent.com/51391473/217379828-5b432af0-70ea-4cde-9620-0775c805036c.png)

It may not look _that_ good, but you can change the background and remove the checkerboard.
I still think we should change the background color to look a little bit darker by default to prevent this. Maybe one of these colors?

New: `#409E66` / `#45A96D`
Current: `#60be86`
