### ISSUE TITLE
[bug/apple-icon]: font is squared off

### ISSUE THREAD

**Issue by suxiaogang** [devicons/devicon#144]
![image](https://user-images.githubusercontent.com/1567518/49285141-a34ee900-f4d1-11e8-983c-2f181958411b.png)

**Comment by iamclaytonray** [comment]
If you could, please file your issue (and any new issues) to the new repo/fork [here](https://github.com/iamclaytonray/devicon). Thanks!

**Comment by amiceli** [comment]
Any update for this icon ?

**Comment by amiceli** [comment]
I created a PR for this : https://github.com/konpa/devicon/pull/177

**Comment by amacado** [comment]
As I can see this issue seems to be fixed
