### ISSUE TITLE
[ICON REQUEST]: YAML

### ISSUE THREAD

**Issue by KayleeDavisGitHub** [devicons/devicon#1446]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

YAML is a human-readable data-serialization language. With the inclusion of Markdown and editors I think this programming language falls within scope. 

#### About:
https://en.wikipedia.org/wiki/YAML

#### Image:
https://en.wikipedia.org/wiki/File:Official_YAML_Logo.svg

### Additional information

I found this closed issue from a long time ago that included some support on getting the YAML logo included, I don't know if this was ever completed or if the YAML logo was ultimately removed.

https://github.com/devicons/devicon/pull/1142

**Comment by weh** [comment]
i think this is a duplicate of #1446
there is a PR already #1448

**Comment by KayleeDavisGitHub** [comment]
@weh this is #1446, #1448 was made as a result of this :)

**Comment by weh** [comment]
hahaha sorry, mi fault. must have been before coffee.
