### ISSUE TITLE
[ICON REQUEST]: Astro

### ISSUE THREAD

**Issue by agriffard** [devicons/devicon#1464]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Astro, static site generator similar to Next.js, Gatsby, ...

### Links and sources

https://astro.build/
https://github.com/withastro/astro/blob/dd354f83e8d5191a5e962c999f0a0d859da94a7c/assets/brand/logo-square-white.png
https://github.com/withastro/astro/blob/dd354f83e8d5191a5e962c999f0a0d859da94a7c/assets/brand/logo.svg

**Comment by lunatic-fox** [comment]
Hello there @agriffard!
Thank you for the request, but **Astro** icon is already `in-develop` state.
* #1034 
* #1350 

To be extra sure for future requests, you can also check if the icon is in `icons` repository of `develop` branch.
