### ISSUE TITLE
[OTHER] Update the issue template for icon requests to be more detailed

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#1467]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### What would you like to share?

It would be nice if there was a stricter format on the icon requests. So the [icon_request.yml](https://github.com/devicons/devicon/blob/master/.github/ISSUE_TEMPLATE/icon_request.yml) issue template should be updated.

#### Required:
1. Link to resources (website, github, npm, etc..) (**Examples:** https://github.com/sveltejs , https://svelte.dev/ , https://www.npmjs.com/package/svelte)
2. Link to icons. Official icons should be linked regardless of type, and unofficial if SVG's aren't available from the official ones. (**Example:** https://github.com/sveltejs/branding)
3. Preview of the most important icons (**Example:** `![](https://raw.githubusercontent.com/sveltejs/branding/c4dfca6743572087a6aef0e109ffe3d95596e86a/svelte-logo.svg)`)

#### Encouraged:
1. List of related tags/categories that the tool falls under (**Example:** `programming`, `language`)
2. Alternative names (**Example:** `go`, `golang`)
3. Main/primary color. Especially important if the color should be different than the most dominant color in the icons. For example, some tools might have a different primary color than the one most prevalent in the icons. (**Example:** `#2fff2f`)

**Comment by Snailedlt** [comment]
I'll work on this once I get some more free time. Hopefully this weekend or next week :)

**Comment by Panquesito7** [comment]
I guess this is already done. Closing.

**Comment by Snailedlt** [comment]
Yes, but it's still in develop, so the changes aren't applied until it's merged into master
