### ISSUE TITLE
[FEATURE REQUEST] Validate and add snippet to `devicon.json` in VS Code

### ISSUE THREAD

**Issue by lunatic-fox** [devicons/devicon#1481]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

In `devicon.json`, we can sometimes miss a property or even get confused about the value that should be added.

### Possible Solution

I think many users use VS Code or GitHub Codespaces. Also I got inspired by [@BenSouchet comment](https://github.com/devicons/devicon/issues/988#issuecomment-1265112532) in order to create a validator and a snippet for a new entry to `devicon.json` in VS Code.

This is the [***link***](https://github.com/lunatic-fox/devicon/tree/vscode_intellisense) to a branch with this proposed feature.

## Feature overview
Once you start typing `new` on `devicon.json` the snippet suggestion is activated.
![new-entry](https://user-images.githubusercontent.com/76992016/198091829-57b6daa5-26c3-4fe4-a2ff-5808e3cf4e4c.png)

Hitting `Enter` will create a template object with all required properties.
![new-entry-json](https://user-images.githubusercontent.com/76992016/198092148-be988b3d-ad85-40ac-93ab-8d3359ee28dd.png)

The validator will be working, that's why some parts are underlined in yellow.
If you hover over some property it'll show a short description.
> *All descriptions were based on* [*Updating `devicon.json`*](https://github.com/devicons/devicon/wiki/Updating-%60devicon.json%60).
![hover-properties](https://user-images.githubusercontent.com/76992016/198092556-be48cefe-8f5e-4d45-93e9-8e0fc1702ccb.png)

`versions.svg`, `versions.font`, `aliases[].base` and `aliases[].alias` show autocompletion suggestions with all possible icon versions.
![auto-completion-suggestions](https://user-images.githubusercontent.com/76992016/198093643-0874a841-9b48-4504-927d-983f82d25e49.png)

`aliases[].base` and `aliases[].alias` are suggested properties, because the objects of `aliases` are optional.
![auto-completion-suggestions-properties](https://user-images.githubusercontent.com/76992016/198094480-1606f231-4921-4c24-b9ae-45ebe2b85fa7.png)

## Validation
* `name` - `^[0-9a-z-]+$`
* `altnames[]` - *none*
* `tags[]` - `tags-enum.json`
  > ***Needs to be standardized!***
* `versions`
  * `.svg[]` - *icon versions*
  * `.font[]` - *icon versions*
* `color` - `^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$`
  > ***Can be standardized to six digits!***
* `aliases[]`
  * `.?base` - *icon versions*
  * `.?alias` - *icon versions*

### Additional information

I made `tags-enum.json` just by grouping all existent tags in `devicon.json` `develop` branch with Node.js.

I think in a strategy of breaking tags by `-`, `/` and `space` in order to be just a set of single words. But I need opinions on that!

**Comment by Snailedlt** [comment]
Looks awesome! Ship it! 😁
The tags probably need to be reworked though, but that can also come at a later date :)

**Comment by lunatic-fox** [comment]
Hello there @Snailedlt!
I agree about reworking on `tags`, but I think this is long term discussion.
I'll be making a derivative branch using the generic validation of type on `tags`, that way may be possible to add the other functionalities, while `tags` is not yet standardized.

**Comment by lunatic-fox** [comment]
[**vscode_intellisense_no_tags**](https://github.com/lunatic-fox/devicon/tree/vscode_intellisense_no_tags) branch.
- `tags` property has a generic validation against string type
- `aliases` property has validation to its inner objects

**Comment by Snailedlt** [comment]
Couldn't agree more! I think we should use the one you made with the tags though, makes it easier to add more tags, and refactor them later on :)

**Comment by lunatic-fox** [comment]
Great! 🤩
So later I'll be doing a pull request of the first branch with the updates of the second one.

**Comment by Snailedlt** [comment]
Great! Can't wait to get this merged! Will be a huge improvement, and surely speed up the process both for code contributors and reviewers! 🚀
