### ISSUE TITLE
RFC: Icon Types

### ISSUE THREAD

**Issue by iamclaytonray** [devicons/devicon#149]
As FontAwesome (and many others do), should we provide icon variants? The ones I was thinking of would include:

`outline`
`solid`
`regular`

Thoughts? This would be put in the backlog until we get most issues and PRs dealt with but figured we can start discussion around it now for when we get through open issues and PRs!

**Comment by Berkmann18** [comment]
That's a good idea, how would you define each variant?

**Comment by iamclaytonray** [comment]
Well, I like what Julien did with including text and non-text variants. I think I'd define variants the way FontAwesome does + what Julien did. It's a lot of extra icons but I think it solves a lot more use-cases

**Comment by Berkmann18** [comment]
Oh yeah, that makes sense.
That would definitely be a good thing which would allow for flexibility.
