### ISSUE TITLE
[BUG] Jira plain-wordmark font (Visual bug/Improper rendering)

### ISSUE THREAD

**Issue by PantheraRed** [devicons/devicon#1500]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

In this bug, the Jira plain-wordmark font can be seen missing some colors. I have verified this bug on both android chrome and windows chrome.

Android chrome:
<img src="https://user-images.githubusercontent.com/41539361/199949351-0ccb44bc-e368-4187-878a-33c2f11becb2.png" height="265" />

Windows chrome:
![image](https://user-images.githubusercontent.com/41539361/199949158-c568140e-b648-4252-88aa-ddbe03ef3875.png)

### Possible fixes or solutions

To my guess, this was a problem with Iconmoon's parsing back when Jira's plain-wordmark font version was generated. 
This screenshot from https://github.com/devicons/devicon/pull/1062#issuecomment-1073113477 shows the visual bug.
![image](https://camo.githubusercontent.com/69eb676fe5c86aaedffe01a284831341dddb5325bfc99352ced1d443489cdbb9/68747470733a2f2f692e696d6775722e636f6d2f6b776b356e62372e706e67)

However, when I import `jira-plain-wordmark.svg` manually it works fine.
![image](https://user-images.githubusercontent.com/41539361/199963343-84713211-765f-4cfd-a187-3cf303bff741.png)

In my opinion best solution would be to recreate `jira-plain.svg` and `jira-plain-wordmark.svg` properly and regenerate using Iconmon for best results.

**Comment by lunatic-fox** [comment]
Great catch! 🕵🏼‍♂️
Thank you for this contribution! 🤩

I'll make a fixing PR for this icon soon.

**Problems:**
- major: paths are not unified
- minor: icons have `fill` property
