### ISSUE TITLE
[ICON REQUEST]: <ROS>

### ISSUE THREAD

**Issue by bardpedersen** [devicons/devicon#1504]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Robot operation system

### Links and sources

https://www.ros.org

**Comment by luizcarloscf** [comment]
It seems to me that this issue is duplicated. https://github.com/devicons/devicon/issues/256
ROS icon is already in develop https://github.com/devicons/devicon/pull/1100

**Comment by Snailedlt** [comment]
Duplicate of #256
