### ISSUE TITLE
[BUG] Bad code in `discordjs-plain-wordmark.svg`

### ISSUE THREAD

**Issue by cyberalien** [devicons/devicon#1518]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

`<g stroke="null" fill="#2A2C3E">`

Null is not a valid color

### Possible fixes or solutions

`<g stroke="none" fill="#2A2C3E">`

**Comment by cyberalien** [comment]
Same issue in related icon `discordjs-original-wordmark`

**Comment by cyberalien** [comment]
Also `qt-original` contains `stroke="null"`

**Comment by Snailedlt** [comment]
If I understand this correctly, you want `stroke="null"` to be removed, right?

**Comment by cyberalien** [comment]
Yes, removing it is one of solutions. Another solution is to set value to `none`, which I guess was the intended value but someone made a typo (probably after long coding session dealing with `null` 😄).

**Comment by Snailedlt** [comment]
Ahh, now I see that the solution is different from the bug!
Yeah, I would definitely have done the same 😅
