### ISSUE TITLE
[BUG] Invalid color in polygon-plain.svg

### ISSUE THREAD

**Issue by cyberalien** [devicons/devicon#1520]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

`fill="rgb(%100,%100,%100)"` is not a valid color. % is on wrong side of numbers.

### Possible fixes or solutions

Change to `fill="#fff"`

**Comment by Snailedlt** [comment]
I don't think I'll have time to work on this before next year, so I'm unassigning it.
@cyberalien @lunatic-fox feel free to make a PR if you have time, and I'll make sure to review it ASAP
