### ISSUE TITLE
[ICON REQUEST]: <C++>

### ISSUE THREAD

**Issue by AM-Darshan** [devicons/devicon#1566]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

C++ is a programming language

### Links and sources

https://commons.wikimedia.org/wiki/File:ISO_C%2B%2B_Logo.svg

**Comment by PantheraRed** [comment]
Hello @AM-Darshan! I don't understand what's the issue here. The icon already exists [here](https://github.com/devicons/devicon/blob/develop/icons/cplusplus/cplusplus-original.svg).
