### ISSUE TITLE
[BUG]: Unable to load/view icon

### ISSUE THREAD

**Issue by Kellsonphilips** [devicons/devicon#1599]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

Unable to view or load SVG icon which also affects those that use it in their skills section. 

![Screenshot 2022-12-30 at 00 01 42](https://user-images.githubusercontent.com/81332784/209994902-6a09bb4b-2ac1-4c8d-bfea-f935d5155329.png)

![Screenshot 2022-12-30 at 00 02 31](https://user-images.githubusercontent.com/81332784/209994907-609b1469-cddf-4e84-a784-0e26e03d4f74.png)

All icons affeced

![Screenshot 2022-12-30 at 00 06 20](https://user-images.githubusercontent.com/81332784/209995026-16fdb2b9-4e6d-4d22-97c4-a103f9df1d46.png)

### Possible fixes or solutions

I think it's probably a GitHub action thing but I might be wrong. 
If someone is able to view the icons please indicate or it's a general issue. 
Thanks 

### Additional information

Screens are provided for a clear issue.

**Comment by PantheraRed** [comment]
Hello @Kellsonphilips, there can be a few reasons as mentioned [here](https://github.com/devicons/devicon/discussions/1563).

**Comment by Kellsonphilips** [comment]
I'm using Safari and it's been working fine but then stopped.  I do not have any new extension installed and so, I do not know what causes the problem.

**Comment by lunatic-fox** [comment]
Hello @Kellsonphilips!

I'm not using Safari, but I've tried to reference the image the way you did in this comment and it broke too.

|Icon 1|Icon 2|
|:-:|:-:|
|<img src="https://github.com/devicons/devicon/blob/master/icons/sass/sass-original.svg" title="sass" alt="sass" width="40"/>|<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/devicon/devicon-original.svg" title="devicon" alt="devicon" width="40"/>|

If Safari is able to show **Icon 2**, that means you can use the icons that way:
Base URL: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/`
```html
<img
  src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/[ICON NAME]/[ICON NAME & VERSION].svg"
  title="[ICON NAME]"
  alt="[ICON NAME]"
  width="40"/>
```

Wish for the best!

**Comment by Kellsonphilips** [comment]
> Hello @Kellsonphilips!
> 
> I'm not using Safari, but I've tried to reference the image the way you did in this comment and it broke too.
> 
> Icon 1	Icon 2
> <img alt="sass" width="40" src="https://github.com/devicons/devicon/blob/master/icons/sass/sass-original.svg">	<img alt="devicon" width="40" src="https://camo.githubusercontent.com/2ae31b5e9b7e63d74012b8b318def539ae9da4809fe3b12ca6c362fec251c859/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f64657669636f6e732f64657669636f6e2f69636f6e732f64657669636f6e2f64657669636f6e2d6f726967696e616c2e737667">
> If Safari is able to show **Icon 2**, that means you can use the icons that way: Base URL: `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/`
> 
> ```
> <img
>   src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/[ICON NAME]/[ICON NAME & VERSION].svg"
>   title="[ICON NAME]"
>   alt="[ICON NAME]"
>   width="40"/>
> ```
> 
> Wish for the best!

Thanks for this, let me try it out and see.

**Comment by Kellsonphilips** [comment]
This is the fix for this bug when referencing the icon URL, 

Do not use the GitHub URL reference:
<img src="https://github.com/devicons/devicon/blob/master/icons/html5/html5-original.svg"  title="HTML5" alt="html5" height="50" width="40" />

Use the  example below that uses the Base URL: 
<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" title="html5" alt="html5"
  width="40" />

Thanks to @lunatic-fox  for helping 💪

**Comment by lunatic-fox** [comment]
No problem! 🙂
Actually this is the original way to reference the image see on [devicon website](https://devicon.dev) and on [README](https://github.com/devicons/devicon). You can also reference as raw user content of GitHub, but cdn is usually shorter.
