### ISSUE TITLE
[FEATURE REQUEST] <New Icon Color>

### ISSUE THREAD

**Issue by BeKowalsky** [devicons/devicon#1602]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Problem

I want to request different colors to GitHub icon, because when I put this on my readme, in dark mode, the icon practically disappears, and I cant change the color, because, apparently GitHub don't accept colors changes in markdown styles. Thanks for your attention.

### Possible Solution

Maybe adding other color that doesn't interfere with light and dark mode.

**Comment by lunatic-fox** [comment]
Hello there!
Take a look at [Devicon API](https://github.com/lunatic-fox/deviconapi).
You can change colors and alternate the theme to GitHub Markdown.
You can also use the [Devicon API Interface](https://lunaticfox.vercel.app/deviconApi) if you want. 🙂

**Comment by BeKowalsky** [comment]
Thank you very much! I used [Devicon API Interface](https://lunaticfox.vercel.app/deviconApi) and got the icon with a configuration that changes colors depending on whether the person uses dark or light mode.
