### ISSUE TITLE
[ICON REQUEST]: Styled Components

### ISSUE THREAD

**Issue by fellowbeard** [devicons/devicon#1607]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

This is a popular styling tool to use with React

### Links and sources

https://styled-components.com/

https://github.com/styled-components/styled-components

**Comment by Gautam25Raj** [comment]
`Styled Component` was already requested on: [Icon Request: Styled Component](https://github.com/devicons/devicon/issues/332)
