### ISSUE TITLE
[ICON REQUEST]: Powershell

### ISSUE THREAD

**Issue by CyberC4p0** [devicons/devicon#1614]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

PowerShell is a cross-platform task automation solution made up of a command-line shell, a scripting language, and a configuration management framework. PowerShell runs on Windows, Linux, and macOS.

### Links and sources

https://learn.microsoft.com/en-us/powershell/

<img alt="Powershell 5" width="100px" style="padding-right:10px;" src="https://learn.microsoft.com/en-us/powershell/media/index/ps_black_128.svg" />

Powershell 7 Icon: https://learn.microsoft.com/en-us/powershell/media/index/ps_black_128.svg

<img alt="Powershell 7" width="100px" style="padding-right:10px;" src="https://learn.microsoft.com/en-us/powershell/media/index/powershell_128.svg" />

Powershell 5 Icon: https://learn.microsoft.com/en-us/powershell/media/index/powershell_128.svg

<img alt="Powershell Gallery" width="100px" style="padding-right:10px;" src="https://learn.microsoft.com/en-us/powershell/media/index/avatar_128.svg" />

Powershell Gallery Icon: https://learn.microsoft.com/en-us/powershell/media/index/avatar_128.svg

**Comment by luizcarloscf** [comment]
Duplicated: https://github.com/devicons/devicon/issues/364
Already in develop: https://github.com/devicons/devicon/pull/1219

**Comment by CyberC4p0** [comment]
> Duplicated: https://github.com/devicons/devicon/issues/364
> 
> Already in develop: https://github.com/devicons/devicon/pull/1219

This issue was started 2 years ago, it was put into development a few months ago, and Powershell icons still haven't been added to the main repository.

**Comment by BenSouchet** [comment]
> This issue was started 2 years ago, it was put into development a few months ago, and Powershell icons still haven't been added to the main repository.

@CyberC4p0 Simply because a new version of devicon hasn't been released/created since the icon has been merged in the dev branch. Wait or ask for a new version to be release to the maintainers.

**Comment by CyberC4p0** [comment]
> > This issue was started 2 years ago, it was put into development a few months ago, and Powershell icons still haven't been added to the main repository.
> 
> 
> 
> @CyberC4p0 Simply because a new version of devicon hasn't been released/created since the icon has been merged in the dev branch. Wait or ask for a new version to be release to the maintainers.

I completely overlooked at the develop branch. I apologize. Thanks a lot for the clarification 🙌

**Comment by lunatic-fox** [comment]
Thank you @CyberC4p0 for requesting! 👍🏼
Also thank you @luizcarloscf and @BenSouchet for your feedback! 🚀

Closing this issue.
