### ISSUE TITLE
Ruby and Rails SVGs not rendering properly

### ISSUE THREAD

**Issue by caseydulong** [devicons/devicon#162]
The Ruby and Rails SVGs do not render properly with the code copied from the box.  However, if I right click on the image and open it in a new tab, it displays perfectly.  If I copy the code from the inspector on that page, it will work fine.  Not only that, if I use the code from the inspector, and the code copied from the box on the frontend, both will display properly.  I think the there is a missing URL somewhere, but I am not very familiar with SVGs.
<img width="123" alt="Ruby SVG is incomplete" src="https://user-images.githubusercontent.com/23215675/55574990-cede1c00-56db-11e9-824f-90966f2bc80a.png">

**Comment by amacado** [comment]
@caseydulong hey, i know this is an old issue and in the latest version i'm not able to confirm this bug. Can you look it up? I will close this issue for now. Feel free to open it again if bug still exist.

**Comment by HoriKyouko** [comment]
![Bug](https://user-images.githubusercontent.com/26206463/87207741-ae3b4380-c2da-11ea-8774-d4df6ade9b7c.png)
Getting the same issue. After looking at it the only thing that's rendering is the path with an explicit 'fill="9E1209"'. All the other fills have url(#a) and go all the way to #p.

**Comment by amacado** [comment]
@HoriKyouko could you provide some sample code? maybe via [codepen.io](https://codepen.io/pen/)

**Comment by HoriKyouko** [comment]
Here is some sample code. The first image on the left shows the code as is with the bug, the middle image highlights that what can be seen is in fact things that don't contain url(#@), @ being my replacement for any alpha character, and the right image shows all url(#@) replaced with some colors that look similar to what can be seen in the example when copying the svg from the web page. Though not correct of course.

[https://codepen.io/HoriKyouko/pen/GRoGQRN?editors=1100](url)

One thing I did find strange was the use of url(#@) in the first place and thought maybe it was a css call to some gradient values/functions that were not transferred over properly. As seen in the preview example:
![image](https://user-images.githubusercontent.com/26206463/87214595-fa4ab000-c2fb-11ea-9647-7253a43e1b21.png)
there looks to be some gradient happening with the upper part of the gem close to the top where it is white and then slowly gets redder as it gets closer to the center of the gem.
