### ISSUE TITLE
[ICON REQUEST]: Railway

### ISSUE THREAD

**Issue by JuggernOtt81** [devicons/devicon#1620]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

railway hosting (usurping herkou for free/low cost users)

### Links and sources

[https://railway.app/design](https://railway.app/design)

**Comment by Aadarsh805** [comment]
> ### I have searched through the issues and didn't find my problem.
> * [x]  Confirm
> 
> ### About the icon
> railway hosting (usurping herkou for free/low cost users)
> 
> ### Links and sources
> https://railway.app/design
> 
> ### Additional information
> _No response_

Hey, you should fix the issue name, put the `railway app` in place of `<icon name>`
