### ISSUE TITLE
[ICON REQUEST]: illustrator-original, photoshop-original

### ISSUE THREAD

**Issue by Contrick64** [devicons/devicon#1628]
### I have searched through the issues and didn't find my problem.

- [x] Confirm

### About the icon

I'm attempting to programattically fill in my icons, and these are two that don't have -original versions.

### Links and sources

[Official site](https://www.adobe.com/creativecloud.html)

### Additional information

These icons exist as -plain variants, they're just missing the -original version

Thanks!

**Comment by lunatic-fox** [comment]
Hello there!
Thank you for your request and sorry for the late response! 😅

I see this is an update request for two icons. So, could you please make one icon request per technology? That way you'll be feedback when they are merged to `develop` branch. 😀

- \[ICON REQUEST]: illustrator
- \[ICON REQUEST]: photoshop

As soon as you made it you can close this issue.

**Comment by Contrick64** [comment]
All set, thanks!
