### ISSUE TITLE
[ICON REQUEST]: <Informatica>

### ISSUE THREAD

**Issue by surajbanerjee** [devicons/devicon#1632]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Informatica is a data integration tool based on ETL architecture. Using this icon in my profile.

### Links and sources

Found this here `https://www.vectorlogo.zone/logos/informatica/index.html`
--
<img src="https://logos-download.com/wp-content/uploads/2020/07/Informatica_Logo.svg" width="100px">

<img src="https://www.vectorlogo.zone/logos/informatica/informatica-icon.svg" width="100px">

**Comment by surajbanerjee** [comment]
Duplicate

**Comment by Panquesito7** [comment]
Duplicate of #1631.
