### ISSUE TITLE
[ICON REQUEST]: Vite

### ISSUE THREAD

**Issue by dostonnabotov** [devicons/devicon#1638]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Next Generation Frontend Tooling

### Links and sources

- [Official webpage](https://vitejs.dev/)
- [Vite logo](https://github.com/vitejs/vite/blob/main/docs/images/vite.svg)

### Additional information

n/a

**Comment by lunatic-fox** [comment]
Hello there!
Thank you for the requesting, but this icon it's already in `develop` branch. 👍🏼
- #1472

Closing this issue.
