### ISSUE TITLE
[ICON REQUEST]: framermotion

### ISSUE THREAD

**Issue by atlamors** [devicons/devicon#1643]
### I have searched through the issues and didn't find my problem.

- [x] Confirm

### About the icon

Framer motion is a powerful react animation library

### Links and sources

[https://www.npmjs.com/package/framer-motion](https://www.npmjs.com/package/framer-motion)
[https://github.com/framer/motion#readme](https://github.com/framer/motion#readme)

This is the [logo they use on their official documents,](https://www.framer.com/motion/) and the only OEM version of the framer motion logo I could find in SVG.
```
<svg xmlns="http:www.w3.org/2000/svg" viewBox="0 0 14 21" role="presentation">
    <path d="M0 0h14v7H7zm0 7h7l7 7H7v7l-7-7z" fill="currentColor"></path>
</svg>
```

The wordmark portion of the logo uses the **GT Walsheim** font and doesn't have an SVG format.

**Comment by Gautam25Raj** [comment]
Working on it. 🚀
