### ISSUE TITLE
[ICON REQUEST]: Intuit Karate

### ISSUE THREAD

**Issue by human02** [devicons/devicon#1646]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

It's a technology that people work and this repo can benefit from adding it. It can help the repo become a place to get all the major icons that are required by people.

### Links and sources

Hi,

I have worked with Intuit Karate and I could not find the certain icon in the repo.
This request is specifically for Intuit Karate.
I have attached the screenshot below for the icon:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/42168454/215241802-81daf28b-1db7-4b25-aa62-cadd5f6f4cd0.png">

link: https://github.com/karatelabs/karate

**Comment by kilianpaquier** [comment]
Hello @human02, the logo was added to develop branch a while ago.

https://github.com/devicons/devicon/tree/develop/icons/karatelabs
