### ISSUE TITLE
DevOps (CircleCI): `build step` to publish latest version on Github Pages

### ISSUE THREAD

**Issue by rjlopezdev** [devicons/devicon#165]
I've noticed [Devicon Web](https://konpa.github.io/devicon/) is not updated with the latest icons.

I could design a simple CI cycle to atomate this proccess:

**Steps**

* First: build static files
* Second: commit new version to `gh-pages` branch

**Triggers**

* Commiting over `master` branch

If you are interested, I would need the scripts you use to publish on `gh-pages` 🙏

**Comment by konpa** [comment]
There is none... I want to automate the process (as well as the one to generation the font files) for a long time but never took the time to do it... For now, `gh-pages` is just an Angular SPA with `master` branch as submodule.

**Comment by rjlopezdev** [comment]
Ouh! I see...
I could work on this first:

* Rewriting old angular.js app into a new Angular 7.
* Script to read `fonts` directory to parse it & generate a JSON with new additions.

Once this is done, build CI cycle.

If you agree that, I could work on it.
Unless, I'll close this issue.

**Comment by konpa** [comment]
Yes sure, would be great !

**Comment by amacado** [comment]
@rjlopezdev are u still interested in contributing? Because an automated build process including the font generation would be amazing.

**Comment by amacado** [comment]
I'm thinking of integrating the `gh-pages` branch into the `master` branch so we do not face the issue of keeping the two branches up to date anymore, any thoughs of this?

**Comment by amacado** [comment]
Since v2.8.0 we are publishing the devicon.dev from the master branch (`docs/`) it's always up to date with the most recent changes.
