### ISSUE TITLE
[ICON REQUEST]: Astro

### ISSUE THREAD

**Issue by emir4169** [devicons/devicon#1651]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

It is a currently popular javascript  framework.

### Links and sources

https://astro.build/
 https://astro.build/press/

**Comment by lunatic-fox** [comment]
Thank you for requesting, but this icon is already in `develop` branch.
- #1350
- #1543

Remember that you can chat with us about the project via [Devicon Discord Community](https://discord.gg/hScy8KWACQ) channel! 😀

Closing this issue.
