### ISSUE TITLE
[ICON REQUEST]: Instagram

### ISSUE THREAD

**Issue by asaggse** [devicons/devicon#1659]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Instagram is a photo and video sharing social networking

### Links and sources

https://commons.wikimedia.org/wiki/File:Instagram_logo_2022.svg

**Comment by kilianpaquier** [comment]
Hello @asaggse, I don’t think social media are accepted anymore on devicon, as stated in https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F.

**Comment by weh** [comment]
i also think this is out of scope
