### ISSUE TITLE
[ICON REQUEST]: <scikit-learn>

### ISSUE THREAD

**Issue by danaikorre** [devicons/devicon#1676]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Machine Learning in Python

### Links and sources

https://scikit-learn.org/stable/

### Additional information

It would be great to have more data science icons.

**Comment by Panquesito7** [comment]
Duplicate of #1032.

**Comment by lauxpaux** [comment]
Came here to request the same icon
