### ISSUE TITLE
[ICON REQUEST]: QwikJS

### ISSUE THREAD

**Issue by FabbSantos** [devicons/devicon#1693]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

QwikJS is a JS framework and HTML first. It is becoming more popular because of its performance.

### Links and sources

Here's the official website:
https://qwik.builder.io/

Github:
https://github.com/BuilderIO/qwik

**Comment by sinuheshinbr** [comment]
@FabbSantos This icon is already at develop branch.  [PR#1435](https://github.com/devicons/devicon/pull/1435)

**Comment by lunatic-fox** [comment]
Thank you @FabbSantos for this request and @sinuheshinbr for the notification! 📝🔍✅🚀
Closed.
