### ISSUE TITLE
[ICON REQUEST]: WebAssembly, or WASM

### ISSUE THREAD

**Issue by juleshenry** [devicons/devicon#1723]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Webassembly is efficient, fast, secure and open source. WASM renders applications like AutoCAD previously unthinkable to be run the browser, runnable.

### Links and sources

Official Website
https://webassembly.org/
Official Logo 
https://webassembly.org/css/webassembly.svg
Awesome projects ... 
https://github.com/mbasso/awesome-wasm

### Additional information

This icon will help users in the burgeoning community promote their interest. Thank you for your consideration!

**Comment by PantheraRed** [comment]
Already exists in [`develop`](https://github.com/devicons/devicon/tree/develop/icons/wasm) branch @juleshenry. If it is missing any version, do let know. Thank you.

**Comment by juleshenry** [comment]
I'm new to the project. I didn't know. Thanks so much @PantheraRed  !
