### ISSUE TITLE
Icon request: Objective C

### ISSUE THREAD

**Issue by kaangokdemir** [devicons/devicon#173]
Great project. It would be great to see Objective C .svg and icon also. 

link: https://assets.exercism.io/tracks/objective-c-bordered-turquoise.png

**Comment by thenick775** [comment]
Bumped because I'd also appreciate this

**Comment by tupaschoal** [comment]
This was added by #425 and already appears on https://devicon.dev/, so it can likely be closed

**Comment by amacado** [comment]
Thanks for the hint @tupaschoal!
