### ISSUE TITLE
[ICON REQUEST]: Angular Material

### ISSUE THREAD

**Issue by maikofelix47** [devicons/devicon#1736]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Angular Material Design is the most commonly used component library by Angular developers

### Links and sources

Website : https://material.angular.io/

Logo and Resources : https://angular.io/presskit#angular-material

**Comment by kilianpaquier** [comment]
Hello @maikofelix47, as we have this Angular icon added recently on develop branch https://github.com/devicons/devicon/blob/develop/icons/angular/angular-original.svg. Which additional icons would you like to have ? Because there're a lot referenced in the provided press kit !
