### ISSUE TITLE
[ICON REQUEST]: <icon name>

### ISSUE THREAD

**Issue by nazarenkodima** [devicons/devicon#1737]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Cypress logo icon. One of technologies we use in web development community

### Links and sources

official website - https://docs.cypress.io/guides/overview/why-cypress
cypress repo - https://github.com/cypress-io/cypress

svg example can be found at - https://react-icons.github.io/react-icons/search?q=cypress

**Comment by lunatic-fox** [comment]
Thank you for contributing with this issue!
However, `cypressio` icons are already ![](https://img.shields.io/badge/-in--develop-fbca04)
- #1097
- #223
