### ISSUE TITLE
[ICON REQUEST]: Ubuntu

### ISSUE THREAD

**Issue by jeremygau** [devicons/devicon#1740]
### I have searched through the issues and didn't find my problem.

- [x] Confirm

### About the icon

one of the most used linux distribution

### Links and sources

[Ubuntu.fr](https://www.ubuntu-fr.org/)

### Additional information

I have seen the ubuntu-plain but i need the ubuntu-original

**Comment by lunatic-fox** [comment]
Thank you for contributing with this issue! 🚀

`ubuntu` also has new icons. Therefore, those who want to update the icons for this technology, consider the icons below.
|`original`|`original-wordmark`|
|:-:|:-:|
|<img alt="original" width="256" src="https://user-images.githubusercontent.com/76992016/235578001-27f0a3f6-9fd1-4ae0-ac1b-e4467a19ae2a.svg"/>|<img alt="original-wordmark" width="256" src="https://user-images.githubusercontent.com/76992016/235578004-86bac734-8b96-426d-aa7f-8305c7f153df.svg"/>|

Remember that `plain` and `plain-wordmark` versions should be based on the same icons.

**Comment by Gautam25Raj** [comment]
Working on it. 🚀
