### ISSUE TITLE
[ICON REQUEST]: elastic-search

### ISSUE THREAD

**Issue by umershah212** [devicons/devicon#1746]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Elasticsearch is a rising technology that is now being used by alot of companies

### Links and sources

https://www.elastic.co/

**Comment by lunatic-fox** [comment]
Thank you for contributing with this issue!
However, `elasticsearch` icons are already ![](https://img.shields.io/badge/-in--develop-fbca04)
- #1255
