### ISSUE TITLE
[ICON REQUEST]: KDE Neon

### ISSUE THREAD

**Issue by pickbreaker** [devicons/devicon#1754]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Icon of the KDE Neon distro

### Links and sources

[KDE Neon Website](https://neon.kde.org)
[Logo Source](https://collaborate.kde.org/s/gT44wHjpDdqqDxL?path=%2F)

**Comment by dotarjun** [comment]
Working on this
