### ISSUE TITLE
Icon request: iOS/OSX development

### ISSUE THREAD

**Issue by shankarmadeshvaran** [devicons/devicon#176]

**Comment by amacado** [comment]
@shankarmadeshvaran  requested to add icons related to iOS development such as 
- macOS
- tvOS
- iOS
- SwiftUI
- Xcode 

and more tool icons to iOS development

**Comment by Thomas-Boi** [comment]
Hi @shankarmadeshvaran please split this into multiple requests for each icon. Thank you.
