### ISSUE TITLE
[BUG] svelte-original.svg is stretched to match width

### ISSUE THREAD

**Issue by blarknes** [devicons/devicon#1760]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

The svelte-original.svg icon is stretched to match the width of the canvas.

Current svelte-original:
https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg

It should be thinner, as it can be seen here:
https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-plain.svg
https://svelte.dev/_app/immutable/assets/stopwar-947a4798.svg

### Possible fixes or solutions

I think the easiest way to solve it would be simply changing the color of svelte-plain to orange. As it has the correct width.

**Comment by PantheraRed** [comment]
Hello @blarknes, seems like this issue has been fixed in the [develop](https://github.com/devicons/devicon/tree/develop) branch https://github.com/devicons/devicon/blob/develop/icons/svelte/svelte-original.svg

**Comment by blarknes** [comment]
Oh Hello! So sorry! Thanks!
