### ISSUE TITLE
[ICON REQUEST]: dev.to

### ISSUE THREAD

**Issue by redhcp** [devicons/devicon#1768]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Site of interest to the community where we share a post about IT/Programming

### Links and sources

https://dev.to/

**Comment by dotarjun** [comment]
@redhcp This icon wont be added. Pls refer to the [not allowed](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F#not-allowed-not-exhaustive) section

**Comment by PantheraRed** [comment]
> @redhcp This icon wont be added. Pls refer to the [not allowed](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F#not-allowed-not-exhaustive) section

I didn't notice this issue. Thank you for bringing it to my notice. 👍
