### ISSUE TITLE
[ICON REQUEST]: cordova && framework7

### ISSUE THREAD

**Issue by gustavoSutil** [devicons/devicon#1776]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

there are a important and an relevant frameworks

### Links and sources

# Framework7
## https://framework7.io/
# Apache Cordova
## https://cordova.apache.org/

Thanks!!

**Comment by dotarjun** [comment]
working on this

**Comment by gustavoSutil** [comment]
nice bro!

**Comment by lunatic-fox** [comment]
Hello @dotarjun! 👋🏼
💡 Just remember there are 2 different technologies here! So if you want to make both, please do [on separated pull requests](https://github.com/devicons/devicon/wiki/Overview-on-Submitting-Icons).
