### ISSUE TITLE
[ICON REQUEST]: AstroJS

### ISSUE THREAD

**Issue by szymonmasternak** [devicons/devicon#1778]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

AstroJS is a web framework that supports both static site generation (SSG) and server-side rendering (SSR). 

### Links and sources

Icon comes in two versions:

https://astro.build/assets/press/astro-icon-dark.svg

https://astro.build/assets/press/astro-icon-light.svg

Rest of AstroJS assets can be potentially obtained below:
https://astro.build/press/

**Comment by Gautam25Raj** [comment]
Working on it. 🙋‍♂️

**Comment by Gautam25Raj** [comment]
Astro icon are already present. [Link](https://github.com/devicons/devicon/tree/develop/icons/astro)

**Comment by akhilgkrishnan** [comment]
@Gautam25Raj Seem like it's in the repository, but it's not accessible via in code.

**Comment by Gautam25Raj** [comment]
> @Gautam25Raj Seem like it's in the repository, but it's not accessible via in code.

@akhilgkrishnan In devicon repository we have 2 main branches **master** and **develop**. They are used to track the development of a project and to release new versions of the project. 

The develop branch is the main branch for development. It is where new features are developed and tested before they are merged into the master branch. The master branch is the production branch. It is where the code that is currently being deployed to production is stored. 

So, currently AstroJS icons are available in **develop branch** and during next release it may get added to **master**.

**Comment by akhilgkrishnan** [comment]
@Gautam25Raj Yes, I forgot to check that on master branch :)
