### ISSUE TITLE
[ICON REQUEST]: Vite

### ISSUE THREAD

**Issue by Showcase-Joz** [devicons/devicon#1780]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Vite is a dev tool

### Links and sources

you might liken vite to a webpack replacement
[Vite website](https://vitejs.dev/)

**Comment by PantheraRed** [comment]
@Showcase-Joz https://github.com/devicons/devicon/tree/develop/icons/vite

**Comment by Gautam25Raj** [comment]
This vite logo seems to be old and outdated.  [New Logo](https://vitejs.dev/logo-with-shadow.png)

**Comment by Gautam25Raj** [comment]
@Panquesito7 @PantheraRed @Showcase-Joz  https://github.com/devicons/devicon/tree/develop/icons/vitejs
