### ISSUE TITLE
[ICON REQUEST]: Puppeteer Icon

### ISSUE THREAD

**Issue by Judge-Paul** [devicons/devicon#1795]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Puppeteer is a headless browser automation tool with a powerful API, enabling developers to automate browser tasks, interact with web pages, and extract data in a programmatic manner.

### Links and sources

Puppeteer Site
https://pptr.dev

SVG Logo I found
https://www.vectorlogo.zone/logos/pptrdev/pptrdev-official.svg

**Comment by Gautam25Raj** [comment]
Working on it. 🚀
