### ISSUE TITLE
Icon Request: Arch Linux

### ISSUE THREAD

**Issue by dlwilson88** [devicons/devicon#180]
Could you consider adding these:     

 1. [**ArchLinux-Dark**](https://sources.archlinux.org/other/artwork/archlinux-logo-dark-scalable.svg)
![archlinux-logo-dark-90dpi](https://user-images.githubusercontent.com/5242018/66821044-c62e9400-ef0f-11e9-8f11-f1ff8f62a37e.png)    
`https://sources.archlinux.org/other/artwork/archlinux-logo-dark-scalable.svg`     
    
 2. [**ArchLinux-Black**](https://sources.archlinux.org/other/artwork/archlinux-logo-black-scalable.svg)
![archlinux-logo-black-90dpi](https://user-images.githubusercontent.com/5242018/66821246-1dccff80-ef10-11e9-8017-4376338bc905.png)
`https://sources.archlinux.org/other/artwork/archlinux-logo-black-scalable.svg`

**Comment by noraj** [comment]
cf. https://archlinux.org/art/
