### ISSUE TITLE
[ICON REQUEST]: Vitest

### ISSUE THREAD

**Issue by Gautam25Raj** [devicons/devicon#1815]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

A Vite-native unit test framework.

### Links and sources

https://vitest.dev

**Comment by lunatic-fox** [comment]
### Original logo
<img width="256" src="https://vitest.dev/logo.svg">

**Comment by canaleal** [comment]
Closing as the Icon has been successfully merged into Develop.
