### ISSUE TITLE
[ICON REQUEST]: Microsoft 365

### ISSUE THREAD

**Issue by Gautam25Raj** [devicons/devicon#1817]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Collaborate for free with online versions of Microsoft Word, PowerPoint, Excel, and OneNote.

### Links and sources

https://www.office.com/

**Comment by canaleal** [comment]
Closed as the icon is out of scope for Devicons since it is a general purpose toolkit, that is not mainly used by developers. Take a look at: https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F#special-cases-see-this-discussion-for-more-details
