### ISSUE TITLE
[ICON REQUEST]: Alpine.js

### ISSUE THREAD

**Issue by Gautam25Raj** [devicons/devicon#1821]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

A lightweight, JavaScript framework.

### Links and sources

https://alpinejs.dev/alpine_long.svg

### Additional information

https://github.com/alpinejs/alpine

**Comment by canaleal** [comment]
Seems like this Icon is already in develop. Marking and closing as a duplicate. 
- https://github.com/devicons/devicon/issues/1198
- https://github.com/devicons/devicon/pull/1324
