### ISSUE TITLE
[ICON REQUEST]: Threads

### ISSUE THREAD

**Issue by Gautam25Raj** [devicons/devicon#1824]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Threads, an Instagram app

### Links and sources

https://www.threads.net

**Comment by PantheraRed** [comment]
@Gautam25Raj Instagram is a social media and hence does not count as a technology. Sames goes for threads.

**Comment by Gautam25Raj** [comment]
Yes, I have thought about that but then I saw twitter icon in develop and I guess threads is a replacement for twitter.

**Comment by Snailedlt** [comment]
@Gautam25Raj 
Please read this part of the wiki: https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F#special-cases-see-this-discussion-for-more-details
