### ISSUE TITLE
[OTHER] Icon's Url is not woking properly

### ISSUE THREAD

**Issue by Shobhit0209** [devicons/devicon#1829]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### What would you like to share?

I was using the icon's URL in my Readme and it is showing only title but nit the icon

**Comment by lunatic-fox** [comment]
Hello there! 
Please send an example of an URL that you're using. Like:
`https://cdn.jsdelivr.net/gh/devicons/devicon/icons/devicon/devicon-original.svg`

Because, this example above is working properly.
Wish for the best!

**Comment by Shobhit0209** [comment]
Hello there,
I am attaching the screenshot with the link
https://github.com/devicons/devicon/blob/master/icons/c/c-original.svg

[image: image.png]

**Comment by Snailedlt** [comment]
Use either the cdn that lunatic-fox linked, or the raw github link:
https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg
![](https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg)

**Comment by Shobhit0209** [comment]
Thanks for the tip!

**Comment by Panquesito7** [comment]
Has this issue been solved for you now, @Shobhit0209? 🙂

**Comment by Snailedlt** [comment]
Closing this issue since it seems like it's solved. 
Feel free to comment again here if it's still not solved, and I'll re-open it
