### ISSUE TITLE
Icon Request: Frontend Tools

### ISSUE THREAD

**Issue by SiimonStark** [devicons/devicon#183]
- [x] Redux
- [ ] Router
- [ ] Enzyme
- [x] Jest
- [x] Express

**Comment by tupaschoal** [comment]
Redux was added by #234 and Jest by #647 and both already appear on https://devicon.dev/, so a few more checkboxes can be ticked

**Comment by amacado** [comment]
@SiimonStark I will close this issue because as @tupaschoal pointed out we already have some of the mentioned icons. More important: This request does not follow our contribution guidelines on how to request icons. Feel free to create new icon requests with the icons which are not yet added! :)
