### ISSUE TITLE
[ICON REQUEST]: Vercel

### ISSUE THREAD

**Issue by markusweldon** [devicons/devicon#1831]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Vercel

### Links and sources

The Vercel icon is missing from the Devicon project, and it would be valuable to include it as Vercel is a popular deployment platform for web applications. 

Official Website: [https://vercel.com/](https://vercel.com/)

Adding the Vercel icon would enhance the completeness of the Devicon project and provide users with a comprehensive collection of icons for various technologies.

### Additional information

Please consider adding the Vercel icon to the Devicon project. Thank you for your attention to this request.

**Comment by PantheraRed** [comment]
> ### I have searched through the issues and didn't find my problem.
@markusweldon, are you sure you searched properly? 🙂

**Comment by markusweldon** [comment]
@PantheraRed, thanks 👍

I see [this](https://github.com/devicons/devicon/pull/1419) from 10 months ago committed to the dev branch.

Curious why such a large amount of new icons haven't been periodically merged into main as an official release. The last commit to main appears to be Mar 22, 2022.
