### ISSUE TITLE
[ICON REQUEST]: swiperjs

### ISSUE THREAD

**Issue by VasylHulpak** [devicons/devicon#1836]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Swiper is the most modern free and open source mobile touch slider with hardware accelerated transitions and amazing native behavior. Use it on websites, web apps, and mobile native/hybrid apps.

### Links and sources

Check out the [SwiperJs website](https://swiperjs.com/)

### Additional information

Right now the library is available for javascript, react, vue and webcomponents

**Comment by Gautam25Raj** [comment]
Working on it 🚀
