### ISSUE TITLE
Icon Request: BASIC

### ISSUE THREAD

**Issue by ioquatix** [devicons/devicon#184]
Please add an icon for BASIC, e.g.

QuickBasic, GW Basic, Visual Basic, etc. I am happy to try and contribute something. Let me know what you think.

**Comment by BenSouchet** [comment]
I don't think there is an official logo for BASIC or Visual Basic so it's no possible for me to do something .
VBScript as a logo:
<img width="287" alt="Screenshot 2022-01-15 at 13 43 40" src="https://user-images.githubusercontent.com/17025808/149622134-cb7ff939-dc7e-44db-b4d8-6aac3e58801c.png">

I can add VBScript but don't know if it's really usefull, let me know :)

**Comment by Thomas-Boi** [comment]
Please refer to #910 since it contains more details.
