### ISSUE TITLE
[ICON REQUEST]: Cypress

### ISSUE THREAD

**Issue by xavierkoo** [devicons/devicon#1842]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Cypress is a front end testing tool for web applications.

### Links and sources

https://www.cypress.io/

**Comment by canaleal** [comment]
I'm surprised this one hasn't been added yet. I can get a PR up tomorrow afternoon, but iIn case someone else want's to handle this ticket, here are the Cypress Media logos in SVG format:

https://www.cypress.io/press-kit/

**Comment by Snailedlt** [comment]
Duplicate of #223
