### ISSUE TITLE
[ICON REQUEST]: Deta Space

### ISSUE THREAD

**Issue by lemonyte** [devicons/devicon#1845]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Deta Space is a serverless cloud hosting platform focused on ease of development and quick deployment/scaling. Even though this is a hosting platform I feel it should be added since Vercel has been added.

### Links and sources

https://deta.space
https://github.com/deta
https://deta.space/landing-page/assets/logo.20539aa2.svg
https://github.com/deta/space-docs/blob/main/.github/deta.svg

### Additional information

I can create the PR if the icon is accepted.

**Comment by Snailedlt** [comment]
Sounds good, feel free to create a PR :)
