### ISSUE TITLE
Icon Request: Perl

### ISSUE THREAD

**Issue by tehmoth** [devicons/devicon#185]
* Perl
* perl
* Raku

**Comment by tobyink** [comment]
Add my vote to this.

Here's some SVG sources:

https://github.com/dnmfarrell/Perl-Icons/tree/master/Icons

I'd suggest using the onion or raptor for Perl, as the camel is a trademark of O'Reilly Media Inc. And use Camelia for Raku (the programming language formerly known as Perl 6).

**Comment by jusuchin85** [comment]
@Thomas-Boi can be closed? 😄
