### ISSUE TITLE
[ICON REQUEST]: Notion

### ISSUE THREAD

**Issue by robbyph** [devicons/devicon#1851]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Notion is a commonly used PKM software

### Links and sources

https://www.notion.so/product

https://commons.wikimedia.org/wiki/File:Notion_app_logo.png

**Comment by ShreyasSaunshi** [comment]
Hi, can you assign me this issue?

**Comment by Snailedlt** [comment]
@ShreyasSaunshi We don't really assign issues here other than to very active contributors... but please feel free to work on it, and let us know if you need any help :)

**Comment by Yashh56** [comment]
I would like to Contribute
