### ISSUE TITLE
[ICON REQUEST]: Gitpod

### ISSUE THREAD

**Issue by IMGROOT2** [devicons/devicon#1858]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Gitpod

### Links and sources

https://www.gitpod.io/ is a ready-to-code cloud IDE.

**Comment by weh** [comment]
This image is in [develop](https://github.com/devicons/devicon/tree/develop) already
see https://github.com/devicons/devicon/pull/1372 and https://github.com/devicons/devicon/issues/1371
