### ISSUE TITLE
[ICON REQUEST]: <C#>

### ISSUE THREAD

**Issue by mdestafadilah** [devicons/devicon#1863]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

C# is like other language but it's over with Microsoft and Community.

### Links and sources

https://learn.microsoft.com/en-us/dotnet/csharp/

### Additional information

I know, it's .NET but it's too general, not spesific to languange.

**Comment by canaleal** [comment]
Hey @mdestafadilah , C# already exists in the Master Branch https://github.com/devicons/devicon/tree/master/icons/csharp and was added in this very old commit https://github.com/devicons/devicon/commit/e1e71358efd844876dfc3217aa6429957ad92bc8

**Comment by mdestafadilah** [comment]
oh sorry my mistake, thanks, i will close.
