### ISSUE TITLE
[ICON REQUEST]: <icon name>

### ISSUE THREAD

**Issue by pabitra0011** [devicons/devicon#1887]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

SQL Server is a specific relational database management system (RDBMS) developed and owned by Microsoft.

### Links and sources

Official site - https://www.microsoft.com/en-in/sql-server/sql-server-downloads

**Comment by Snailedlt** [comment]
@pabitra0011 What icon exactly do you want added? You mention both SQL and SQL server here, but it's difficult to tell which icon you want since your issue doesn't have a proper title.

**Comment by pabitra0011** [comment]
I want to add Sql Server database icon.

**Comment by Snailedlt** [comment]
I see. That's already added though. See [microsoftsqlserver](https://github.com/devicons/devicon/tree/master/icons/microsoftsqlserver)
