### ISSUE TITLE
[ICON REQUEST]: <F#>

### ISSUE THREAD

**Issue by borkarSahil** [devicons/devicon#1892]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

F# is an open-source, cross-platform programming language that makes it easy to write succinct, performant, robust, and practical code. 

### Links and sources

https://fsharp.org/

**Comment by canaleal** [comment]
Hey @borkarSahil , F# already exists in the [master branch](https://github.com/devicons/devicon/tree/master/icons/fsharp).

It was merged in this [PR](https://github.com/devicons/devicon/pull/495).
