### ISSUE TITLE
[ICON REQUEST]: <PureScript>

### ISSUE THREAD

**Issue by borkarSahil** [devicons/devicon#1893]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

PureScript is a small, strongly, statically typed programming language .

### Links and sources

https://www.purescript.org/

**Comment by canaleal** [comment]
Hey @borkarSahil , Pure Script does not exist in master but it does exist in the [develop](https://github.com/devicons/devicon/tree/develop/icons/purescript) branch.
