### ISSUE TITLE
[ICON REQUEST]: <Apache Groovy>

### ISSUE THREAD

**Issue by borkarSahil** [devicons/devicon#1894]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Apache Groovy is a Java-syntax-compatible object-oriented programming language

### Links and sources

https://groovy-lang.org/

**Comment by weh** [comment]
This icon already exists in the published version 2.15.1 (?)
https://github.com/devicons/devicon/pull/237
