### ISSUE TITLE
Icon Request: QT

### ISSUE THREAD

**Issue by kevin-ruby** [devicons/devicon#190]
a Qt logo would be awesome. Thanks!

**Comment by tupaschoal** [comment]
@Thomas-Boi not sure why merging #691 didn't close it (maybe because it didn't go into `master` yet?), so I'm commenting here for verification.

**Comment by Thomas-Boi** [comment]
This is something we are looking into as well. There are many issues that has PRs that were merged into `master` but were never closed. Thank you for letting us know this is still happening 👍

**Comment by Panquesito7** [comment]
I'll close this issue for now. This is fixed, so I see no reason to keep it open.
