### ISSUE TITLE
[ICON REQUEST]: <ROS>

### ISSUE THREAD

**Issue by gabri00** [devicons/devicon#1903]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

The Robot Operating System (ROS) is a set of software libraries and tools that help you build robot applications.

### Links and sources

[ros.org](https://www.ros.org/)

**Comment by canaleal** [comment]
Awesome suggestion @gabri00 !

For those looking to add this logo, you might want to check out the word-mark SVG on [Wikipedia](https://en.wikipedia.org/wiki/Robot_Operating_System#/media/File:Ros_logo.svg). It's already in the ROS `#22314E` fill color, just like the one in their [brand guide](https://www.ros.org/imgs/ROSBrandGuide.pdf).

You can find all the logos in the ROS Press Kit and Logos at the bottom of their [brand page](https://www.ros.org/blog/media/). I recommend using the 9 dots for the original SVG. Both SVGs are simple enough to used for Plain.

**Comment by Yashh56** [comment]
#1100
