### ISSUE TITLE
[ICON REQUEST]: Plotly

### ISSUE THREAD

**Issue by Grey-Hat-07** [devicons/devicon#1904]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Plotly Open Source Graphing Libraries

### Links and sources

About the icon
Plotly graphing library makes interactive, publication-quality graphs. Examples of how to make line plots, scatter plots, area charts, bar charts, error bars, box plots, histograms, heatmaps, subplots, multiple-axes, polar charts, and bubble charts.

Links and sources
Website: https://plotly.com/graphing-libraries/

**Comment by weh** [comment]
This icon exists in develop branch 
see PRs #1134, #1589
