### ISSUE TITLE
Icon Request: Nosql, firebase, redux

### ISSUE THREAD

**Issue by JagNanda** [devicons/devicon#191]
Hi, it would much appreciated if any of these icons could be created.

**Comment by debdutgoswami** [comment]
Refer to PR #143 and #170 :)

**Comment by tupaschoal** [comment]
Redux was added by #234 and firebase by #461 and both are already live on devicons

**Comment by amacado** [comment]
Thanks for the hint @tupaschoal! I'm closing this issue since two of the icons are already added. @JagNanda feel free to create a new issue requesting 'nosql' following our guidelines.
