### ISSUE TITLE
[ICON REQUEST]: Mithril.js

### ISSUE THREAD

**Issue by canaleal** [devicons/devicon#1937]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Mithril.js is a lightweight, modern client-side framework for building single-page applications (SPAs). It offers a virtual DOM for efficient rendering and a component-based architecture for modular UI construction. Additionally, Mithril provides built-in routing and XHR utilities, streamlining SPA development.

## Links
- [Mithril Website](https://mithril.js.org/)
- [Mithril Github](https://github.com/MithrilJS/mithril.js)

## Brand Logos
- [Main Logo](https://github.com/MithrilJS/mithril.js/blob/next/assets/logo.svg)

### Additional information

There does not exist any Mithril wordmark logo.
The only logos that can be created from the original Mithril SVG include (original, plain, and line). 

I recommend using an alias for original and plain instead of having to create another SVG file.

**Comment by Yashh56** [comment]
I would like to contribute
