### ISSUE TITLE
Request for Elm & Reason

### ISSUE THREAD

**Issue by Djuppi** [devicons/devicon#194]
Thank you so much for these amazing icons! Noce work :)

If i could i would request icons for Elm and Reason :)

**Comment by admarko** [comment]
+1

**Comment by tupaschoal** [comment]
Seems like elm is already added

**Comment by amacado** [comment]
Yep, elm is already added. @Djuppi when 'Reason' is still relevant feel free to create a new icon request which follows our guidelines :)
