### ISSUE TITLE
[ICON REQUEST]: <Prolog>

### ISSUE THREAD

**Issue by Vitoria-Maria0912** [devicons/devicon#1963]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Icon of the logic language Prolog.

### Links and sources

https://www.swi-prolog.org/

**Comment by canaleal** [comment]
Hey @Vitoria-Maria0912, Prolog currently exists in the develop branch of Devicon here:
- https://github.com/devicons/devicon/blob/develop/icons/prolog/prolog-original-wordmark.svg

Also, a fresh new release is on the way. You'll spot prolog on the master branch and the devicon website real soon.

**Comment by canaleal** [comment]
Am marking this as duplicate and closing as prolog already exists.
