### ISSUE TITLE
[ICON REQUEST]: <Postman>

### ISSUE THREAD

**Issue by lerry68** [devicons/devicon#1978]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

please add "Postman" icon

### Links and sources

https://www.postman.com/

**Comment by canaleal** [comment]
Hey @lerry68, Postman currently exists in the develop branch. 
- https://github.com/devicons/devicon/tree/develop/icons/postman

**Comment by canaleal** [comment]
Am marking this as duplicate and closing as Icon already exists.
