### ISSUE TITLE
[ICON REQUEST]: AntD Icon

### ISSUE THREAD

**Issue by YaroslavWeb** [devicons/devicon#1989]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Antd - UI library (like Material UI)

### Links and sources

https://ant.design/

**Comment by canaleal** [comment]
Hey @YaroslavWeb, Ant Design is not in the master branch, but it does exist in develop. 

- https://github.com/devicons/devicon/blob/develop/icons/antdesign/antdesign-original.svg

**Comment by canaleal** [comment]
Closing and marking as duplicate as Icon already exists.
