### ISSUE TITLE
Icon request: Adobe CC

### ISSUE THREAD

**Issue by ghost** [devicons/devicon#199]
Hi: 

I have a request to add the adobe icon. 
Something like this: https://icons8.com/icon/62149/adobe-creative-cloud 
https://www.adobe.com/legal/permissions/icons-web-logos.html

**Comment by Thomas-Boi** [comment]
I'd say this is too generic. Please check our [guide](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F) and let us know your thoughts
