### ISSUE TITLE
[ICON REQUEST]: Airflow

### ISSUE THREAD

**Issue by katkaypettitt** [devicons/devicon#2004]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Commonly used open source data engineering platform

### Links and sources

Official website: 
https://airflow.apache.org/

GitHub:
https://github.com/apache/airflow

Images:
https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+logos

**Comment by weh** [comment]
Apache Airflow is already in development
see: #1412 and #1163
