### ISSUE TITLE
[ICON REQUEST]: Supabase

### ISSUE THREAD

**Issue by justinherrera** [devicons/devicon#2016]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

It is an open source firebase alternative and it is becoming popular

### Links and sources

platform link: https://supabase.com/
icon link: https://github.com/supabase/supabase/blob/ee18b5ac1f0ade98be447a595335a04c02108c2e/apps/studio/public/supabase-logo.svg#L4

**Comment by canaleal** [comment]
Hey @justinherrera, welcome to Devicon and thankyou for the awesome icon suggestion. 
While the Supabase Icon does not exist in the master branch, it does exist in the [Develop Branch](https://github.com/devicons/devicon/blob/develop/icons/supabase/supabase-original.svg). 
Until a new release is made I recommend using the SVG from develop.

**Comment by justinherrera** [comment]
When would be the new release?

**Comment by canaleal** [comment]
Hey @justinherrera, we're currently in the process of creating the next release build. There's a few issues with some of the older icons that we need to get rid of; until these issues are resolved, the release will need to be delayed. 

I don't want to give a set time, but if all goes well, hopefully, expect the next release quite soon.
