### ISSUE TITLE
Icon request: GraphQL

### ISSUE THREAD

**Issue by maugeya** [devicons/devicon#209]
> ### About the icon
> GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data.
> 
> ### Links
> https://graphql.org/img/logo.svg
> 
> ### Preview
> <img alt="" width="30%" src="https://camo.githubusercontent.com/4453190c8ab634df9abe355ec7cb0a2f5704c257b3535fa028c1dc3c51d441cd/68747470733a2f2f6772617068716c2e6f72672f696d672f6c6f676f2e737667">

Description provided by @aravindvnair99 https://github.com/devicons/devicon/issues/490

**Comment by tupaschoal** [comment]
This was added by #530 and is already live, so it can probably be closed.

**Comment by amacado** [comment]
Thanks for the hint @tupaschoal!
