### ISSUE TITLE
[FEATURE REQUEST]: Make an icon not found page for when the user searches and it is not available

### ISSUE THREAD

**Issue by Bashamega** [devicons/devicon#2137]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### Description

Hello:)

My idea is to make a 404 not found page for the user when the search term is invalid or there is not icons available.

### Context

It can benefit the user by telling him there is no icons available, and that he needs to change his search term. Because, the user think there is something wrong with his network or the page is still loading

### Possible Solution

Create a component telling the user that it is not found and making it visible when the icon is not found.

### Additional information

If this issue is approved I would love to work on it but please guide me to the correct repo because this one is only icons and fonts.
Thank you

**Comment by canaleal** [comment]
Hey @Bashamega, Love the idea – thanks for bringing it up!

We'll likely move over to using [this website](https://risbi0.github.io/devicon-new-ui/) in the future. It's not yet updated with the latest icons yest, but should be soon. When that happens, the `No Icons Found` warning should be added. 

![image](https://github.com/devicons/devicon/assets/49886351/650344d8-c7f1-4a30-88f3-498ea5c76467)

**Comment by Bashamega** [comment]
> Hey @Bashamega, Love the idea – thanks for bringing it up!
> 
> We'll likely move over to using [this website](https://risbi0.github.io/devicon-new-ui/) in the future. It's not yet updated with the latest icons yest, but should be soon. When that happens, the `No Icons Found` warning should be added.
> 
> ![image](https://private-user-images.githubusercontent.com/49886351/303322932-650344d8-c7f1-4a30-88f3-498ea5c76467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDE1MjAsIm5iZiI6MTcwNzQwMTIyMCwicGF0aCI6Ii80OTg4NjM1MS8zMDMzMjI5MzItNjUwMzQ0ZDgtYzdmMS00YTMwLTg4ZjMtNDk4ZWE1Yzc2NDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE0MDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZDkxZWUxMTczNmU2M2ZiZDlhZmM0YWU1NjM3NzIxNmQxMWI4MjNiN2E5NWU3NWU1MWNhYmY4MGJlZjNkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c1RPPkguTh7I_FAVv_5OsNIoI47840qmtgO8dQgxaSQ)

Your welcome

Also it would be nice if there is and add icon button which will take the user to the icon request issue template
