### ISSUE TITLE
[ICON REQUEST]: Asana

### ISSUE THREAD

**Issue by JustIceQAQ** [devicons/devicon#2144]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

A company-wide goals, manage strategic plans, and get work done on a single platform.

### Links and sources

https://asana.com/

#### iconname-version-name
<img width="100px" src="previewable_link_to_icon" ></img>
link_to_icon

**Comment by canaleal** [comment]
Hey @JustIceQAQ, because Asana is a project management tool like JIRA it does not meet the [criteria](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F) for icons that can be accepted into Devicon.
