### ISSUE TITLE
[ICON REQUEST]: Vite.js

### ISSUE THREAD

**Issue by aldanielago** [devicons/devicon#2159]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Because it's a really good tool. 

### Links and sources

https://vitejs.dev/

#### vitejs-4-vite iconname-version-name
<img width="100px" src="https://seeklogo.com/images/V/vite-logo-BFD4283991-seeklogo.com.png" ></img>

**Comment by canaleal** [comment]
Hey @aldanielago, Vite exists in the [master branch](https://github.com/devicons/devicon/blob/master/icons/vitejs/vitejs-original.svg) already.
