### ISSUE TITLE
[ICON REQUEST]: Tableau

### ISSUE THREAD

**Issue by rahul-bharadwaaj** [devicons/devicon#2169]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

To show case my skills

### Links and sources

https://www.google.com/url?sa=i&url=https%3A%2F%2Fanalyticstraininghub.com%2Ftableau-course%2Ficon-tableau%2F&psig=AOvVaw3hvq1-hxQtViLLtOF0I44q&ust=1711071935270000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKja3-idhIUDFQAAAAAdAAAAABAE

#### iconname-version-name
<img width="100px" src="previewable_link_to_icon" ></img>
link_to_icon

**Comment by canaleal** [comment]
Hey @rahul-bharadwaaj, thankyou for the icon suggestion but the tableau icon has been rejected in a previous [icon request](https://github.com/devicons/devicon/pull/1811) as it did not meet the requirements outlined in the [wiki](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F).
