### ISSUE TITLE
[ICON REQUEST]: Telegram

### ISSUE THREAD

**Issue by Panagiotis-Sklidas** [devicons/devicon#2175]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Many developers use  Telegram as a way to communicate with their client

### Links and sources

From the official Telegram site
https://telegram.org/file/464001088/1/bI7AJLo7oX4.287931.zip/374fe3b0a59dc60005

### Icon links and previews

![Logo](https://github.com/devicons/devicon/assets/45635393/b8c7f63b-fab8-48ed-ab10-a0de397f690c)

**Comment by canaleal** [comment]
Hey @Panagiotis-Sklidas, Telegram itself is not specifically targeted towards software development; it's a general-purpose messaging platform. It conflicts with the type of icons we [accept](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F).
