### ISSUE TITLE
[ICON REQUEST]: NetBeans

### ISSUE THREAD

**Issue by MiguelAntonioRS** [devicons/devicon#2198]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Netbeans is an ide for programming in Java and is the best for beginners

### Links and sources

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Apache_NetBeans_Logo.svg/800px-Apache_NetBeans_Logo.svg.png" title="NetBeans" alt="NetBeans" width="40" height="40">

#### iconname-version-name
<img width="100px" src="previewable_link_to_icon" ></img>
link_to_icon

**Comment by canaleal** [comment]
Hey @MiguelAntonioRS, this issue is a duplicate. There's fairly old Issue #930 still in wait. 
Regardless, I'll get a PR up soon.
