### ISSUE TITLE
[ICON REQUEST]: SQL SERVER

### ISSUE THREAD

**Issue by MiguelAntonioRS** [devicons/devicon#2199]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

one of the most popular database managers

### Links and sources

<img src="https://banner2.cleanpng.com/20180614/sg/kisspng-microsoft-sql-server-sql-server-management-studio-transactional-analysis-5b2207401c5992.0038138215289567361161.jpg" title="SQL" alt="SQL" height="40" width="40">  

### Icon links and previews

<img src="https://banner2.cleanpng.com/20180614/sg/kisspng-microsoft-sql-server-sql-server-management-studio-transactional-analysis-5b2207401c5992.0038138215289567361161.jpg" title="SQL SERVER" alt="SQL SERVER" height="40" width="40">

**Comment by canaleal** [comment]
Closing as SQL Server already [exists](https://github.com/devicons/devicon/tree/master/icons/microsoftsqlserver) in the Devicon main branch.

**Comment by MiguelAntonioRS** [comment]
Sorry i don't see

**Comment by canaleal** [comment]
> Sorry i don't see

No worries.
