### ISSUE TITLE
[ICON REQUEST]: Spring Boot

### ISSUE THREAD

**Issue by MiguelAntonioRS** [devicons/devicon#2205]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Spring Boot, a very popular framework within the Java community and widely used

### Links and sources

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyn8QqjBWVi7oFXCPk_nBUatVuwVN6hyv1akvbqa7lw&s" title="springboot" alt="springboot" height="40" width="40">

#### iconname-version-name
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcyn8QqjBWVi7oFXCPk_nBUatVuwVN6hyv1akvbqa7lw&s" title="springboot" alt="springboot" height="40" width="40">

### Additional information

Java Spring Boot (Spring Boot) is a tool that makes developing web applications and microservices with the Spring Framework faster and easier through three main functionalities: Automatic configuration. A stubborn approach to setup.

**Comment by lfb0801** [comment]
Yes please

**Comment by MiguelAntonioRS** [comment]
Enjoy it
