### ISSUE TITLE
[ICON REQUEST]: Tableau

### ISSUE THREAD

**Issue by vishaldhatrika** [devicons/devicon#2241]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Data visualization platform

### Links and sources

https://tableau.com/

#### tableau-from-slack
<img width="100px" src="https://avatars.slack-edge.com/2021-07-28/2335856319233_b1f6442290972bfa5498_512.png" ></img>
[https://avatars.slack-edge.com/2021-07-28/2335856319233_b1f6442290972bfa5498_512.png](https://avatars.slack-edge.com/2021-07-28/2335856319233_b1f6442290972bfa5498_512.png)

**Comment by canaleal** [comment]
Hey @vishaldhatrika, great suggestion! However, there is already a slightly older [issue](https://github.com/devicons/devicon/issues/1030) for Tableau.

**Comment by vishaldhatrika** [comment]
duplicate of [https://github.com/devicons/devicon/issues/1030](https://github.com/devicons/devicon/issues/1030)
