### ISSUE TITLE
[ICON REQUEST]: Remix

### ISSUE THREAD

**Issue by willin** [devicons/devicon#2254]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### About the icon

Remix framework

### Links and sources

https://github.com/remix-run
https://remix.run

#### iconname-version-name
<img width="100px" src="https://avatars.githubusercontent.com/u/64235328?s=200&v=4" ></img>

<https://avatars.githubusercontent.com/u/64235328?s=200&v=4>

**Comment by canaleal** [comment]
Hey @willin, Remix already exists in the develop branch. 
https://github.com/devicons/devicon/tree/develop/icons/remix

![image](https://github.com/user-attachments/assets/bc22412f-814c-403a-b589-d64304a4983a)
