### ISSUE TITLE
[OTHER]: SVG standards misleading?

### ISSUE THREAD

**Issue by Finii** [devicons/devicon#2265]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### What would you like to share?

The Wiki lays out rules how icons have to be designed:

https://github.com/devicons/devicon/wiki/SVG-Standards

But the example is misleading or at least waters the requirements down a bit.

![image](https://github.com/user-attachments/assets/8e9ed133-113e-4c08-a83e-bcf35fc4f3bc)

While it says there must be no padding the example image has some padding around the outermost path and the viewbox.

Suggestion: Fix the example image to actually have no padding :-D

**Comment by canaleal** [comment]
Thanks for pointing out the error @Finii 
I will fix the issue.

**Comment by canaleal** [comment]
Issue resolved. Thankyou.
