### ISSUE TITLE
Feature request: download the logo in your plain style

### ISSUE THREAD

**Issue by RoRoche** [devicons/devicon#228]
The plain style used in result list is very nice.

cf.

```css
cbp-ig-icon devicon-cucumber-plain
```

I would like to download it directly?

What's about using an input to let user define the base color (here #60be86), to match his design system? Would very cool!

**Comment by amacado** [comment]
Since @RoRoche did not respond my comment I think this issue is resolved and can be closed. If not feel free to reopen it.
