### ISSUE TITLE
[OTHER]: Update Vite icon 

### ISSUE THREAD

**Issue by sabeerbikba** [devicons/devicon#2300]
### I have searched through the issues and didn't find my problem.

- [X] Confirm

### What would you like to share?

The current Vite icon in the Devicon repository is outdated and doesn’t match the latest design standards of the Vite logo. The icon needs to be updated to align with the latest Vite branding guidelines. A more up-to-date icon would improve recognition and consistency across developer tools and projects using Devicon.

### Additional information

Here’s an image of the current Vite icon for reference, along with the latest Vite icon design for comparison. 

![image](https://github.com/user-attachments/assets/ff57a127-7cd4-464b-9f2a-c653cc75c1d0)

![image](https://github.com/user-attachments/assets/c8edc7eb-6d53-4847-9026-b78bf30916ae)

https://vite.dev/logo.svg

 Updating the icon with the latest version will enhance the visual alignment with other modernized icons in the Devicon repository. Let me know if any specific format or resolution is preferred.

**Comment by canaleal** [comment]
Looks like there's 2 versions. 

Vite and ViteJS in devicons. 

https://devicon-ui.vercel.app/?branch=develop&icon=vitejs
