### ISSUE TITLE
Setup SVG fixer 

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#247]
**PROBLEM**: If your svg containts strokes or any tags besides a single path e.g polygon rect line etc, you will get errors when trying to convert them into fonts.

The project [oslllo/svg-fixer](https://github.com/oslllo/svg-fixer) is able to auto-correct svg's and convert `strokes` to `fill`.

**Comment by Thomas-Boi** [comment]
Hey @amacado ,

Do you still need any help with this? I can make another script that use the above repo to fix icons if need ("bot:fix" maybe)?

**Comment by amacado** [comment]
feel free! 👍🏻
