### ISSUE TITLE
Icon request: Nim

### ISSUE THREAD

**Issue by juancarlospaco** [devicons/devicon#249]
- [ ] Nim https://nim-lang.org

#### Useful 
- https://github.com/nim-lang/assets/tree/master/Art
- More info https://en.wikipedia.org/wiki/Nim_(programming_language)

**Comment by amacado** [comment]
@juancarlospaco I've never heard of nim/nimble, can you say if those are two separated projects? Because if that's the case I would like you to create two issues, one for each.

**Comment by Snailedlt** [comment]
This looks awesome!
https://www.youtube.com/watch?v=WHyOHQ_GkNo
