### ISSUE TITLE
Icon Request: Gatsby.js

### ISSUE THREAD

**Issue by ganeshsundaram39** [devicons/devicon#251]
URL: https://www.gatsbyjs.org/

**Comment by amacado** [comment]
Icon can be downloaded here https://www.gatsbyjs.org/guidelines/logo/

**Comment by ddmasterdon** [comment]
Try this link for direct download

https://raw.githubusercontent.com/github/explore/e94815998e4e0713912fed477a1f346ec04c3da2/topics/gatsby/gatsby.png

**Comment by amacado** [comment]
Closing this issue in favor of #308 (this issue containing more information in the issue description)
