### ISSUE TITLE
Icon request: ROS

### ISSUE THREAD

**Issue by JihunDev** [devicons/devicon#256]
Official resources for icon and color:
Brand guidelines : https://www.ros.org/press-kit/
color : the color value for print is 533C and the online hex color is #22314E

**Comment by amacado** [comment]
@JihunDev I like how you requested 👍🏻

**Comment by Berkmann18** [comment]
@amacado That's how SimpleIcons does it (well at least until recently).

**Comment by JihunDev** [comment]
@Berkmann18 Right, I wrote in the form of a simpleicons.

**Comment by joefscholtz** [comment]
Hey! I'm trying to patch a font using this icon, was it already added in the `fonts/devicon.ttf` file in the dev branch? If so, how could I find the unicode character? I tried installing the font and search for the character with `xfd -fa devicon` in the terminal for example, but with no success.

Thanks in advance!
