### ISSUE TITLE
Icon request: Dart

### ISSUE THREAD

**Issue by IoanaAlexandru** [devicons/devicon#267]
With the popularization of Flutter, Dart is becoming a rather used programming language.

Example brand svg here: https://dart.dev/assets/shared/dart-logo-for-shares.png?2

**Comment by amacado** [comment]
Hello @IoanaAlexandru, thanks for pointing our Dart! If you got the time feel free to take a look at [CONTRIBUTING.md#submitting-icon](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#submitting-icon) and add this icon by yourself! :)
