### ISSUE TITLE
Icon request: mongoose

### ISSUE THREAD

**Issue by stevendo** [devicons/devicon#269]
![mongoose-icon](https://user-images.githubusercontent.com/4326021/91245781-4e7ae980-e71c-11ea-9e8c-fa3b003e0a56.png)
Requesting an icon for mongoose please!
https://mongoosejs.com/docs/

**Comment by amacado** [comment]
Hello @stevendo, thanks for pointing our mongoose! If you got the time feel consider to take a look at [CONTRIBUTING.md#submitting-icon](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#submitting-icon) and add this icon by yourself! :)
