### ISSUE TITLE
Question on what to do to css files in the new build task.

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#286]
Hey @amacado,

I would like to ask for your inputs on the generation of the css files and the branch workflow trigger. 

*Quick summary*

I am currently upgrading the current `devicon.json` to a newer version that would include the `aliases` and `color` attribute (see this [pr](https://github.com/devicons/devicon/pull/268)). Beside the changes to this file, I'm also working on a new `gulp task` to generate css files (`devicon-alias.css` and `devicon-color.css`) based on the new `devicon.json`.

As you can see in the pr, we talked about removing the alias and the color css file completely. However, we later talked about how we don't want to break compatibility while we upgrade the repo. So as a confirmation, should I delete these css files after I generate the `devicon.min.css`? I'm working on the `gulp tasks` right now and I can pipe the outputs into a file. It's also faster appending to existing file as well but we would have a bunch of css files sitting around. Let me know what you think.

**Comment by amacado** [comment]
In my opinion we should remove the `devicon-colors.css` and `devicon-alias.css` after the next generation of our build process is ready. Maybe you can introduce a option within the gulp task to not remove the css files upon building but the default setting should include the removal.

**Comment by Thomas-Boi** [comment]
Ok, that sounds good to me
