### ISSUE TITLE
npm release

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#288]
We have an old published [npm package of devicon ](https://www.npmjs.com/package/devicon). I would suggest to implement npm release as enhancement to our [automated release process](https://github.com/devicons/devicon/issues/287).  I already got in contact with @konpa and I will see how we can migrate the existing npm release of devicon.

**Comment by Thomas-Boi** [comment]
I can lend a hand with making a script as well. There are a lot of [actions](https://github.com/marketplace?type=actions&query=npm) on the Marketplace that we can use.

**Comment by amacado** [comment]
sure, go ahead! 👍🏻

**Comment by amacado** [comment]
I will start working on this! :)
