### ISSUE TITLE
migrate gh-pages to master branch

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#289]
I would like to discuss what you guys think of migrating the `gh-pages` branch in the `master` branch and keep the public page (which is now available at [devicon.dev](https://devicon.dev/) btw.) in sync with the latest development. Currently each time a new master is released we need to update the gh-pages branch accordingly. I think it would improve our workflow to merge those branches and publish the github-page in /docs (or smiliar folder).

What is your opinion?

**Comment by Thomas-Boi** [comment]
I can start working on a new GitHub workflow for updating the `gh-pages`/`master` after we finish with the build script. I can also help with migrating the `gh-pages` over to the `master` branch.

**Comment by Thomas-Boi** [comment]
Hi all, 

I'm looking into migrating the gh-pages over to the main branch.
Here is what I'm planning to do:
-Bring main up to date to develop
-Add a /docs folder into the main branch which contains all the files that are currently in gh-pages. Remove the devicons.git reference 
-Change the url for the devicon.json in the assests/js/script.js so it points to the devicon.json in the main branch

Then we edit the GitHub Pages settings so it use the /docs
Whenever we have a new release, we would merge develop into main and the /docs folder would read from the new devicon.json
