### ISSUE TITLE
Icon request: Jupyter

### ISSUE THREAD

**Issue by eevleevs** [devicons/devicon#295]
### About the icon
Jupyter is a popular tool to write python notebooks, with its own file format based on JSON.
In an app offering to download both plain Python code and notebook, I would use the two relative icons to choose.
### Links
https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png
### Preview

**Comment by Panquesito7** [comment]
I think this issue can be closed. https://github.com/devicons/devicon/pull/501
