### ISSUE TITLE
Icon request: Jenkins

### ISSUE THREAD

**Issue by tariq86** [devicons/devicon#306]
### About the icon

[Jenkins](https://www.jenkins.io/) is a very popular open source automation server, commonly used for CI/CD.

### Links

The main Jenkins website has a whole artwork section [here](https://www.jenkins.io/artwork/), which has a link to a SVG of the official logo: https://www.jenkins.io/images/logos/jenkins/jenkins.svg

### Preview

![Jenkins](https://www.jenkins.io/images/logos/jenkins/jenkins.svg)

**Comment by tariq86** [comment]
It looks like this icon was requested a while ago in #121 along with a few other logos; I opened this to request/track Jenkins only.

**Comment by amacado** [comment]
@tariq86 thanks for creating a new issue. It's correct to create a new one, since we want to have each icon request in a separated issue 👍🏻
