### ISSUE TITLE
Icon request: Gatsby

### ISSUE THREAD

**Issue by edwintrumpet** [devicons/devicon#308]
### About the icon
Gatsby is a very popular frontend framework that uses ReactJS to build powerful SPAs
### Links
- Oficial website of Gatsby https://www.gatsbyjs.com/
- Guidelines and logo https://www.gatsbyjs.com/guidelines/logo/

### Preview
![Gatsby](https://dominicode.com/wp-content/uploads/gatsbyjs_introduccion.jpg)

**Comment by amacado** [comment]
Gatsby was requested several times before, I use this issue to clean up so we only have one active issue regarding Gatsby! :)
