### ISSUE TITLE
Icon request: Tailwind CSS

### ISSUE THREAD

**Issue by alxayeed** [devicons/devicon#319]
### About the icon
Tailwind CSS is a utility first, highly customizable, low-level CSS framework that gives you all of the building blocks you need to build bespoke designs without any annoying opinionated styles you have to fight to override
### Links
https://tailwindcss.com/
https://www.vectorlogo.zone/util/preview.html?image=/logos/tailwindcss/tailwindcss-icon.svg
### Preview
![tailwind](https://user-images.githubusercontent.com/35950055/95715570-e6f90900-0c8b-11eb-9a1e-ee2dd6565110.png)

**Comment by tupaschoal** [comment]
This icon is already seen on https://devicon.dev/. so this can probably be closed.

**Comment by amacado** [comment]
Thanks for the hint @tupaschoal!
