### ISSUE TITLE
New Build Workflow Trigger

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#329]
Hey everyone,

Recently, we have introduced a new workflow to the repo. Instead of building the icons, this script will only take a screenshot of the icons after they are uploaded to icomoon.io. This "peek" script will help us decide whether to merge a PR into the repo.

However, since we now have this script, the current build script's trigger is weird. If we continue using the current build script, the PR that we are using it on might not have the icons that we merged from another PR. 

To solve this, I am asking everyone for thoughts on how to run the build script. Some possible solutions that I thought of are:
* Trigger the build script manually on the GitHub website. This gives us more flexibility for when to build the icons. However, it needs some extra work (very minimal though).
* Trigger using a cron expression/schedule. This would run the script at a certain time interval, which means that we don't have to worry about it in the future. However, it is not very flexible.

What do you guys think?

**Comment by amacado** [comment]
I think it's ok to trigger the build script manually since it's not a big deal. As long it's documented in the `CONTRIBUTING.md` we should be fine for the moment.

I really like the bot:peek command, although it seems to [fail at the moment](https://github.com/devicons/devicon/pull/331) :-)

**Comment by Thomas-Boi** [comment]
Yeah, this is due to the comment bot that I wanted to add to the peek script 😅

I'm removing it from the peek script in my next push. I'll also add the manual trigger to the build script and update the CONTRIBUTING.md

**Comment by amacado** [comment]
Do you think it's possible to get the comment bot to work properly? This would be very handy! :heart:

**Comment by Thomas-Boi** [comment]
So I just double check the error. It seems like there's an issue on the Actions side and not from us. I'll comment out the code for the comment bot for now and I'llre check in the future in case it gets resolved.

I also opened an issue on their repo as well.
