### ISSUE TITLE
Icon request: Azure Cloud, Google Cloud

### ISSUE THREAD

**Issue by saranmahadev** [devicons/devicon#344]
### About the icon
Azure Cloud and Google Cloud are major Cloud Services in the Market
### Links
Google Cloud - https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Google_Cloud_Logo.svg/1280px-Google_Cloud_Logo.svg.png
Azure Cloud  - https://www.logo.wine/a/logo/Microsoft_Azure/Microsoft_Azure-Logo.wine.svg

**Comment by amacado** [comment]
Hello @saranmahadev, would you be so kind and separate those requests into two issues? (see our [CONTRIBUTING.md](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#requesting-a-icon))
I'm closing this issue, but feel free to reopen it once you modified it.
