### ISSUE TITLE
Icon request: Unity

### ISSUE THREAD

**Issue by AdamTCarroll** [devicons/devicon#345]
### About the icon
Unity Game Engine logo
### Links
https://fontawesome.com/icons/unity?style=brands
### Preview
https://www.google.com/search?q=unity+game+engine+logo&tbm=isch&ved=2ahUKEwi8hoG0l9fsAhX2XhUIHa0SCCEQ2-cCegQIABAA&oq=unity+game+engine+logo&gs_lcp=CgNpbWcQAzIECCMQJzICCAAyBggAEAUQHjoECAAQGDoGCAAQCBAeOgQIABAeUOsKWJgZYLMaaAFwAHgAgAFPiAHsA5IBATmYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=3lWZX7yfFva91fAPraWgiAI&bih=1321&biw=1375&rlz=1C1CHBF_enIE832IE832

**Comment by RubixDev** [comment]
I think a version visible on black backgound would also be useful. Something like this: 
<img alt="unity" src="https://user-images.githubusercontent.com/35602040/125848134-350b530d-5519-4995-8aa6-587ac3c05ba6.png" width="100" height="100">
https://downloads.rubixdev.de/unity.svg
