### ISSUE TITLE
Icon request: Unreal Engine

### ISSUE THREAD

**Issue by AdamTCarroll** [devicons/devicon#346]
### About the icon
Unreal Engine (Game Engine)
### Links
https://www.google.com/search?q=unreal+engine+logo&tbm=isch&ved=2ahUKEwiUw42sndfsAhX6XxUIHUlTAxkQ2-cCegQIABAA&oq=unreal+engine+logo&gs_lcp=CgNpbWcQAzIECAAQQzIECAAQQzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAUL4dWIslYLUmaAFwAHgAgAFCiAH_ApIBATaYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=GFyZX5TXGPq_1fAPyaaNyAE&bih=1321&biw=1375&rlz=1C1CHBF_enIE832IE832
### Preview
![unreal-engine-2-569488](https://user-images.githubusercontent.com/12417677/97433592-a9e07800-1915-11eb-8f0b-f4e8cdf8babb.png)

**Comment by Leuconoe** [comment]
bump

**Comment by Snailedlt** [comment]
The logos can be found here: https://epicgames.ent.box.com/s/c2m8idcyejqvg5mjf4e2q73b7jbaghft

guidelines: https://www.unrealengine.com/en-US/branding
