### ISSUE TITLE
Icon request: HackerRank

### ISSUE THREAD

**Issue by thrnkk** [devicons/devicon#351]
### About the icon
can be used to personal websites.
### Links
https://fontawesome.com/icons/hackerrank
### Preview
![image](https://user-images.githubusercontent.com/60141339/97579900-64818080-19d1-11eb-94a1-8177c2a1363d.png)

**Comment by amacado** [comment]
I'm not sure if this matches the goal for this icon kit. Why you think it would fit in?

**Comment by thrnkk** [comment]
It already has 'facebook' and 'twitter' logos for example, I was thinking it could fit with them.

**Comment by amacado** [comment]
@thrnkk thats a good point. In my opinion facebook and twitter also not fulfilling the idea of this repository, but as already mentioned we should clearify what this iconset is about @konpa @Thomas-Boi

**Comment by Thomas-Boi** [comment]
Hmm, this is a hard one to figure out. I do wonder why we have Facebook and Twitter in our repo in the first place. My thoughts are that they are famous tech companies who developed a lot of tech development (Facebook has React and GraphQL while Twitter created Bootstrap). However, that opens to the door to Netflix (ChaosMonkey) and Atlassian (CI/CD tools).

How about this? We will open a discussion on what types of icons should be included in our repo. Until then, we can leave this icon request open until we can decide what to do with it.
