### ISSUE TITLE
Icon request: Android

### ISSUE THREAD

**Issue by arashnrim** [devicons/devicon#359]
### About the icon
The Android icon is already existing in Devicon, but Android had a re-design in 2019 that changed the main logo.

Instead of having the full Android body in display, the new design only involves the head of the Android with minor tweaks (i.e., colour and location of eye dots).

### Links
- [A pop of color and more: updates to Android’s brand](https://www.blog.google/products/android/evolving-android-brand/)
- [Huge Inc project page](https://www.hugeinc.com/work/android)

### Preview
![500px-Android_new_logo_2019 svg](https://user-images.githubusercontent.com/47273556/98494571-3ecd6480-2278-11eb-9fdb-aaafe847b150.png)
![Android_symbol_green_2 max-500x500](https://user-images.githubusercontent.com/47273556/98494586-4b51bd00-2278-11eb-85bf-25399258465c.png)

Thank you!

**Comment by Panquesito7** [comment]
This issue is already fixed. Closing.
