### ISSUE TITLE
[ICON REQUEST]: PowerShell

### ISSUE THREAD

**Issue by VisualBean** [devicons/devicon#364]
### About the icon
Its PowerShell..
### Links
https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.1
### Preview
*If available, provide some images of the icon you would like to be added*
![image](https://user-images.githubusercontent.com/5294032/99530958-50aeb600-29a2-11eb-9e40-0889c77551ed.png)

**Comment by BenSouchet** [comment]
@Thomas-Boi Hi, I can add the icon but there is two colors variations, the "old" logo (before Powershell 7) and the new logo (Powershell 7 & above).
Everyone have in mind the blue one (the old) but maybe it's better to only add the new version, what do you think ?

**Comment by Snailedlt** [comment]
Found this SVG version: https://gist.github.com/Xainey/d5bde7d01dcbac51ac951810e94313aa
![image](https://user-images.githubusercontent.com/43886029/167025252-3cd6af96-e126-441b-b1a2-227cbad1e92f.png)

**Comment by Snailedlt** [comment]
## Powershell:
![image](https://user-images.githubusercontent.com/43886029/167025458-8e69b1aa-4dc3-471d-8b51-4d3025f6515b.png)


## Powershell 5.1:
![image](https://user-images.githubusercontent.com/43886029/167025518-c6a9884d-7b56-4d67-822e-99870ab1e8b8.png)

Image source: https://docs.microsoft.com/en-us/powershell/

**Comment by Snailedlt** [comment]
# SVG Versions
(All of these icons are from the [assets folder](https://github.com/PowerShell/PowerShell/tree/master/assets) of the Powershell GitHub repo)

## ps_black_128.svg
https://github.com/PowerShell/PowerShell/blob/master/assets/ps_black_128.svg
![image](https://user-images.githubusercontent.com/43886029/167026127-b05c7a77-4714-4295-b590-34ce55414ebb.png)

## powershell_128.svg
https://github.com/PowerShell/PowerShell/blob/master/assets/powershell_128.svg
![image](https://user-images.githubusercontent.com/43886029/167026170-f7d9ba76-66ad-49d0-98a5-e3167c9c12c7.png)

## av_colors_128.svg
Another cool version with the same colors as the Powershell avatar:
https://github.com/PowerShell/PowerShell/blob/master/assets/av_colors_128.svg
![image](https://user-images.githubusercontent.com/43886029/167026385-7e7a0474-0e91-4c1f-b73d-4ffd5a855256.png)

## ps_fluent_design_384.svg
https://github.com/PowerShell/PowerShell/blob/master/assets/ps_fluent_design_384.svg
![image](https://user-images.githubusercontent.com/43886029/167026788-21968df3-43cf-4bfa-b24a-5b4d265ad0a9.png)

**Comment by clcaldwell** [comment]
@SteveL-MSFT This has been open for a while. Any chance you can shed some light on what icon Microsoft thinks should be included here for Powershell?

**Comment by Snailedlt** [comment]
No response yet :/

**Comment by Snailedlt** [comment]
@andschwa
Perhaps you could let us know which Powershell icon(s) we should use?

**Comment by andschwa** [comment]
Let me ping the team.

**Comment by SydneyhSmith** [comment]
The image above "ps_black_128.svg" is a great choice! (PowerShell PM here 😄 )

**Comment by BenSouchet** [comment]
@andschwa Hi, okay will do the PR in the new days 🙂

**Comment by BenSouchet** [comment]
I just push the PR https://github.com/devicons/devicon/pull/1219
