### ISSUE TITLE
Icon request: Scalingo

### ISSUE THREAD

**Issue by cprodhomme** [devicons/devicon#366]
### About the icon
i want to implemente this logo in my project because it's a PAAS like Heroku.

### Links
https://scalingo.com
you can find the mediakit here : https://scalingo.com/mediakit.zip

### Preview
<img width="148" alt="Capture d’écran 2020-11-20 à 23 43 19" src="https://user-images.githubusercontent.com/7428736/99856862-346d6d80-2b8a-11eb-98c0-631dc548a02e.png">

<img width="210" alt="Capture d’écran 2020-11-20 à 23 44 57" src="https://user-images.githubusercontent.com/7428736/99856938-6979c000-2b8a-11eb-96c4-2cf6fe4f40d6.png">

**Comment by jusuchin85** [comment]
Icons have been updated since the initial issue creation. Raised a PR to import these into devicons.

**Comment by jusuchin85** [comment]
@Panquesito7 I think we forgot to label this issue with `in-develop` 😃
