### ISSUE TITLE
Icon request: WebAssembly/WASM

### ISSUE THREAD

**Issue by yusuf8ahmed** [devicons/devicon#367]
### About the icon
*Short description why you think this icon is matching in our project*
The newest addition to the web environment (HTML, JS, CSS, WASM)
### Links
The official winner of the WebAssembly logo competition
https://github.com/carlosbaraza/web-assembly-logo
### Preview
<img src="https://raw.githubusercontent.com/carlosbaraza/web-assembly-logo/master/dist/icon/web-assembly-icon.png" height="200"></img>

**Comment by Snailedlt** [comment]
[Website](https://webassembly.org/)
