### ISSUE TITLE
Icon request: F# (fsharp)

### ISSUE THREAD

**Issue by wRadion** [devicons/devicon#368]
### About the icon
F# is the functional programming language of the .NET platform.

### Links
https://en.wikipedia.org/wiki/F_Sharp_(programming_language)
https://fsharp.org/

### Preview
![F#Logo](https://upload.wikimedia.org/wikipedia/commons/5/57/Fsharp_logo.png)

**Comment by Panquesito7** [comment]
This issue is already fixed. Closing.
