### ISSUE TITLE
Issue : Mismatch with Github icon class name between devicon.dev and devicon.min.css

### ISSUE THREAD

**Issue by BenSouchet** [devicons/devicon#373]
Hi,
On the website (https://devicon.dev/) when I search for Github icon I get the follow icon class name : ```<i class="devicon-github-plain"></i>``` but if I download the repo and do a manual installation on my website the correct icon class name for Github is ```<i class="devicon-github-original"></i>```

```devicon-github-plain``` doesn't work, at least on my installation with the icons font.

By the way thanks for the great work 😉
Have a great day!

Ben

**Comment by amacado** [comment]
Hello @BenSouchet and thanks for the report. I can confirm the issue (see this https://jsfiddle.net/t4nqmkjx/) and proposing a fix in the linked pull request.

**Comment by BenSouchet** [comment]
@amacado Perfect, this fix the issue 🙂

**Comment by amacado** [comment]
I will reopen this issue until it's resolved and published and the pull request is accepted.

**Comment by amacado** [comment]
fix in release https://github.com/devicons/devicon/releases/tag/v2.7
