### ISSUE TITLE
Plain and Original class name mismatch

### ISSUE THREAD

**Issue by AliF50** [devicons/devicon#381]
Hello,

I believe there is an issue with SourceTree, GitHub and BitBucket original and plain naming convention for colored variants. I will give GitHub as an example

I saw in a previous issue that github went from `devicon-github-plain` to `devicon-github-original` which is fine but shouldn't line 1296 of devicon.min.css be changed from `.devicon-github-plain.colored, .devicon-github-plain-wordmark.colored {` to `.devicon-github-original.colored, .devicon-github-original-wordmark.colored {`? The same can be said about SourceTree and BitBucket.

Looking forward to your response.

**Comment by amacado** [comment]
Hello @AliF50, you're right! And therefore it's already changed in the newest release v2.7! See the updated `devicon.min.css `. This is done automatically by our build process.

Regarding SourceTree and BitBucket: The font versions for this icons are broken. See this issue: https://github.com/devicons/devicon/issues/248

If you're ok with it, I will close this issue :)
