### ISSUE TITLE
Auto-Update latest version (tagging) in GitHub Page (including CDN link)

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#395]
When a new version is beeing released it should auto update the version number which is shown on the GitHub page. Currently it has to be updated manually. I would also suggest to update the CDN links for pointing to a specific version instead of the `master` branch. This is recommended as best practices because when someone uses the CDN it should not be "auto updated" in the background which could cause Incompatibility (see discussion https://github.com/devicons/devicon/discussions/391).

![image](https://user-images.githubusercontent.com/8781699/102185023-b6626500-3eb0-11eb-86a6-d8c4c4920ca8.png)

I think it should be possible to use the GitHub REST API for that: https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-tags

**Comment by amacado** [comment]
I will work on this issue in the upcoming week.

**Comment by Thomas-Boi** [comment]
Closing this issue since #401 is already merged

**Comment by amacado** [comment]
@Thomas-Boi it will auto-close once merged into master ;-)
