### ISSUE TITLE
icon request: Next.js

### ISSUE THREAD

**Issue by r3nanp** [devicons/devicon#397]
### Next.js Icon 
*Next is a consolidated framework for React, I would love to see this icon here :)*
### Links
*Provide helpful links which can be used to take a deeper look into the icon and provide, if available, some resources (svg's) where the icon can be found*

[Next site](https://nextjs.org/)

<img src="https://camo.githubusercontent.com/4509a0e669bbbe7310edec5533ace738503462c41b63bda2a6a2f1c4c6ae4bd2/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4e6578742e6a732d3030303f267374796c653d666c6174266c6f676f3d6e6578742e6a73266c6f676f436f6c6f723d464646" />

### Preview
![nextjs](https://user-images.githubusercontent.com/47953339/102215109-055fc880-3eb8-11eb-89fb-2bb3201bd964.png)

![next](https://user-images.githubusercontent.com/47953339/102215114-085ab900-3eb8-11eb-9b3f-e59e3d60f2da.png)

**Comment by maltejur** [comment]
Can be closed now
