### ISSUE TITLE
Icon request: Twitter

### ISSUE THREAD

**Issue by ahmedfaaid** [devicons/devicon#399]
### About the icon
A logo icon of the Twitter bird.

There seems to be an issue with a few of the icons not showing up. One of them is the Twitter icon. I have attached an image of what it looks like on the website.

I am not sure if this is a known issue. If it is please let me know and I will delete this issue.

### Links
[Twitter](https://twitter.com)

### Preview
![twitter-icon](https://user-images.githubusercontent.com/42549274/102726276-70136880-42eb-11eb-9747-559c6f1acaf9.png)

**Comment by amacado** [comment]
Hello @ahmedfaaid, there is already an issue (https://github.com/devicons/devicon/issues/248) and a pull request (currently in draft) solving this issue https://github.com/devicons/devicon/pull/396
