### ISSUE TITLE
Icon request: Dart

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#409]
### About the icon
Flutter use dart as main programming language
### Links
https://icons8.com/icons/set/dart-programming-language
### Preview
![icons8-dart-48](https://user-images.githubusercontent.com/33158051/103333292-7b793900-4a3b-11eb-96f3-34db8d1c8efe.png)

**Comment by amacado** [comment]
Hello @yacosta738, we already have a issue regarding Dart (and also a pull request which needs to be improved). See https://github.com/devicons/devicon/issues/267
