### ISSUE TITLE
Icon request: R programming language

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#410]
### About the icon
R is statistic programming language used in artificial intelligence
### Links
https://www.google.com/search?q=r+programming+language+icon&sxsrf=ALeKk03VxmeTaScU3uBaIhnrFohlH0yw_A:1609308611484&tbm=isch&source=iu&ictx=1&fir=zYvxUnn8tHjwXM%252CohBHh0JBZZzDSM%252C_&vet=1&usg=AI4_-kRiGJ-xziB8mJHMwOLOvbjbR_flsw&sa=X&ved=2ahUKEwiQ5fvghfXtAhVEnFkKHcG1B9AQ9QF6BAgREAE&biw=1920&bih=923#imgrc=zYvxUnn8tHjwXM
### Preview
*If available, provide some images of the icon you would like to be added*
![Rlogo](https://user-images.githubusercontent.com/33158051/103333492-1d992100-4a3c-11eb-8cd4-e83cb2c44895.png)

**Comment by Panquesito7** [comment]
This issue is already fixed. Closing.
