### ISSUE TITLE
bot:peek failing "UnhandledPromiseRejectionWarning: Error: Request failed with status code 403"

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#414]
As you can see in PR https://github.com/devicons/devicon/pull/413 the bot:peek action is failing which can be traced to

![image](https://user-images.githubusercontent.com/8781699/103353064-1a3b7f00-4aa8-11eb-877a-c6d70de2b0c4.png)

Is this error caused by not using the latest version of `devicons/public-upload-to-imgur`? @Thomas-Boi 

![image](https://user-images.githubusercontent.com/8781699/103353003-f841fc80-4aa7-11eb-86c8-47508c2a790c.png)

**Comment by Thomas-Boi** [comment]
Yes it is. I'll work on [the peek bot pr](https://api.github.com/repos/Codertocat/Hello-World/pulls/2/commits) and commit your suggestions so we can merge it asap.

**Comment by Thomas-Boi** [comment]
Hi @amacado ,

I've added the some new features to the [peek bot pr](https://github.com/devicons/devicon/pull/412). The main feature is error handling for when an error is found, such as when the name can't be find in the title. 

You can see an example in this [PR](https://github.com/devicons/devicon/pull/408) at the very bottom. If you check the corresponding [action](https://github.com/devicons/devicon/actions/runs/453266528), you can see that the script failed when it can't find the title.

**Comment by amacado** [comment]
Still failing.. seehttps://github.com/devicons/devicon/actions/runs/453414999

**Comment by Thomas-Boi** [comment]
I think this is because the source branch didn't get the new commits yet. In fact, it seems like their source branch is forked from an older master:

![image](https://user-images.githubusercontent.com/43018778/103386366-532d2100-4ab3-11eb-9b99-867a2d8c718d.png)

The only solution is to ask them to pull our develop into their master.

**Comment by amacado** [comment]
Even with updated branch it fails (but a new error) :rofl:
https://github.com/devicons/devicon/runs/1630175599

![image](https://user-images.githubusercontent.com/8781699/103410107-1b34e500-4b6a-11eb-894f-98b0a42698cb.png)

**Comment by Thomas-Boi** [comment]
Hmm, this is interesting. I'll take another look at the script.

**Comment by Thomas-Boi** [comment]
@amacado please see my notes at the bottom of #421

**Comment by amacado** [comment]
@Thomas-Boi I have good and bad news. I found the reason why the `bot:peek` command is still failing. It's because of the restrictions of Github Secrets:
> Secrets are not passed to workflows that are triggered by a pull request from a fork 
https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

That's the reason why PR which are initiated from this repository working well but when the action is executed from a forked pull request it will fail on the image upload step with error code 403. Since the CLIENT_ID is stored as secret and is required when the upload is beeing executed it fails and following execution steps fill fail accordingly.

I could not find a easy solution for this problem, maybe we can use the build artifacts or the [GitHub CDN](https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d) as alternative to imgur. Or we need to find a different hosting provider without the need of a secret (I wasn't able to find one).

**Comment by Thomas-Boi** [comment]
Hey amacado,

You are correct. I'm surprised that I didn't notice this while making the workflow. Seems like we will be going back to the upload-artifacts then. Oh well😞

I will change the workflow file so we use the old method. As for the GitHub CDN, that was my first go to method but it seems like it's currently only available using their website (kinda like Icomoon). Maybe using Selenium might help but that can't be done right now.

**Comment by Thomas-Boi** [comment]
Closing this issue since the fix is in develop
