### ISSUE TITLE
Addressing abandoned PRs

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#417]
Hello all,

Currently, we have a lot of PRs that are abandoned by their authors (they didn't reply to comments for a long time). Unfortunately, there are many useful icons that these PRs contain and it's a shame if they are to go to waste. 

I would like to address this issue by forking these PRs, check the icon, then create a new PR from these abandoned PRs. Since GitHub tracks contribution by commits, the original authors should still receive their well-deserved credits.

I think a starting point would be to comment on these PRs and let the authors know that we will be salvaging their PRs. I'm thinking a month's notice should suffice. Then, I'll just work on these PR on my own time.

Let me know what you guys think.

**Comment by amacado** [comment]
@Thomas-Boi I highly appreciate this idea. I have the same from time to time (I feel uncomfortable with abandoned pr) ;-) But currently I don't have enough spare time to do it myself. 

Maybe we could - in addition to the comment - add a label to those pr? So we can easily track them. And once you (or someone else) is working on it comment on the pr that it's beeing reworked.

**Comment by amacado** [comment]
Maybe working with the github feature of "Project" could be a enhancement? So we could track pull requests which are waiting for a reaction from the initial contributor, pull requests which are reworked and those which are done?

**Comment by Thomas-Boi** [comment]
I agree, the "Project" tab would be useful in this case since we have to track the PR in multiple stages. Some of the old PR also contain multiple icons so we would need to split it up.

We can start by:
1. Make a label to identify these PR.
2. Comment and let the contributors know that we will "take over" their PR. Give them a month to respond. 
3. After that time, if nothing happens, we will start reclaiming it. We will track our progress using the "Project" tab and the assignee feature.

**Comment by Thomas-Boi** [comment]
I can start with the label and the comments. This shouldn't take too long

**Comment by Thomas-Boi** [comment]
Just something I notice:

If a workflow is triggered by a pull request event, it's the destination's workflow that will be triggered, not the forked repo (see [this](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories). So we can check any PR that has the correct PR name without needing to fork from their repo. We might still have to fork it to fix some stuff though but just something I notice.
