### ISSUE TITLE
Icon request: spring boot, maven, jhipster, less, xhtml. xml, sqlite, neo4j, vmware, hyper-v, virtual box, junit

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#418]
### About the icon
some technologies 
### Preview

![1280px-Maven_logo svg](https://user-images.githubusercontent.com/33158051/103392177-96ef4d00-4aea-11eb-9072-5b5a7b551a99.png)
![110-1105990_jhipster-banner-jhipster-logo](https://user-images.githubusercontent.com/33158051/103392180-9951a700-4aea-11eb-9b77-aec4129f47c6.png)
![download](https://user-images.githubusercontent.com/33158051/103392182-99ea3d80-4aea-11eb-8f96-5d8fb135247c.png)
![icons8-xml-file-64](https://user-images.githubusercontent.com/33158051/103392183-9a82d400-4aea-11eb-9a58-948f405082a9.png)
![kisspng-logo-vmware-vsphere-vcenter-virtualization-it-аутсорсинг-it-outsourcing-Киев-5b62e2faa5be87 7897632215332072906789](https://user-images.githubusercontent.com/33158051/103392184-9b1b6a80-4aea-11eb-9766-33fa6f22c7eb.jpg)
![png-transparent-hyper-v-microsoft-virtualization-virtual-machine-cloud-computing-microsoft-blue-text-logo](https://user-images.githubusercontent.com/33158051/103392187-9c4c9780-4aea-11eb-83cd-83f2754975cf.png)
![spring-boot](https://user-images.githubusercontent.com/33158051/103392188-9c4c9780-4aea-11eb-8800-4c864d00dd71.png)
![virtualbox-3-569544](https://user-images.githubusercontent.com/33158051/103392189-9ce52e00-4aea-11eb-8f72-e38385b07220.png)
![Screenshot_20201230_220224](https://user-images.githubusercontent.com/33158051/103392219-c2723780-4aea-11eb-9ce7-077151756000.png)

**Comment by amacado** [comment]
Hello @yacosta738, please have a look at https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#requesting-an-icon. Each request requires a own issue (and before requesting lookup it already is requested - like R).

Have a happy new year! 👍🏻
