### ISSUE TITLE
Node-Webkit is now NW.js

### ISSUE THREAD

**Issue by TheJaredWilcurt** [devicons/devicon#43]
Node-Webkit rebranded to NW.js a year ago. The search on your site should probably show it for both.

* http://nwjs.io

**Comment by TheJaredWilcurt** [comment]
yeah, I mean, it's still wrong? It's like how Jade was renamed to Pug. The site is just out dated and should be updated to have the correct name

**Comment by iamclaytonray** [comment]
Okay, we'll rename it. Thanks!

**Comment by Thomas-Boi** [comment]
Hello @iamclaytonray ,

I'll be helping out with this issue. We now have a new format for the `devicon.json` so our approach would be a bit different.
