### ISSUE TITLE
Icon request: Maven

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#430]
### About the icon
Maven is java dependencies manager
### Links
https://maven.apache.org/
### Preview
![1280px-Maven_logo svg](https://user-images.githubusercontent.com/33158051/103466428-2bd48f00-4d13-11eb-8d30-4602a442bfad.png)

**Comment by Snailedlt** [comment]
Logos: https://maven.apache.org/images/?C=N;O=D
(Hover over logos to see the logo type)

<img alt="maven-logo-white-on-black.svg" title="maven-logo-white-on-black.svg" src="https://maven.apache.org/images/maven-logo-white-on-black.svg" />

<img alt="maven-logo-white-on-black.purevec.svg" title="maven-logo-white-on-black.purevec.svg" src="https://maven.apache.org/images/maven-logo-white-on-black.purevec.svg" />

<img alt="maven-logo-black-on-white.svg" title="maven-logo-black-on-white.svg" src="https://maven.apache.org/images/maven-logo-black-on-white.svg" />

<img alt="maven-logo-black-on-white.purevec.svg" title="maven-logo-black-on-white.purevec.svg" src="https://maven.apache.org/images/maven-logo-black-on-white.purevec.svg" />


Version from commons.wikimedia.org: https://commons.wikimedia.org/wiki/File:Apache_Maven_logo.svg
<img alt="Maven" title="Maven" src="https://upload.wikimedia.org/wikipedia/commons/5/52/Apache_Maven_logo.svg" />

**Comment by Snailedlt** [comment]
Only feathers (SVG)
![file_type_maven_icon_130397](https://user-images.githubusercontent.com/43886029/158700377-62b0da69-81a2-4340-8ce6-dec718533aee.svg)

Source: https://icon-icons.com/icon/file-type-maven/130397
