### ISSUE TITLE
Icon request: Spring Boot

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#435]
### About the icon
Spring Boot is a java/kotlin framework
### Links
https://spring.io/projects/spring-boot
### Preview
![spring-boot](https://user-images.githubusercontent.com/33158051/103466606-760a4000-4d14-11eb-9941-2f3d00371471.png)

**Comment by amacado** [comment]
Can you provide the difference between https://github.com/devicons/devicon/issues/225? The same domain spring.io is mentioned, but different logos? :)

**Comment by yacosta738** [comment]
Spring Boot allows you to configure the spring framework in an easier and more productive way, Spring Boot is the evolution of the spring framework
This is logo for Spring Framework
![download](https://user-images.githubusercontent.com/33158051/103925017-e7673b80-50e4-11eb-9379-ceb82e3f382c.png)

Ideally: add both icons

**Comment by jusuchin85** [comment]
@Thomas-Boi @amacado @Panquesito7 can be closed? Seems a PR has already been merged: #550
