### ISSUE TITLE
Icon request: SQLite

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#437]
### About the icon
SQLite a simple database used in mobile aplications
### Links
https://www.sqlite.org/index.html
### Preview
*If available, provide some images of the icon you would like to be added*
![SQLite370 svg](https://user-images.githubusercontent.com/33158051/103467186-7b6a8900-4d1a-11eb-9907-491064bc8458.png)

**Comment by Snailedlt** [comment]
SVG (plain without wordmark): 
![SQLite-plain](https://upload.wikimedia.org/wikipedia/commons/9/97/Sqlite-square-icon.svg)

**Comment by Panquesito7** [comment]
Great work 🚀 Feel free to make a PR for that! Just make sure you follow our [contributing guidelines](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md). 🙂

**Comment by Snailedlt** [comment]
@Panquesito7 I attempted to add it and sent a PR. Not sure if it's good enough, but take a look if you'd like 👍
