### ISSUE TITLE
Icon request: Neo4j

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#438]
### About the icon
Neo4j is a graph database
### Links
https://neo4j.com/
### Preview
![neo4j](https://user-images.githubusercontent.com/33158051/103467225-de5c2000-4d1a-11eb-8edb-af46572cca00.png)

**Comment by amacado** [comment]
Closing this request in favour of #617 which has the more udpdated icon. Thanks for pointing out @tupaschoal
