### ISSUE TITLE
Icon request: Less

### ISSUE THREAD

**Issue by yacosta738** [devicons/devicon#439]
### About the icon
Less It's CSS, with just a little more.

### Links
http://lesscss.org/
![less](https://user-images.githubusercontent.com/33158051/103467248-1ebb9e00-4d1b-11eb-9a21-59f3e005f65c.jpeg)

### Preview
*If available, provide some images of the icon you would like to be added*

**Comment by amacado** [comment]
Closing this request, since we already have less as icon. Dont hesitate to reopen it, if I missed something :)

```
<!-- in your header -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@master/devicon.min.css">

<!-- in your body -->
<i class="devicon-less-plain-wordmark"></i>
```

![image](https://user-images.githubusercontent.com/8781699/103469138-36b61080-4d61-11eb-92e4-321106eece8b.png)
