### ISSUE TITLE
SVG extraction failes on icons containing a comment at the top (f.e. bash-plain.svg)

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#444]
EDIT: See https://github.com/devicons/devicon/issues/444#issuecomment-753699913 for explaination

There is a problem with displaying the `plain` version of the new bash icon. It shows up but not displaying the svg code below:
It works fine for the original version and also for the font versions. I wonder if this might be a result of the updated build process (removing color function or so? It's just a guess).

![image](https://user-images.githubusercontent.com/8781699/103469596-1f7a2180-4d67-11eb-92bb-f3812db1185c.png)

Interesting fact: When you open the svg in the browser it will show repeated:
https://raw.githubusercontent.com/devicons/devicon/master/icons/bash/bash-plain.svg
![image](https://user-images.githubusercontent.com/8781699/103469605-3de01d00-4d67-11eb-9ab6-5b1bd2064528.png)

**Comment by Thomas-Boi** [comment]
Hmm that's strange. The Icomoon color removal only applies to the font. The original SVG is not affected in anyway.

**Comment by amacado** [comment]
This was just a guess on my side, it is probably another reason..

**Comment by EnisMulic** [comment]
@amacado I just checked and it looks like there was some extra svg elements in the original file I took, removing that seems to fix the issue
https://raw.githubusercontent.com/EnisMulic/devicon/fix/icon/bash/icons/bash/bash-plain.svg
![image](https://user-images.githubusercontent.com/17247763/103488664-cfef3080-4e0e-11eb-8d63-c36b3b8db205.png)

**Comment by Thomas-Boi** [comment]
@EnisMulic I was wondering about that too. It seems that the plain version somehow has more content than the original. 

Can you create a new PR that contain this fix please?

**Comment by amacado** [comment]
The error is still there. I will investigate further. Think it's related to the way we extract the svg to show the code.

**Comment by amacado** [comment]
Yep, the error is related to the way we extract the information from the svg. When there is a comment block at the beginning of the svg we fail in showing the correct code. Some examples:

![image](https://user-images.githubusercontent.com/8781699/103492519-c32d0580-4e2b-11eb-8313-7a9d0fca0377.png)
![image](https://user-images.githubusercontent.com/8781699/103492540-f1124a00-4e2b-11eb-83ab-4be12c5fdc83.png)
![image](https://user-images.githubusercontent.com/8781699/103492549-fd96a280-4e2b-11eb-8940-d2560b98081d.png)

I will rename the issue and setup a fix for this.

**Comment by Thomas-Boi** [comment]
Wow, that's an interesting bug. I have merge your fix into develop. Let's hope that this will be the last time we see this issue.

**Comment by amacado** [comment]
Fixed in https://github.com/devicons/devicon/releases/tag/v2.8.2
