### ISSUE TITLE
Icon request: Godot

### ISSUE THREAD

**Issue by EnisMulic** [devicons/devicon#447]
### About the icon
Godot is a 2D and 3D, cross-platform, free and open-source game engine
### Links
[Website](https://godotengine.org/)   
[Logo](https://en.wikipedia.org/wiki/Godot_(game_engine)#/media/File:Godot_logo.svg)
### Preview
![og-wordmark](https://godotengine.org/themes/godotengine/assets/logo.svg)
![og](https://cdn.worldvectorlogo.com/logos/godot-1.svg)

<details>
Also testing request:icon lable
</details>

**Comment by tupaschoal** [comment]
This was added by #663 and is already live on https://devicon.dev/, so it can probably be closed.

**Comment by amacado** [comment]
Thanks for the hint @tupaschoal!
