### ISSUE TITLE
Some SVG icons do not fulfill viewbox requirement

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#456]
>Each .svg file contains one version of an icon in a 0 0 128 128 viewbox.
https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#svg-standards

Some examples:
https://raw.githubusercontent.com/devicons/devicon/master/icons/yunohost/yunohost-plain.svg
https://raw.githubusercontent.com/devicons/devicon/master/icons/cucumber/cucumber-plain-wordmark.svg

We should run a small script to check that all existing icons match our guidelines.

**Comment by amacado** [comment]
Maybe we should combine this issue with https://github.com/devicons/devicon/issues/407

**Comment by Thomas-Boi** [comment]
I think we should combine them for sure. I'll copy your comments over to that issue so everything is in one place and close this one.
