### ISSUE TITLE
Resource not accessible by integration error

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#478]
This error is generated by the comment step in the `Check SVGs` workflow:

![image](https://user-images.githubusercontent.com/43018778/104106590-f4626700-526b-11eb-92dc-bf329eef9886.png)

The interesting thing is this step works fine if the PR is opened by a branch inside the repo:

![image](https://user-images.githubusercontent.com/43018778/104106696-24aa0580-526c-11eb-9baf-a22de44d1665.png)

I will look more into this. This seems like another issue with access or auth.

**Comment by pan3793** [comment]
Encounter same issue on fork repo, do you find the solution?

**Comment by amacado** [comment]
@pan3793 currently @Thomas-Boi is working for finding a solution. This is more like a GitHub actions limitation and not a specific devicon problem.

There is f.e. this comment action https://github.com/mshick/add-pr-comment/ which solves this limitation by creating a proxy service for commenting on forked branches. But this requires to have a proxy up and running, which needs to be maintained.. Maybe we can find a simpler solution for this.

**Comment by Thomas-Boi** [comment]
So I poke around a bit more. It seems that the repo you mentioned was correct. No matter which Action I used, it got blocked whenever it's a fork. After doing some more research, the reason and solution can be found [here](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/). However, this requires a private repo, which obviously can't be done for us.

I have seen an interesting way to by pass this issue. @nyurik (see [here](https://github.com/nyurik/auto_pr_comments_from_forks) create a cron job/`schedule` workflow that runs every 5 mins and checks whether there's a new PR. If there is, find the workflow associated, download the artifacts, do its thing, then post on the PR. This is actually the inspiration for [my post](https://github.com/devicons/devicon/discussions/383#discussioncomment-270765)

I'll keep digging and see what I can come up with. It seems like many people in the community have this complaint too and GitHub is looking into it. Further updates will probably go into the [discussion](https://github.com/devicons/devicon/discussions/383) since this is bigger than the `check_svg` workflow.

**Comment by pan3793** [comment]
Found a simple solution to solve this, see detail at https://github.com/housepower/ClickHouse-Native-JDBC/pull/294

**Comment by Thomas-Boi** [comment]
Hi @pan3793 ,

I actually saw this resource when I was researching for a solution. At first, I was hesitant about this because of something that I found in the blog:

![image](https://user-images.githubusercontent.com/43018778/104233768-4f7c9100-5407-11eb-98b4-57b8e7eabd7e.png)

However, it seems like your code works and it's in a public repo so I wonder if there was an update. I can look into it more and see if it works cause this seems cleaner than the current way I'm doing it.

**Comment by pan3793** [comment]
I also hesitated until saw the next paragraph header **Improvements for public repository forks** 🤣

**Comment by Thomas-Boi** [comment]
Lol damn you are right 😆. Just scrolling down would have save me an entire evening working with the `workflow_run` thing. Thanks for the tip. I'll definitely implement this now

**Comment by nyurik** [comment]
> I have seen an interesting way to by pass this issue. @nyurik (see [here](https://github.com/nyurik/auto_pr_comments_from_forks) create a cron job/`schedule` workflow that runs every 5 mins and checks whether there's a new PR. If there is, find the workflow associated, download the artifacts, do its thing, then post on the PR. This is actually the inspiration for [my post](https://github.com/devicons/devicon/discussions/383#discussioncomment-270765)

There is now an official way to do this after I spoke with github for a long time about the issue. See https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run -- much more efficient than using the scheduler, but otherwise it is pretty much the same concept as I originally proposed.

**Comment by Thomas-Boi** [comment]
Thanks nyurik! We ended up using the `workflow_run` just as you said. I'm also looking into the `pull_request_target` as well.  Props for the cool work around that you thought of at first though.
