### ISSUE TITLE
Icon request: Blender

### ISSUE THREAD

**Issue by K0ST4S** [devicons/devicon#482]
### About the icon
When it comes to game development Blender is indistinguishable part that is open source and widely used.
### Links
https://commons.wikimedia.org/wiki/File:Logo_Blender.svg#/media/File:Blender_logo_no_text.svg
### Preview
![image](https://user-images.githubusercontent.com/43761714/104756559-a2867900-5764-11eb-8d5f-3b2ea87e199c.png)

**Comment by maxpxtts** [comment]
@K0ST4S @Panquesito7 this issue could now be closed
