### ISSUE TITLE
"data error: devicon-2.8.2\icons\drupal.eps"

### ISSUE THREAD

**Issue by RipplePiam** [devicons/devicon#484]
After downloading v2.8.2 and extracting the zip file, it will report an error: "data error: devicon-2.8.2\icons\drupal.eps"

![1](https://user-images.githubusercontent.com/45916506/104834967-43e50a80-58de-11eb-9f1d-0f172ce37328.png)

**Comment by amacado** [comment]
@RipplePiam can you please provide more information? What does this error mean? Where did you downloaded the package? When I download the latest [github release ](https://github.com/devicons/devicon/releases/tag/v2.8.2) the `drupal.eps` looks just fine.

**Comment by amacado** [comment]
Closed due to inactivity.
