### ISSUE TITLE
C, C++, and Python Icons Broken

### ISSUE THREAD

**Issue by PowerBroker2** [devicons/devicon#489]
Not sure if the links changed, discontinued, or both for C, C++, and Python. I'm trying to use the icons in my profile readme, but those particular icons are broken. Here is my readme section for my readme:

```html
<a href="https://www.arduino.cc/" target="_blank"> <img src="https://cdn.worldvectorlogo.com/logos/arduino-1.svg" alt="arduino" width="40" height="40"/> </a>
<a href="https://www.cprogramming.com/" target="_blank"> <img src="https://devicons.github.io/devicon/devicon.git/icons/c/c-original.svg" alt="c" width="40" height="40"/> </a>
<a href="https://www.w3schools.com/cpp/" target="_blank"> <img src="https://devicons.github.io/devicon/devicon.git/icons/cplusplus/cplusplus-original.svg" alt="cplusplus" width="40" height="40"/> </a>
<a href="https://flask.palletsprojects.com/" target="_blank"> <img src="https://www.vectorlogo.zone/logos/pocoo_flask/pocoo_flask-icon.svg" alt="flask" width="40" height="40"/> </a>
<a href="https://www.python.org" target="_blank"> <img src="https://devicons.github.io/devicon/devicon.git/icons/python/python-original.svg" alt="python" width="40" height="40"/> </a>
<a href="https://www.qt.io/" target="_blank"> <img src="https://upload.wikimedia.org/wikipedia/commons/0/0b/Qt_logo_2016.svg" alt="qt" width="40" height="40"/> </a>
<a href="https://www.sqlite.org/" target="_blank"> <img src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg" alt="sqlite" width="40" height="40"/>
```

Here's what is rendering:
![Capture](https://user-images.githubusercontent.com/20977405/105387022-1dc3b100-5be3-11eb-837f-4ae6cdd6b55c.PNG)

**Comment by amacado** [comment]
Hello @PowerBroker2, we changed the `gh-pages` branch to `master` branch (https://github.com/devicons/devicon/issues/289) for serving the github pages (https://devicon.dev). Therefore there was no need to have the `devicon.git` within the depreceated `gh-pages` branch anymore. This the content is now served directly from the `master` branch your links are broken.

Anyway: I would suggest to refer from a CDN provider and specify a tagged version like:

https://cdn.jsdelivr.net/gh/devicons/devicon@v2.9.0/icons/c/c-plain.svg

Or even better: Clone/Download the icons and use them directly 😄
