### ISSUE TITLE
Icon request: GraphQL

### ISSUE THREAD

**Issue by aravindvnair99** [devicons/devicon#490]
### About the icon

GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data.

### Links

https://graphql.org/img/logo.svg

### Preview

<img src="https://graphql.org/img/logo.svg" width=30%>

**Comment by amacado** [comment]
Duplicate of https://github.com/devicons/devicon/issues/209. I took this description and pasted it in the existing request.

**Comment by aravindvnair99** [comment]
> Duplicate of #209. I took this description and pasted it in the existing request.

Ah yes @amacado, thanks! I had [searched for duplicates](https://github.com/devicons/devicon/issues?q=is%3Aissue+is%3Aopen+graph) by typing "[Graph](https://github.com/devicons/devicon/issues?q=is%3Aissue+is%3Aopen+graph)" and not "[GraphQL](https://github.com/devicons/devicon/issues?q=is%3Aissue+is%3Aopen+graphql)". My bad. Sorry for the trouble!

**Comment by amacado** [comment]
@aravindvnair99 no worries, happens to the best of us ;-)
