### ISSUE TITLE
When you add more than two icons for the font versions, it adds up an `\n` in the GitHub comment

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#510]
When you add more than two icons for the font versions, it adds up an `\n` in the GitHub comment:

![image](https://user-images.githubusercontent.com/51391473/108760642-87511b00-7513-11eb-8fb4-02e7d735d1ee.png)

_Originally posted by @Panquesito7 in https://github.com/devicons/devicon/pull/509#discussion_r580538363_

**Comment by Panquesito7** [comment]
I think the problem is in the script, isn't it?
https://github.com/devicons/devicon/blob/825033326bb8256e56556fa85346bb7ae9e34d14/.github/scripts/icomoon_peek.py#L32-L33

**Comment by Thomas-Boi** [comment]
> I think the problem is in the script, isn't it?
> https://github.com/devicons/devicon/blob/825033326bb8256e56556fa85346bb7ae9e34d14/.github/scripts/icomoon_peek.py#L32-L33

It's not this one unfortunately, it's this one:

![image](https://user-images.githubusercontent.com/43018778/108800867-22181c80-7549-11eb-909c-1ec965f4cf94.png)


The first one is for logging inside the Python script. The second one is the Action that actually posting the message.

**Comment by Panquesito7** [comment]
Ah, OK. I see. I think the best to do is to remove the `\n`.

**Comment by amacado** [comment]
Fixed in https://github.com/devicons/devicon/pull/511
