### ISSUE TITLE
"Post Check SVG" action is not working as expected

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#514]
In PR #513, the "Post Check SVG" action still post the wrong message. This is strange since the `master` branch has been updated with the new version. 

Here is the old version with the incorrect name before we merge into `master`:
![image](https://user-images.githubusercontent.com/43018778/108892372-a22f9800-75c4-11eb-900f-bd2aca892ddb.png)

Here is the new version:
![image](https://user-images.githubusercontent.com/43018778/108892406-ac519680-75c4-11eb-83cd-85aa6b264f2b.png)

This name change was made in #509 and proves that the file has been merged into master. 

I'll look more into this issue during the weekend and test it with my forked repo.

**Comment by amacado** [comment]
There is also this failed action https://github.com/devicons/devicon/actions/runs/593486887 

![image](https://user-images.githubusercontent.com/8781699/108892744-89e56a80-7610-11eb-8041-c64cfbd5e662.png)

**Comment by Thomas-Boi** [comment]
> There is also this failed action https://github.com/devicons/devicon/actions/runs/593486887

This was bad design on my part. I'll have to change it later. Pretty much, what's happening is I only check for 2 results: successful run and failure.

However, there is also a third outcome: the workflow was skipped since the label is not "bot:peek". This is getting lumped into that.

There's also the bad status checks for getting the PR number. I'll have to change it to "always()" so the script will always have a PR to to.

**Comment by Panquesito7** [comment]
This issue is already fixed. Closing.
