### ISSUE TITLE
Make the SVG checker bot stop posting comments after each commit

### ISSUE THREAD

**Issue by Panquesito7** [devicons/devicon#534]
The SVG checker bot should only post 1 message to check if the SVG's added in the PR are fine (in the 1st commit).
It posts a comment each time a commit is made. It should only do that if there are errors found after the 1st commit.

_P.S.: Not sure if this should be moved to Discussions or keep it right here in Issues._

What do you think? 🙂

**Comment by amacado** [comment]
It's annoying that the bot is posting for every commit, that's true. But on the other hand it's meaningful. Since every commit/push can introduce changes which makes a build fail or succeed. So the bot **has** to check every push. Maybe we could find a solution to remove/hide old messages from the bot when they have the same content as before?

> P.S.: Not sure if this should be moved to Discussions or keep it right here in Issues.

Keep it here! :)

**Comment by Panquesito7** [comment]
> Since every commit/push can introduce changes which makes a build fail or succeed.  So the bot **has** to check every push.

Oh yes, I'm not saying that it shouldn't check on every push. I think I didn't explain it well, sorry!
Let's say we made a PR and the SVGs are just fine. It should post one message saying that the SVGs are fine. If the user makes a new commit and no fails found, then it shouldn't post a comment. On the 1st commit, post a message. If there's another commit, and there are no fails, then don't post a message. Hope I get to understand. 🙂

**Comment by Thomas-Boi** [comment]
That sounds like a pretty good idea. I am getting sick of seeing the bloated comment chains 🙃. 

A potential solution is to not comment anything if the SVGs are OK and only comment if there's an issue. I think this should be fine.

If you guys still like at least 1 message, I can look into that as well.

**Comment by Panquesito7** [comment]
> only comment if there's an issue. I think this should be fine.

Sounds good to me. Let's wait on @amacado's response to see what he thinks. 🙂

**Comment by amacado** [comment]
Maybe we should let the script fail and post a message when the pull request is violating our requirements. This would have the advantage of disallow the merge while the check is failing:

![image](https://user-images.githubusercontent.com/8781699/112072991-619b4e00-8b73-11eb-9769-86943621aec0.png)

I'm ok with posting a message only when the check fails (but posting the message as often until the problems are resolved). Having a message saying "everything is good" is nice in theory, but we see in practice it's annoying ;-) And the green checkmark for the status should be enough.

**Comment by Thomas-Boi** [comment]
> I'm ok with posting a message only when the check fails (but posting the message as often until the problems are resolved). Having a message saying "everything is good" is nice in theory, but we see in practice it's annoying ;-) And the green checkmark for the status should be enough.

Ok, that sounds good. I'll get on it 👍
