### ISSUE TITLE
Icon request: Zig

### ISSUE THREAD

**Issue by Himujjal** [devicons/devicon#543]
### About the icon
Zig is an upcoming systems programming language without any hidden control flow and low-level enough to compete with C.

### Links
https://raw.githubusercontent.com/ziglang/logo/master/zig-mark.svg
https://raw.githubusercontent.com/ziglang/logo/master/zig-mark-neg-white.svg
https://raw.githubusercontent.com/ziglang/logo/master/zig-mark-neg-black.svg

### Preview

![zig-icon](https://raw.githubusercontent.com/ziglang/logo/master/zig-mark.svg)

**Comment by tupaschoal** [comment]
This was added by #587 and is already live on https://devicon.dev/, so it can probably be closed.

**Comment by Himujjal** [comment]
cool
