### ISSUE TITLE
Icon request: Lua

### ISSUE THREAD

**Issue by Robby-V** [devicons/devicon#549]
### About the icon
Lua is a pretty popular programming language used by games like Roblox and Garry's Mod.
### Links
[https://www.lua.org/](https://www.lua.org/)
### Preview
![Lua Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Lua-Logo.svg/1200px-Lua-Logo.svg.png)

**Comment by Panquesito7** [comment]
This has been added in https://github.com/devicons/devicon/pull/548. Until the next release of Devicons, this won't be included in the `master` branch. Thank you for your suggestion. 🙂
