### ISSUE TITLE
Icon request: Ansible

### ISSUE THREAD

**Issue by syntaxseed** [devicons/devicon#566]
### About the icon
Ansible is one of the top automation, provisioning & deployment tools. By Red Hat.

### Links
https://www.ansible.com/

https://commons.m.wikimedia.org/wiki/File:Ansible_logo.svg

### Preview
White on black & black on white versions would be awesome.

Version with the word "ansible" and a version with just the circle icon.

**Comment by BenSouchet** [comment]
Added to my TODO :)
