### ISSUE TITLE
Icon request: Ant Design

### ISSUE THREAD

**Issue by saifulshihab** [devicons/devicon#570]
### Links
Ant Design: <img src='https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg' alt='ant' />
Src: https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg

**Comment by Thomas-Boi** [comment]
Hi @saifulshihab can you please split each icon into its own requests? This makes it easier for us to close issues based on PR.

**Comment by saifulshihab** [comment]
Sure.
