### ISSUE TITLE
Icon request: Matlab

### ISSUE THREAD

**Issue by AndreaLunaro** [devicons/devicon#588]
### About the icon
Matlab is the standard language for scientific use
### Links
Matlab: https://it.mathworks.com/

**Comment by amacado** [comment]
Matlab was already added in v2.10.0 (https://github.com/devicons/devicon/pull/504). See https://github.com/devicons/devicon/pull/492 by @Panquesito7 

```
<i class="devicon-matlab-plain"></i>
```
