### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Swiizouille** [devicons/devicon#600]
### About the icon
*Short description why you think this icon is matching in our project*
### Links
*Provide helpful links which can be used to take a deeper look into the icon and provide, if available, some resources (svg's) where the icon can be found*
### Preview
*If available, provide some images of the icon you would like to be added*

**Comment by amacado** [comment]
Docker is already in the repository. Also this issue does not fit in our guidelines.

```
<i class="devicon-docker-plain"></i>
```
