### ISSUE TITLE
Icon request: Jamstack

### ISSUE THREAD

**Issue by Utkarsh1504** [devicons/devicon#618]
### About the icon
Jamstack is an architecture designed to make the web faster, more secure, and easier to scale. It builds on many of the tools and workflows which developers love, and which bring maximum productivity.

### Links
https://jamstack.org/
https://jamstack.org/logos/

### Preview
<img width="132" alt="Jamstack_Icon_Original_Solid" src="https://user-images.githubusercontent.com/76392681/118630851-8cf58e80-b7ec-11eb-8a95-6a044902f770.png">

**Comment by Thomas-Boi** [comment]
Don't delete this Issue manually. Leave this open so we can see if linking issue using commit message works.
