### ISSUE TITLE
Icon request: Blazor

### ISSUE THREAD

**Issue by martintaylor1635** [devicons/devicon#619]
### About the icon
Blazor lets you build interactive web UIs using C# instead of JavaScript. Blazor apps are composed of reusable web UI components implemented using C#, HTML, and CSS. Both client and server code is written in C#, allowing you to share code and libraries.
### Links
[Blazor Homepage](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor)
### Preview
![BrandBlazor_nohalo_1000x](https://user-images.githubusercontent.com/58300181/118833035-09ee3a00-b8b9-11eb-95de-ee6e69e2f510.png)

**Comment by Snailedlt** [comment]
@martintaylor1635 did you find any official SVG versions?

**Comment by canaleal** [comment]
Official branding can be found here:
- https://github.com/dotnet/aspnetcore/issues/26522

Only original, plain, and maybe line can be created from these icons. No official wordmark exists.

**Comment by canaleal** [comment]
Closing as the icon now exists in main.
