### ISSUE TITLE
Some svg icons don't have colors

### ISSUE THREAD

**Issue by eden-lane** [devicons/devicon#63]
Some icons have attribute `fill` (angular's icon for example), but some of them don't. For example, webpack's icon has attribute class `cls-1` instead of `fill`. Is it intended?

**Comment by oligibson** [comment]
@eden-lane thanks for raising, this isn't intended behaviour. I will look at this when I get a chance.

**Comment by VladimirDev93** [comment]
Facebook icon doesn't have the blue background.
