### ISSUE TITLE
Icon request: GameMaker Studio

### ISSUE THREAD

**Issue by AhmedElTabarani** [devicons/devicon#633]
### About the icon
GameMaker Studio is a game engine, so it is within the domain of programmers and developers

### Links

https://www.yoyogames.com/en/legal/brand
https://en.wikipedia.org/wiki/File:GameMaker_Studio_2.svg

**Comment by Snailedlt** [comment]
Direct dowload link for their logos: https://coal.yoyogames.com/brand/GameMaker_Logo.zip

**Comment by Snailedlt** [comment]
## SVG Logo from WikiMedia:
![](https://upload.wikimedia.org/wikipedia/en/4/4b/GameMaker_Logo.svg)

**Comment by Snailedlt** [comment]
How to convert bitmap images (PNG, JPG,...) to vector images (SVG...): https://github.com/devicons/devicon/pull/1428#issuecomment-1271702666

**Comment by PantheraRed** [comment]
I think this icon should be discussed before looking into the [PR](https://github.com/devicons/devicon/pull/1772). YoYo Games take their [branding](https://gamemaker.io/en/legal/brand) seriously.
