### ISSUE TITLE
CDN Delivery

### ISSUE THREAD

**Issue by samanix** [devicons/devicon#68]
You should try and submit to a more stable CDN like [cdnjs](https://cdnjs.com) and/or [jsdelivr](https://www.jsdelivr.com/)

[This link works](https://cdn.jsdelivr.net/npm/devicon) for jsdelivr but not the [github one](https://cdn.jsdelivr.net/gh/konpa/devicon/devicon.min.css)

https://github.com/jsdelivr/jsdelivr#usage

**Comment by jimaek** [comment]
If npm works you dont need the github link. They are the same.

**Comment by Samanix** [comment]
Some people may want to use others though, having a broader delivery will allow for more people to use it

**Comment by jimaek** [comment]
I dont really understand your point. For user nothing would change if the file was delivered from Github or npm.

But in any case, if you want github to work then the owner must use semver valid tags in Github. But again its not required because npm already works.

**Comment by iamclaytonray** [comment]
We can do this via [unpkg](https://unpkg.com/#/). Thanks for filing an issue!

**Comment by amacado** [comment]
Swap from RawGit to jsDelivr in #222, but adding alternatives is a good idea!

**Comment by Thomas-Boi** [comment]
Closing this issue since it's fixed in #222
