### ISSUE TITLE
Feature Request: missing icons from Font Mfizz 

### ISSUE THREAD

**Issue by noraj** [devicons/devicon#683]
### Suggested Feature

Here is an abandoned project **Font Mfizz**

> Font Mfizz provides scalable vector icons representing programming languages, operating systems, software engineering, and technology. It was designed designed for technology and software geeks. It can be customized — size, color, drop shadow, and anything that can be done with the power of CSS.

The project is not updated since 2017 but has a good bunch of icons but it's still a good list of ideas for devicon.

- Source: https://github.com/fizzed/font-mfizz
- Demo: http://fizzed.com/oss/font-mfizz

### Why we should have this feature

Completing the missing icons from Font Mfizz.

**Comment by Thomas-Boi** [comment]
This is a good idea. There are a couple of stale repos that do the same job as us. It'll be nice to grow the repo together with them.

**Comment by soham4abc** [comment]
I would like to work on this issue!

**Comment by Thomas-Boi** [comment]
Hey @soham4abc, 

That'll be great 😄! Check out the [`CONTRIBUTING.md`](https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md) if you have any questions

**Comment by noraj** [comment]
> Devicon can only accept icons of tech that exists/people us. Some of the icon from Font Mfizz, like

3dprint was in the category deprecated, all other, except from that category, do exist

![image](https://user-images.githubusercontent.com/16578570/159177608-b4ea3fe7-ff17-4a7d-b2fe-3c5e54c0592c.png)
