### ISSUE TITLE
Enhance contrast for icon preview on devicon.dev (devicon-plain invisible)

### ISSUE THREAD

**Issue by albertcodes** [devicons/devicon#685]
### Bug
*The devicon plain icon does not preview on the main page.. shows as null.*

![devicons-bug](https://user-images.githubusercontent.com/34912159/122327054-ee1c9900-cf35-11eb-9d95-599b66389f3f.png)

### Possible Fixes/Solutions
*Probe on this issue to detect what is causing the issue.*

**Comment by Panquesito7** [comment]
This is due to the website's background being the same color as that SVG (there are even other SVGs that cannot be seen too).

**Comment by amacado** [comment]
@Panquesito7 why you reopened this issue? :)

**Comment by Panquesito7** [comment]
> @Panquesito7, why you reopened this issue? :)

This still has to be fixed, I think. 🙂

**Comment by Thomas-Boi** [comment]
Perhaps we can change the background color of the icons box?

**Comment by amacado** [comment]
Since **any** color we choose might conflict with any (future) icon it's not a good solution to change the background color or the icon color.  I can think of other solutions:

- Maybe we can provide a "background color picker" within the devicons website? 
- Or in an advanced implementation auto-detect the icons color and choose a contrast? 
- Or enhancing the `devicon.json` with a parameter to allow selecting a background color (like `contrastColor`) for the preview?
```
{
    "name": "devicon",
    "tags": [
        "iconset"
    ],
    "versions": {
        "svg": [
            "original",
            "original-wordmark",
            "plain",
            "plain-wordmark"
        ],
        "font": [
            "plain",
            "plain-wordmark"
        ]
    },
    "color": "#60BE86",
    "contrastColor": "#000000",
    "aliases": []
},
```

**Comment by Thomas-Boi** [comment]
I think option 1: "Maybe we can provide a "background color picker" within the devicons website?" is the best. Inkscape has an option that can change the background and I enjoy using that. A color picker is not too hard to do (might have some libraries already out there) as well.

**Comment by Panquesito7** [comment]
> Perhaps we can change the background color of the icons box?

This could be a temporary solution while we work on what @amacado said (I like the `contrastColor` setting theory).

**Comment by Thomas-Boi** [comment]
Just a thought on the other options:

Option 2 is plausible if we have a formula for the opposite color contrast. However, I think we might overengineer the problem
Option 3 will take a bit of work, both in converting the existing `devicon.json` and for future contributors to update it.

I think the simplest solution that fixes the problem (option 1) is the best one. 

Also, a thought I had is we can have a default checkerboard background. Then, in the corner, we can have a color picker button that changes the background.

**Comment by Panquesito7** [comment]
Sounds good to me. If you need any help on this, please ping me. Thanks. 🙂

**Comment by Thomas-Boi** [comment]
@amacado if you are cool with option 1, I can start looking into it

**Comment by Thomas-Boi** [comment]
Closing this. Please see #698 for progress on this feature
