### ISSUE TITLE
react

### ISSUE THREAD

**Issue by FredrickHilarian** [devicons/devicon#687]
### About the icon
*Short description of why you think this icon belongs in our project.*

### Links
*Provide links to the icon's official website/repository. Anywhere that shows us what the technology is about and its official logo. If available, also provide some resources (SVG's) where the icon can be found (Font Awesome, Icomoon, etc..).*

**Comment by amacado** [comment]
Closing this request(?) since 
1) We already have `react`
2) Request is invalid in terms of requesting guidelines (https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#requesting-an-icon)
