### ISSUE TITLE
Icon request: LLVM

### ISSUE THREAD

**Issue by tupaschoal** [devicons/devicon#688]
### About the icon
LLVM is a set of compiler and tools based on it that powers up many compilation environments today.

### Links
[LLVM Website](https://llvm.org/)
[LLVM Logo page](https://llvm.org/Logo.html)

### Preview
![image](https://user-images.githubusercontent.com/6443427/123156954-51c82a00-d440-11eb-9b8d-c7790fb42a57.png)

### Note
They have used several images throughout the history, but I guess the latest one should be picked, if possible.

**Comment by BenSouchet** [comment]
If this request get 10 upvote (thumb up) I vectorize this "logo" as SVG and do the PR ;)
