### ISSUE TITLE
Icon request: GNU Compiler Collection (GCC)

### ISSUE THREAD

**Issue by tupaschoal** [devicons/devicon#690]
### About the icon
GNU Compiler Collection, as the name implies is a set of compiler and tools based on it that powers up probably most compilation environments today.

### Links
[GCC Website](https://gcc.gnu.org/)

### Preview
![image](https://gcc.gnu.org/img/gccegg-65.png)

**Comment by Thomas-Boi** [comment]
Don't close this PR manually. This is left opene as a test case for closing Issue using reference in commit message.
