### ISSUE TITLE
Amend guidelines to avoid mis-matched icon layouts

### ISSUE THREAD

**Issue by Chippd** [devicons/devicon#70]
I want to use the icons in this repo programatically, but I'm getting awkward results, visually I mean. See screenshot. The "plain-wordmark" icons aren't all the same structure in that some have the icon to the left of the word, and some have it above. I think an update to the guidelines to specify that the wordmark should be one or the other (whatever is most prevalent currently within the repo). I can submit a PR with my ideas if that makes sense. 

http://imgur.com/6nGq5pK

Thank you all for the work, it's a great resource.

**Comment by Thomas-Boi** [comment]
I'll be closing this issue since there's no new comments on it. If someone comment, I'll reopen this
