### ISSUE TITLE
Icon request: ESLint

### ISSUE THREAD

**Issue by theblobscp** [devicons/devicon#714]
### About the icon
*Short description of why you think this icon belongs in our project.*
ESLint is a popular javascript thing and I think it would be good to add it

### Links
<ul>
<li><a href="https://github.com/eslint/eslint">Repo</a></li>
<li><a href="https://iconscout.com/icon/eslint-1">ESLint svg download (sorry it's bad, it's all I found)</a></li>
</ul>

**Comment by BenSouchet** [comment]
Added to my TODO :)

By the way the official logo on the website is a valid SVG:
https://d33wubrfki0l68.cloudfront.net/204482ca413433c80cd14fe369e2181dd97a2a40/092e2/assets/img/logo.svg
