### ISSUE TITLE
Icon request: Neovim

### ISSUE THREAD

**Issue by zeitchef** [devicons/devicon#717]
### About the icon
Neovim is a Vim-based text editor engineered for extensibility and usability, to encourage new applications and contributions.

### Links
http://neovim.io/
Neovim icons can be downloaded [here](http://neovim.io/logos/neovim-logos.zip)

### Preview
![neovim-logo-flat](https://user-images.githubusercontent.com/6670659/124632369-8f877280-de84-11eb-99ae-6f13645ab050.png)

![neovim-mark](https://user-images.githubusercontent.com/6670659/124632228-6f57b380-de84-11eb-80cb-576d045bc921.png)

**Comment by SIMULATAN** [comment]
Any updates?

The SVG version of the images in the original issue are here:
neovim-logo-flat:
![neovim-logo-flat](https://user-images.githubusercontent.com/63104422/178288421-f837ca66-85b4-42b5-a30e-f971d12d6bca.svg)
neovim-mark:
![neovim-mark](https://user-images.githubusercontent.com/63104422/178288469-ddb93ca9-5827-45b3-9cc7-450368984bea.svg)
