### ISSUE TITLE
Feature Request: Convert Styles to Attributes, Inline Styles, or Prefix Styles

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#745]
### Problem 
Currently, our `svg-checker bot` is checking whether an SVG has a style element in order to adhere to the [standards](https://github.com/devicons/devicon/issues/400). Summary: we have scoping issues with the default class names => we want contributors to convert it to attributes instead. 

Currently, the contributors have to fix it manually. This could be improved since it's possible to fix using SVGO, which is already part of our build script.

### Suggested Feature
There are three ways to fix the issue using [SVGO](https://github.com/svg/svgo#built-in-plugins):
1. Our current [`prefixIds` plugin](https://github.com/svg/svgo/blob/master/plugins/prefixIds.js) actually prefix `classes` as well. Thus, we'll avoid the scoping issues as seen in #400 while still retains the benefits of classes. 
  - This option requires the least work from us as well since it's already present in the workflow.
  - Before running script (taken from [here](https://github.com/devicons/devicon/blob/a36a63aa8398f615653411c494e0ab8fd7a6bc53/icons/centos/centos-original.svg):
    `<style><![CDATA[.I{fill:rgb(57.647059%,13.333333%,47.45098%)}.J{fill:rgb(93.72549%,65.490196%,14.117647%)}.K{fill:rgb(61.176471%,80.392157%,16.470588%)}.L{fill:rgb(14.901961%,14.509804%,46.666667%)}]]></style>`
  - After running script (ran locally on my computer with current settings):
    `<style>.centos-I{fill:#932279}.centos-J{fill:#efa724}.centos-K{fill:#9ccd2a}.centos-L{fill:#262577}</style>`
  - To test for yourself, run this command locally in the `devicon` root folder: `npm run optimize-svg -- --svgFiles=JSON_ARRAY_OF_PATHS"`. 
    - Ex: mine was `npm run optimize-svg -- --svgFiles="[\"./centos.svg\"]"`

2. The [plugin `inlineStyles`](https://github.com/svg/svgo/blob/master/plugins/inlineStyles.js) will move `<style>` tag declarations to individual `style` attributes. Ex: 
  - Before running the script:
  ```
  <svg>
    <style>
      .a { fill: red }
    </style>
    <path class='a' />
  </svg>
  ```

  - After running the script:
  ```
  <svg>
    <path fill='red' />
  </svg>
  ```
  - Note: This script can be combined with other plugins. We can add `removeStyle` option to delete the `<style>` if there's any non-matched classes. We can add `convertStyleToAttrs` to change the `style` to attributes like `fill`.

3. Use the  `convertStyleToAttrs` plugin in conjunction with step 1 to change the `style` to attributes like `fill`. This is just one extra step compared to step 1.

### Why we should have this feature
- This will save the contributors' time from removing/converting style tags manually. 
- Using classes usually save space in the SVG files, reducing our repo's size.

@amacado @Panquesito7 would you be open to this? If we choose option 1, all we have to do is remove the check in the `check-bot`.

**Comment by amacado** [comment]
@Thomas-Boi can you explain why we have to remove the check in `check-bot` when we decide going with option 1? Maybe we sould run the optimize-bot (bot:optimize) for every pull request (and not only on labeling action?

**Comment by Thomas-Boi** [comment]
> @Thomas-Boi can you explain why we have to remove the check in `check-bot` when we decide going with option 1? 

I meant that we will only need to remove the check for the `convert style to fill` in the `check-bot`. We will still keep the `check-bot`, just simplify it.

> Maybe we sould run the optimize-bot (bot:optimize) for every pull request (and not only on labeling action?

That's fine by me. So do we want the `optimize-bot` to run whenever the PR is accepted? Then, it will open a PR into develop? Note that we can't commit to a PR from a forked repo (see [this issue](https://github.com/devicons/devicon/issues/614)), so we will have to open a PR whenever we optimize the files.

I can look into auto-merging the PR when this happens. I think there are actions that already do this.

**Comment by amacado** [comment]
> I can look into auto-merging the PR when this happens. I think there are actions that already do this.

I appreciate all the work you're investing but maybe we are over-engineering here. It's not very complicated to convert styles to attributes by hand (or using a tool) and commit those changes again. And our bot already points this problem out (maybe add some help text there which explains how to convert or even providing a tool?). Having a workflow which will run **after** a merge, which's purpose is to modify the files in the latest merge just to create a new pull request which needs to be auto-merged for "simplification".. Sounds pretty complicated and not very intuitive, or? And I haven't even mentioned the problems which are introduced with auto-merging.

**Comment by Thomas-Boi** [comment]
Hi @amacado,

> I appreciate all the work you're investing but maybe we are over-engineering here

I agree with the sentiment. I would like to avoid changing the current workflow as much as possible. The `auto-merge` was merely a feature that I thought of; it's not something that I enjoy doing but feasible.

The simplest way to do this (that I can think of) is option 1 in my original posting:
- We keep the same optimize workflow but change the bot to prefix classes alongside ids. This is one extra line in the config object for the bot. This prevents conflicts as seen with the `gradient` issue awhile ago.
- We remove the check statement (not the whole `check-bot`) for `classes to fills` since the `optimizer-bot` now fix that issue for us. All the other checks will still be present.

One thing I want to clear up in case there's any confusion:
- The `optimizer-bot` is in charge of minifying and prefix ids
- It's only run once as part of the `build` step of a new release. It's not triggered through labelling like `bot:peek` or any other `pull_request` event.

**Comment by Thomas-Boi** [comment]
@amacado Thank you 👍. If the solution turns out to not work well, we can always revert it
