### ISSUE TITLE
Swift icon missing from npm module

### ISSUE THREAD

**Issue by paulrberg** [devicons/devicon#76]
I'm able to get the swift icon if I import the devicon.min.css, but when I install the npm module, there's no icon at all.

**Comment by JGJP** [comment]
I'm getting the same thing with the webpack icons, maybe just a question of updating the npm module? Webpack definitely seems like it should be included.

**Comment by pratamatama** [comment]
I had same problem. Installed trough npm. 

![xscriptindonesia dev_technologies_create 1](https://user-images.githubusercontent.com/42239243/51585235-412bc680-1f0b-11e9-9774-ccb29e5ea62a.png)

**Comment by amacado** [comment]
Related to #288
