### ISSUE TITLE
Bug Report: Icomoon can't convert SVGs with strokes to fills

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#766]
### Bug
Icomoon will ignore SVGs with strokes when making it into a font. This was warned by the website since it's a known limitation of the site.

![image](https://user-images.githubusercontent.com/43018778/126567800-6eb7e641-a75d-4d31-b52a-4e15c45bcc44.png)

Most of the time, this does not causes any problem. The warning above has displayed itself before the build bot was implemented. However, for some cases, the font are wrongly created.

As you can see below, for these two SVGs, Icomoon would generate 5 Glyphs. The mini icons are what the icon actually look like.
![image](https://user-images.githubusercontent.com/43018778/126580622-2b5e0b6a-92d6-4fa6-896f-412d833a4cde.png)

Script wise, here's what the CSS looks like:
```
.devicon-socketio-original-wordmark .path1:before {
  content: "\e901";
  color: none;
}
.devicon-socketio-original-wordmark .path2:before {
  content: "\e902";
  margin-left: -1em;
  color: ;
}
.devicon-socketio-original-wordmark .path3:before {
  content: "\e903";
  margin-left: -1em;
  color: ;
}
.devicon-socketio-original-wordmark .path4:before {
  content: "\e904";
  margin-left: -1em;
  color: ;
}
```

The issue is caused by the circle in `socketio-original-wordmark` using stroke for the outline. This is misinterpreted by Icomoon  and caused the above issue.

### How to replicate the bug
Upload the current versions of `socketio` SVGs to Icomoon and try to generate a font with them.

### Possible Fixes/Solutions
This will have to be fixed manually by the user. However, `peek-bot` will need to be upgraded so it also check the font version rather than just the SVG version to prevent this from happening. It should also parse the SVG for `stroke`-related attribute

**Comment by Panquesito7** [comment]
I think this is fixed now.
