### ISSUE TITLE
Bug Report: socketio icons contains strokes, not fills.

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#767]
### Bug
This is related to #766. `socketio` Icons don't get generated properly by Icomoon due to the presence of strokes in the SVGs.

### How to replicate the bug
Upload the current `socketio` SVGs to Icomoon and try generating icons from them.

### Possible Fixes/Solutions
Convert the strokes to fills/paths as [stated by Icomoon](https://icomoon.io/#docs/stroke-to-fill).

**Comment by theblobscp** [comment]
You should close this since you merged the pr @Thomas-Boi
