### ISSUE TITLE
Icon request: Vuetify

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#770]
### About the icon
From their website: "Vuetify is a Vue UI Library with beautifully handcrafted Material Components".

### Links
https://vuetifyjs.com/en/

*This was requested by a Discord user*

**Comment by vikash2806** [comment]
@Thomas-Boi Hey do I need to re request for Vuetify icon ? I mean creating a new issue by uploading the SVG. 
or do I need to wait for some time to access Vuetify icon on [devicon](https://devicon.dev) website ? 
it seems this issue is opened long time ago.

**Comment by Thomas-Boi** [comment]
Hi @vikash2806,

The repo unfortunately doesn't work this way. The icons are made mostly by contributors; the maintainers' duty is with maintaining the repo and improving the workflow. Due to the great amounts of icons request, opening an Issue doesn't guarantee that an icon is made for it. However, it does bring attention of the icons you want to make to other people.

You can view a more detailed explanation [here](The icons are made mostly by contributors; the maintainers).
