### ISSUE TITLE
Icon request: [laravel]

### ISSUE THREAD

**Issue by kilatex** [devicons/devicon#771]
### About the icon
*Short description of why you think this icon belongs in our project.*

### Links
*Provide links to the icon's official website/repository. Anywhere that shows us what the technology is about and its official logo. If available, also provide some resources (SVG's) where the icon can be found (Font Awesome, Icomoon, etc..).*

**Comment by theblobscp** [comment]
Actually fill out the teemplate?

**Comment by TheFoxarmy** [comment]
The Devicon website already has Laravel.

**Comment by theblobscp** [comment]
They still need to say what exactly they want, like original, line
