### ISSUE TITLE
Icon request: [nuxtjs, vuetify, solidjs]

### ISSUE THREAD

**Issue by musedadam** [devicons/devicon#776]
### About the icon
nuxtjs is a web framework for vue
vuetify is a ui framework for vue
solidjs is a javascript framework
### Links
nuxtjs: https://nuxtjs.org/design
vuetify: https://images.app.goo.gl/DsDWNVk2o8oci95Q8
solidjs: https://images.app.goo.gl/oPnbxQUy25V5ESHVA
*Provide links to the icon's official website/repository. Anywhere that shows us what the technology is about and its official logo. If available, also provide some resources (SVG's) where the icon can be found (Font Awesome, Icomoon, etc..).*

**Comment by theblobscp** [comment]
See #770 for vuetify

**Comment by Thomas-Boi** [comment]
Hi @musedadam,

Please split this PR into 3 individual PRs. There are 3 icons here so each should have their own PR.
