### ISSUE TITLE
Feature Request: Update the PR Template

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#784]
### Problem 
The PR template doesn't look very good when in preview mode.

Case 1: see [this](https://github.com/Thomas-Boi/devicon/pull/46)
Case 2 (better): see [this](https://github.com/Thomas-Boi/devicon/pull/47)

### Suggested Feature
Update the PR template so it looks better. Also preview it in Markdown mode.

### Why we should have this feature
Professional PR templates standardize the repo and make it easier for us to fix issues.

**Comment by theblobscp** [comment]
Which of the prs is linked to the issue

**Comment by Panquesito7** [comment]
I'll try to update it to make it look better. Thanks for reporting. 🙂

**Comment by Panquesito7** [comment]
@Thomas-Boi, but why do you say it looks bad? For me, it's already good.

**Comment by Thomas-Boi** [comment]
Sorry, "bad" makes it worse than it sounds. Most of it is good but we definitely need to fix a few small things:

- The top section (info on the PR template) is probably unnecessary. Does the average person needs to see it? We will have to look at this for every PRs as well so any redundant info is unneeded.
- When I delete the `New Icon` section, the top section became bolded as well. This is distracting => if we plan to keep the top part, we definitely need to address this.
- The checkboxes were formatted wrong (which is my fault). Empty checkboxes should be `[ ]` with a space in between them.

Hope that helps @Panquesito7

**Comment by Thomas-Boi** [comment]
One more thing:
I notice the text here is wrong
> # New Feature Section
> 

Notice that it says "adding a new icon", should be "adding a new feature"
