### ISSUE TITLE
[ICON REQUEST]: Cloudflare

### ISSUE THREAD

**Issue by izzqz** [devicons/devicon#785]
### About the icon
Cloudflare is pretty popular, and I would like to use it in devicons.

### Links
- Cloudflare in font awesome:
https://fontawesome.com/v5.15/icons/cloudflare

- Cloudflare logo:
https://github.com/cloudflare/research.cloudflare.com/blob/3e0022632a18404431c9393329b87e370259d2a9/img/cloud.svg

**Comment by BenSouchet** [comment]
Added to my TODO :)

**Comment by MatthewPerryDev** [comment]
Any updates on this?

**Comment by BenSouchet** [comment]
Hi, just added a PR #1298 to add the Cloudflare icons.
For the Cloudflare workers I will work on it tomorrow.

**Comment by Snailedlt** [comment]
@izzqz Can you please split this into two issues? 
One issue for each icon like described here: https://github.com/devicons/devicon/wiki/Requesting-an-Icon

**Comment by Snailedlt** [comment]
Made a new icon request, and edited this one so it can be closed with the next release
