### ISSUE TITLE
Icon request: JiraAlign

### ISSUE THREAD

**Issue by vellala2000** [devicons/devicon#789]
### About the icon
JiraAlign is software development SDLC tool that closely integrates with Jira.

### Links
https://wac-cdn.atlassian.com/dam/jcr:b821902e-5ee6-432f-a7e2-9f18aaa2641b/Jira%20Align-blue-rgb.svg?cdnVersion=1747
https://www.atlassian.com/software/jira/align

**Comment by yeyeto2788** [comment]
I'll be working on this one.

**Comment by Snailedlt** [comment]
All Atlassian logos can be found here: https://atlassian.design/resources/logo-library

Direct download for Jira Align: https://assets.ctfassets.net/8j5aqoy0ts8s/3lCp3ysGSidBd0wkWyPM4D/e4b8269fb78936b9f542b1e11392f24a/Jira_Align-Attribution-Lockup.zip

**Comment by Snailedlt** [comment]
Here's some previews:
![jira-align-logo-gradient-white-attribution_rgb](https://user-images.githubusercontent.com/43886029/196701722-789cc2da-2d12-4a20-978e-0a660bb6424c.svg)
![jira-align-logo-gradient-blue-attribution_rgb](https://user-images.githubusercontent.com/43886029/196701727-fafa5f0c-03c9-42db-b104-595882e61306.svg)
![jira-align-logo-gradient-neutral-attribution_rgb](https://user-images.githubusercontent.com/43886029/196701728-4561bc0b-3cd8-4a94-8223-20bed6555dde.svg)
