### ISSUE TITLE
Icon request: Capacitor

### ISSUE THREAD

**Issue by gurvancampion** [devicons/devicon#825]
### What would you like to share?

**About the icon**
Capacitor is a cross-platform API and code execution layer that makes it easy to call Native SDKs from web code and to write custom native plugins that your app may need. Additionally, Capacitor provides first-class Progressive Web App support so you can write one app and deploy it to the app stores and the mobile web.

**Links and sources**
https://capacitorjs.com/
https://github.com/simple-icons/simple-icons/blob/develop/icons/capacitor.svg

**Comment by opuu** [comment]
+1

**Comment by BenSouchet** [comment]
Added to my TODO ;)
