### ISSUE TITLE
Icon request: Fastify

### ISSUE THREAD

**Issue by gurvancampion** [devicons/devicon#826]
### What would you like to share?

**About the icon**
Fast and low overhead web framework, for Node.js.

**Links and sources**
https://www.fastify.io/
https://github.com/simple-icons/simple-icons/blob/develop/icons/fastify.svg

Edit: Could you fix the problem of the template when creating a new Icon request? I will then add more request

**Comment by BenSouchet** [comment]
Working on it! :)
