### ISSUE TITLE
Icon request: LaTeX

### ISSUE THREAD

**Issue by katrinaalaimo** [devicons/devicon#838]
### What would you like to share?

LaTeX is a high level descriptive markup language and is widely used in academia as a document preparation system. 

GitHub:
[https://github.com/latex3](https://github.com/latex3)

Official website:
[https://www.latex-project.org/](https://www.latex-project.org/)

Wikipedia page:
[https://en.wikipedia.org/wiki/LaTeX](https://en.wikipedia.org/wiki/LaTeX)

**Comment by BenSouchet** [comment]
Added to my TODO :)
