### ISSUE TITLE
[BUG] Website is malfunctioning since the repo and npm size are too large to be served via JSDelivr

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#846]
### Bug description

Our repo package is getting too large to be served via JSDelivr. 

Here are the stats of our package:
![image](https://user-images.githubusercontent.com/43018778/132731039-49b5253b-d621-45fa-a16a-c473764fa7be.png)

The strange thing is this doesn't happen to our previous versions, which were also around the same size:
![image](https://user-images.githubusercontent.com/43018778/132731118-3197388b-a8d4-4601-b333-ba0224b635c5.png)

This is affecting the website's functionality:
![image](https://user-images.githubusercontent.com/43018778/132731188-6bf6d8aa-4b25-4e03-a367-ecacadd5be75.png)

The website can't pull individual files from the repo due to the size.

The biggest offender is the `/icons` folder. Its size is 116 MB, which is 89% of the package size right now.

Next is `node_modules` at 27.8 MB. However, our dependencies are all listed as `devDependencies`, which should not affect the install nor publish size.

The remaining size is split between the `/fonts` at 2.8 MB, `/.github` at 3.2 MB, and `/icomoon.json` at 1.8 MB. These are negligible.

### Possible fixes or solutions

Here are a few solutions:
1. We can switch the URL to use the GitHub repo instead. This is not considered good practice but it might do for a quick fix.
2. Move the icons into a separate repo 
  - I like this idea the most. The icons are quite huge and doesn't need to be in the same location as the fonts.
  - The only issue is how do separate these two. Perhaps make a new repo for the `fonts` only? Whenever there's a new release, a PR is opened into it that contains the new font files and css files only?
3.  Ignore them somehow when pushing to npm.
  - Perhaps when we publish to npm, we can delete the `/icons` folder? This means that all URL to the `.svg` files will be done through GitHub from now on.
  - If `npm` has something similar to `.gitignore`, we can use that too.
4. Change the size limit of JSDelivr.
  - Currently, it's set at 50 MB. Perhaps we can increase it? This might eventually reach a ceiling so I think this is a short term solution.

### Additional information

We should try and fix this ASAP. Probably make a minor release for it too since I merged `kaggle` yesterday.

EDIT: See this [comment](https://github.com/devicons/devicon/pull/842#issuecomment-915944882) for the error message found when loading an icon.
Here's the image:
![image](https://user-images.githubusercontent.com/43018778/132746737-36328a9e-d360-43d9-8f6b-10159f84088c.png)

**Comment by maltejur** [comment]
A quick fix would be to replace jsdelivr with [gitcdn](https://gitcdn.link/). That would just be a drop in replacement, changing `https://cdn.jsdelivr.net/gh/devicons/devicon/icons` to `https://gitcdn.link/repo/devicons/devicon/master/icons`.

**Comment by MartinKolarik** [comment]
Hi, Martin from jsDelivr here. This looks like an error on our side - checking and will give you an update soon.

**Comment by MartinKolarik** [comment]
We identified the problem and it'll be fixed in a moment.

**Comment by MartinKolarik** [comment]
Fixed now, sorry for the inconvenience. A TLDR is that there's was a bug which in some very specific cases incorrectly triggered this restriction. You can continue using the GitHub source regardless of the total repo size, as long as you request only individual files (i.e., directory listings have the 50 MB limit but you don't seem to be using those).

**Comment by amacado** [comment]
Thanks for the update @MartinKolarik! Just for my personal interest: How did you found our issue so fast? Did anyone contacted you or you have some kind of internal tracking within jsDelivr which alerted you?

**Comment by jimaek** [comment]
> Thanks for the update @MartinKolarik! Just for my personal interest: How did you found our issue so fast? Did anyone contacted you or you have some kind of internal tracking within jsDelivr which alerted you?

We monitor mentions of jsDelivr around the web including Github to pro-actively help users :)

**Comment by Panquesito7** [comment]
Awesome! Thanks for your help, @MartinKolarik, and @jimaek! 😄👍
