### ISSUE TITLE
Icon request: Camtasia Studio

### ISSUE THREAD

**Issue by melvincwng** [devicons/devicon#850]
### About the icon

It's a popular video editing software tool

### Links and sources

Official website: https://www.techsmith.com/video-editor.html
Resources of logo: https://www.techsmith.com/download-logo.html
Alternative resource of logo: https://icons8.com/icons/set/camtasia

### Additional information

Hope this icon gets implemented in your library soon!  Thanks :)

**Comment by Thomas-Boi** [comment]
I think this is too generic to be considered a tool for the programming industry. Please view [this link](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F) and let us know what you think. I'll close this for now but if you can convince us, we'll reopen the PR.
