### ISSUE TITLE
Icon request: Microsoft Office

### ISSUE THREAD

**Issue by melvincwng** [devicons/devicon#851]
### About the icon

A lot of people around the globe utilize Microsoft Office products; it's essentially a basic tech skill in 2021.

### Links and sources

Link: https://www.microsoft.com/en-us/microsoft-365/microsoft-office
Resource to icon: https://icons8.com/icons/set/microsoft-office

Alternative resource 1 to icon: https://icomoon.io/app/#/select 
Alternative resource 2 (search for Microsoft): https://www.flaticon.com/

### Additional information

MS Office is the rectangle box looking icon

**Comment by Thomas-Boi** [comment]
Unfortunately, the product is too general to fit in this repo. You can check out our reasoning [here](https://github.com/devicons/devicon/wiki/What-Icons-Do-We-Accept%3F)
