### ISSUE TITLE
Icon request: Netlify

### ISSUE THREAD

**Issue by ghost** [devicons/devicon#854]
### About the icon

There hasn't been icons related to hosting and it's part of software development

### Links and sources

https://www.netlify.com/?_ga=2.245523715.622517246.1631639445-1899199550.1631639445

**Comment by Snailedlt** [comment]
Logos can be found here -> https://www.netlify.com/press/#logos

👇 I prefer these ones 👇 
## SVG's (official)

logomark.svg (`netlify-original`)
![](https://www.netlify.com/v3/img/components/logomark.svg)

logomark-light.svg (`netlify-plain`)
![](https://www.netlify.com/v3/img/components/logomark-light.svg)

full-logo-light.svg (`netlify-original-wordmark`)
![](https://www.netlify.com/v3/img/components/full-logo-light.svg)

full-logo-light-simple.svg (`netlify-plain-wordmark`)
![](https://www.netlify.com/v3/img/components/full-logo-light-simple.svg)

**Comment by canaleal** [comment]
This Issue (#854) was created prior to this other issue (https://github.com/devicons/devicon/issues/1814), but regardless, the SVG has been merged into develop:
- https://github.com/devicons/devicon/pull/1820
