### ISSUE TITLE
Icon request: Livewire

### ISSUE THREAD

**Issue by joowdx** [devicons/devicon#855]
### About the icon

Livewire is a full-stack framework for Laravel that makes building dynamic interfaces simple, without leaving the comfort of Laravel.

### Links and sources

https://laravel-livewire.com/

**Comment by CesarObedFL** [comment]
team, include this icon please...

**Comment by AbdulWahedSabury** [comment]
include this icon please...

**Comment by Panquesito7** [comment]
Working on this.
