### ISSUE TITLE
Icon request: [NAME]

### ISSUE THREAD

**Issue by NargesEl** [devicons/devicon#857]
### About the icon

Seaborn, Matplotlib, Metabase, Scikit-learn

### Links and sources

https://scikit-learn.org/stable/

https://www.metabase.com/

https://matplotlib.org/

https://seaborn.pydata.org/

**Comment by amacado** [comment]
Hi @NargesEl, please take a look at our [contribution guidelines](https://github.com/devicons/devicon/blob/2ae2a900d2f041da66e950e4d48052658d850630/CONTRIBUTING.md#requestingIcon), chapter "Requesting an Icon" 😄 

You have violated our guideline:
>"Please create separate issues for each icon"
