### ISSUE TITLE
Icon request: Pytest

### ISSUE THREAD

**Issue by NargesEl** [devicons/devicon#861]
### About the icon

Pytest

### Links and sources

https://docs.pytest.org/en/6.2.x/

### Additional information

thank you

**Comment by theblobscp** [comment]
Can you give your issues a name? It looks like you're spamming from my notifications.

**Comment by NargesEl** [comment]
Ops sorry. New to this.

**Comment by theblobscp** [comment]
It's fine, just try not to do it again.
