### ISSUE TITLE
Icon request: Solidity

### ISSUE THREAD

**Issue by Mayank17M** [devicons/devicon#864]
### About the icon

Solidity is an object-oriented, high-level language for implementing smart contracts.

### Links and sources

[Solidity documentation](https://docs.soliditylang.org/en/v0.8.7/)
[Icon](https://docs.soliditylang.org/en/v0.8.7/_images/logo.svg)

**Comment by pecraveiro** [comment]
Up! :octocat:

**Comment by Mayank17M** [comment]
Yes, this works as well.

**Comment by Panquesito7** [comment]
Would any of you like to work on this? :)

**Comment by Mayank17M** [comment]
Yes, I'd love to contribute :)

**Comment by pecraveiro** [comment]
Sure, how can we help you @Panquesito7?

**Comment by pecraveiro** [comment]
We fork the ''devicons/icons'' folder and add Solidity original and plain .svg icons?

**Comment by pecraveiro** [comment]
''Uploads are disabled.
File uploads require push access to this repository.''

**Comment by Panquesito7** [comment]
> I don't know why, but I can't upload a folder into devicons/icons repository.
> 
> Solidity Original SVG: https://upload.wikimedia.org/wikipedia/commons/9/98/Solidity_logo.svg Solidity Original SVG: https://docs.soliditylang.org/en/v0.8.11/_static/logo.svg

You need to fork the repository, clone your fork, make your changes, commit, then push to *your fork*.
If you need any more help, feel free to join our [**Discord server**](https://discord.gg/hScy8KWACQ) and ask for help! We're happy to help. 🙂

**Comment by pecraveiro** [comment]
> > I don't know why, but I can't upload a folder into devicons/icons repository.
> > Solidity Original SVG: https://upload.wikimedia.org/wikipedia/commons/9/98/Solidity_logo.svg Solidity Original SVG: https://docs.soliditylang.org/en/v0.8.11/_static/logo.svg
> 
> You need to fork the repository, clone your fork, make your changes, commit, then push to _your fork_. If you need any more help, feel free to join our [**Discord server**](https://discord.gg/hScy8KWACQ) and ask for help! We're happy to help. 🙂

https://github.com/devicons/devicon/pull/1007
