### ISSUE TITLE
Add copy button with links

### ISSUE THREAD

**Issue by Jaspreet099** [devicons/devicon#876]
### Problem

![image](https://user-images.githubusercontent.com/75212002/136735055-cba51158-17af-45f4-8011-bd4a1841e748.png)
its sometimes difficult to copy link

### Suggested feature

Add small copy button near links 

### Why should we have this feature?

it will save time and improve UX

**Comment by Snailedlt** [comment]
To add to this. Make the field focusable (I think that's the right term), so that you can `CTRL`+`A` to select the entire link, instead of the entire page
