### ISSUE TITLE
Icon request: APL

### ISSUE THREAD

**Issue by Zeyu-Li** [devicons/devicon#879]
### About the icon

APL is an array based programming language

### Links and sources

Pretty ancient programming language but used for it's compactness

About: https://en.wikipedia.org/wiki/APL_(programming_language)
SVG link: https://commons.wikimedia.org/wiki/File:APLgradeup.svg
learn more about APL: https://microapl.com/APL/introduction_chapter1.html

**Comment by abrudz** [comment]
Update:

About: https://apl.wiki
SVG link: https://github.com/abrudz/logos/blob/main/apl/green.svg
Learn more about APL: https://apl.wiki/Introductions

**Comment by Zeyu-Li** [comment]
thanks for adding it guys!
