### ISSUE TITLE
Icon request: NetworkX

### ISSUE THREAD

**Issue by bpaixao** [devicons/devicon#898]
### About the icon

I'm working on the project and I noticed there is no icon for it. 

### Links and sources

This is the documentation about: https://networkx.org/

**Comment by ozanuslan** [comment]
Does this look good for you? The version with text was way too wide to be included in the correct format.
![networkx](https://user-images.githubusercontent.com/54141068/141863502-9c602aa0-f72e-4d7a-9e3d-0c520604159f.png)

**Comment by bpaixao** [comment]
Thanks!!!

**Comment by Panquesito7** [comment]
> Does this look good for you? The version with text was way too wide to be included in the correct format. ![networkx](https://user-images.githubusercontent.com/54141068/141863502-9c602aa0-f72e-4d7a-9e3d-0c520604159f.png)

Looks good. 😄👍
Feel free to create a PR.
