### ISSUE TITLE
Icon Request: Swagger

### ISSUE THREAD

**Issue by mxmzb** [devicons/devicon#903]
### About the icon

Swagger is a tool to design and document APIs

### Links and sources

https://swaggerhub.com

**Comment by yeyeto2788** [comment]
@Snailedlt please assign this one to me 🥳

I'll be using [this](https://static1.smartbear.co/swagger/media/assets/images/swagger_logo.svg) which is the one on the swagger website.

**Comment by Snailedlt** [comment]
Sounds good to me.

You can find the logos here: https://github.com/search?l=SVG&q=org%3Aswagger-api+logo&type=Code

And here:
https://github.com/swagger-api/swagger.io/tree/c3449cde8b570664c04c9661e98dc6dc941f5395/images/assets
