### ISSUE TITLE
[BUG] The Discord logo is outdated

### ISSUE THREAD

**Issue by Panquesito7** [devicons/devicon#907]
### Bug description

The Discord logo on the website is outdated.
The new logo can be found at https://discord.com/branding

![image](https://user-images.githubusercontent.com/51391473/140844854-b7bfc7bf-35ac-4839-a4e6-ea049526b1f6.png)

### Possible fixes or solutions

Update the Discord logo to the latest version

### Additional information

Nope.

**Comment by Mazzya** [comment]
Hi Panquesito, can you assign me this task ?

**Comment by Panquesito7** [comment]
> Hi Panquesito, can you assign me this task ?

Assigned. Feel free to work on it. 🙂

**Comment by vikash2806** [comment]
> > Hi Panquesito, can you assign me this task ?
> 
> Assigned. Feel free to work on it. 🙂

Hey David @Panquesito7  seems he haven't fixed this bug. Can you assign it to me so that I can work on this bug ?
