### ISSUE TITLE
[IDEA] devicon svg "cdn"/"api"

### ISSUE THREAD

**Issue by maltejur** [devicons/devicon#913]
### Problem

Using devicon svg icons with jsdelivr is a bit of a hassle, since you can only use github links (`cdn.jsdelivr.net/gh/devicons/devicon`) and not the standard npm ones (`cdn.jsdelivr.net/npm/devicons@2.14.0`), and you can only use the icons in the color that they were made for (at least when using them in img tags, see for example #911).

### Suggested feature

It would be nice to have our own "CDN", where you can just get an icon by using `cdn.devicon.dev/nextjs/original?color=red`.

### Why should we have this feature?

This would make usage of the devicon icons in img tags much easier and in some cases is what makes it possible in the first place.

### Additional information

I could work on this and it wouldn't be that hard, it is just a simple web server that generates the svgs on the fly, and a caching/cdn layer like [cloudfront](https://aws.amazon.com/cloudfront/) that makes the whole thing fast.

Closes #977

**Comment by Thomas-Boi** [comment]
I'm open to having our own webserver. However, where will we be hosting it? Also, depending on the amount of access, we might have to discuss costs and maintenance as well.

Regarding the colors, I think that's a good idea but it'd require us to change the color of the SVGs when the server send it to people. I'm not sure what's the best way to do that since some of them use gradients. Open to ideas though.

**Comment by maltejur** [comment]
> I'm not sure what's the best way to do that since some of them use gradients. Open to ideas though.

I'd say just remove all color attributes from the svg and then add an `fill="..."` to the root svg element.

**Comment by Thomas-Boi** [comment]
Oh crap, I'm so sorry, I wanted to reply to your question, not edit it

**Comment by Thomas-Boi** [comment]
Ok, here's my response:

I think that's a good idea. However, I'm not sure how gradients will react to it or when an SVG has a non-transparent background. Perhaps we can limit changing colors of SVGs only to `plain` SVGs? These SVGs are guarantee to look good with 1 color and avoid potential issues of gradients or having foregrounds and backgrounds the same colors.

So for example, `devicon/nodejs/original` would return the `original` version. It doesn't matter if we have `devicon/nodejs/original?color=red`, we will always return the `original` version. However, if the version was `plain` or font-friendly (as in, `original` but it's effectively `plain`), we will return the modified version.

What do you think?

**Comment by maltejur** [comment]
> What do you think?

Yeah that sounds like a good solution.

> I'm open to having our own webserver. However, where will we be hosting it? Also, depending on the amount of access, we might have to discuss costs and maintenance as well.

The server itself I could host on my own vps, it shouldn't experience that much load because of the cache. [CloudFront](https://aws.amazon.com/cloudfront/pricing) costs arrount 0.10€/GB and I doubt that we will serve hundreds of gigabytes of svg files a month, so I could also just pay that by myself.

**Comment by Thomas-Boi** [comment]
I'm open to the project's idea. Let's see what @amacado think about it.

On a second note, can we find out how many people are using our CDN link right now and see if this feature is welcomed? If not a lot of people are using it, it might not be worthwhile. I'll also share this in the Discord server and see what the community thinks of it.

**Comment by maltejur** [comment]
> On a second note, can we find out how many people are using our CDN link right now and see if this feature is welcomed? If not a lot of people are using it, it might not be worthwhile. I'll also share this in the Discord server and see what the community thinks of it.

https://data.jsdelivr.com/v1/package/gh/devicons/devicon/stats

Seems to be a lot already

**Comment by amacado** [comment]
I appreciate your enthusiasm, but running your own CDN seems very time-consuming and cost-intensive to me. I think we should focus more on our core competencies and not maintain a huge ecosystem.

**Comment by maltejur** [comment]
> seems very time-consuming

I don't think so. It is not like we would rent servers all over the world and build our own CDN. [Cloudfront](https://aws.amazon.com/cloudfront) is completely managed, you just enter a origin domain where the content is originally hosted and cloudfront caches it and serves it fast everywhere.

> cost-intensive

[Cloudfront costs ~0.10€/GB](https://aws.amazon.com/cloudfront/pricing/?nc=sn&loc=3) and the average svg file in this repository is around 4079B, which means that you can serve 2451581 Icons for 1€ (`1 / (4079 * 10e-9 * 0.1)`). The total amount of icons served from jsdelivr is 2404471, so all of the icons served by jsdelivr until now would have cost us ~1€ (my calculations could also be wrong).

**Comment by maltejur** [comment]
I have also worked already on a little server that can send colored svgs and set that up with cloudfront.

https://d2ybq8ooy8ehk5.cloudfront.net
https://github.com/maltejur/devicon-cdn

**Comment by Thomas-Boi** [comment]
I think the server is not too big of a feature for our repo. It's basically an extension of our existing CDN. Just think of it as a standalone app run privately by @maltejur, albeit under our organization. As for the cost, I was hesitant at first but if @maltejur is willing to cover that, I think it works out. Just my two cents.

**Comment by amacado** [comment]
Maybe I was a bit distracted by the word "CDN", what @maltejur describes is, at least in my understanding, more an additional service than a CDN (while the actual CDN part is based on cloudfront). I could think of a public repository (name pending) under the devicon organization and a "private", unofficial service which is hosted/maintained by @maltejur (based on the official repo). So anyone could host this service for himself (if they like to) and since it's not a service by devicon we (as devicon organisation) are not responsible for any liability (like hosting/costs/service availability,..). Of course we can give a shoutout in the README, just making sure it's a unofficial, third-party service. What do you think of this idea?

**Comment by maltejur** [comment]
Sounds good, but how "unofficial" would you like the hosted service to be? Would the links on the website that currently use jsdelivr be updated to use it instead? Would it be under a `devicon.dev` subdomain? I also don't think that people would host this for themselves, since it really is a pretty small program and if you have the capabilities to host this for your project, you probably also have the capabilities to recolor the icons directly in your project in an easier way.

About the name: I would stick with `devicon-cdn`, since it still best describes to the user what it does (it serves the devicon icons via a cdn). And for example jsDelivr also just uses something like cloudflare CDN I believe.

**Comment by Thomas-Boi** [comment]
I think @amacado is worried about the long term usage (maintenance, cost etc.) of the server. If @maltejur ever leave the group, who'll take up maintaining/paying for the server etc. I think these issues are manageable. @maltejur already said the cost is quite small. In fact, if it's used by a lot of people, I'm willing to pitch in or even take over the server cost + maintenance if maltejur leaves the org. The cost would work out to about a few dollars for me a year at most. If it ever gets really expensive, we can just take it down and go back to what we have now.

If @amacado is worried about the legal aspect, I don't see an issue with this either. I can't see how this might negatively affect the organization. We can set up requirements for PR so it requires reviews before merge. This will prevent malicious users from using the server and redirecting it somewhere else. We could even make it a private repo, thus only `devicon` orgs members can access it.

Regarding whether this make the repo too much like an ecosystem, I'd say that this is only a minor change. It's not a huge project that changes the project significantly. It won't bloat our project in my opinion.

**Comment by Thomas-Boi** [comment]
Hey @maltejur, how is your progress on this PR? No rush, I just want to check in.

**Comment by maltejur** [comment]
Since one guy in the discord recommended Vercel (because it is pretty much free for FOSS projects and with it hosting isn't a concern anymore), I am currently redoing the whole thing in NodeJS. The actual API part is pretty much done, but as already said in the discord it would be nice to tie this to a rework of the website. That is what I am currently working on. You can see the current version here:

https://github.com/maltejur/devicon-website

Some examples of the API:
https://devicon-website.vercel.app/api/devicon/plain?color=orange \
https://devicon-website.vercel.app/api/devicon/plain?size=30px&format=png

But be aware that I am currently just trying out some things with the website and it definitely will look a lot different when it is done. Small prototype how it should look like layout-wise: https://www.figma.com/proto/HkwNGws6orEVctZzTNBYQN/devicon-website
