### ISSUE TITLE
Icon request: Python Package Index (PyPI)

### ISSUE THREAD

**Issue by wasi-master** [devicons/devicon#922]
### About the icon

PyPI is the official third-party software repository for Python. A lot of people use Python therefore use PyPI on a daily basis, The main reason I need this icon for is to have a hyperlink to the PyPI page

## Links

Official Website: https://pypi.org/
Wikipedia Page: https://wikipedia.org/wiki/Python_Package_Index

## SVG sources

There are two logos, one large and one small
Large Logo: https://github.com/pypa/warehouse/blob/main/warehouse/static/images/logo-large.svg
Small Logo: https://github.com/pypa/warehouse/blob/main/warehouse/static/images/logo-small.svg

### Previews
Small logo:
![Small Logo](https://raw.githubusercontent.com/pypa/warehouse/main/warehouse/static/images/logo-small.svg)
Large logo:
![Large Logo](https://raw.githubusercontent.com/pypa/warehouse/main/warehouse/static/images/logo-large.svg)

### Additional information

An icon for npm exists so this would be helpful too

**Comment by yeyeto2788** [comment]
@Snailedlt assign this one to me please.
