### ISSUE TITLE
Icon request: Prolog

### ISSUE THREAD

**Issue by fey** [devicons/devicon#924]
### About the icon

Prolog is a logic programming language

### Links and sources

https://iconscout.com/icon/prolog
https://www.swi-prolog.org/icons/swipl.png

**Comment by canaleal** [comment]
Prolog was merged in this PR:
- https://github.com/devicons/devicon/pull/1781

Technically, this Issue (#924) was created prior to this other one (#1761), but hey, at least the icon is now in develop. 
- https://github.com/devicons/devicon/issues/1761
