### ISSUE TITLE
Icon request: CMake

### ISSUE THREAD

**Issue by DeveloperPaul123** [devicons/devicon#925]
### About the icon

CMake is widely used in the C++ community so it makes sense to include an icon for it. 

### Links and sources

[High res PNG/JPEG](https://cmake.org/files/logos/)
[https://iconscout.com/icon/cmake-3521346](https://iconscout.com/icon/cmake-3521346)

**Comment by Panquesito7** [comment]
Already added in #901. 🙂

**Comment by DeveloperPaul123** [comment]
@Panquesito7 Thanks! Is it just not available yet on the website? I searched for it and don't see it there

**Comment by Panquesito7** [comment]
> @Panquesito7 Thanks! Is it just not available yet on the website? I searched for it and don't see it there

We haven't released a new version yet; icons in the `develop` branch won't be reflected on the website (see https://github.com/devicons/devicon/blob/develop/CONTRIBUTING.md#release-strategy-conventions-preparation-and-execution for more information).
