### ISSUE TITLE
Icon request: Django (Existing Django doesn't work well)

### ISSUE THREAD

**Issue by ankushminda** [devicons/devicon#934]
### About the icon

Django is common programming framework used by many web developers.

### Links and sources

The existing django icon doesn't display well in the webpage (See below screenshot). Could you please include this logo for Django.

Error with existing logo.
![image](https://user-images.githubusercontent.com/26448060/144738167-d0096e39-4945-44fa-bbc9-75d234fede13.png)

Reques for below logo to be updated.
![](https://static.djangoproject.com/img/icon-touch.e4872c4da341.png)

https://static.djangoproject.com/img/icon-touch.e4872c4da341.png

**Comment by maltejur** [comment]
Can be closed @Panquesito7
