### ISSUE TITLE
[FEATURE REQUEST] Update the color picking tool to be more intuitive and user-friendly

### ISSUE THREAD

**Issue by Snailedlt** [devicons/devicon#943]
### Problem

 I've been using devicons a few times now, and only today did I find out that there's a color-picker to select a background color for the icons. This is (in my opinion) due to bad design, since the icon for picking a color is no self-explanatory. While I was looking at the color picker I also found a few other things I think can be improved (explained under the "Suggested feature" section.)

### Suggested feature

Here's a list of the features I think are either missing, or can be improved:

1.  Like I've already mentioned, the color picker icon should be changed to something more self-explanatory, like [this](https://www.w3schools.com/colors/img_colormap.gif) or [this](https://help.geogebra.org/public/attachments/5d107b5ed8fdb8964fbad44174bc9b18.png)
2.  Currently there is no way to change back to a transparent background. There should be an option to change the alpha/transparency of the color. Maybe just a tick box, and an extra input field for each "manual" color picking option (RGB->RGBA, HSL->HSLA, and Hex should be #AARRGGBB instead of #RRGGBB).
3. Unlike the other two points, this is just a nice-to-have, but it would be nice to have a "checkered" alternative

### Why should we have this feature?

This would improve the over all User Experience, and would result in a more polished product.

### Additional information

Picture of our current color picker for reference:
![image](https://user-images.githubusercontent.com/43886029/145290215-6287906c-795c-4793-aec2-937633f0d99c.png)

**Comment by Thomas-Boi** [comment]
That's a fair suggestion. I wasn't sure how the community would react to this when I first added it in. I like your suggested images and I would definitely look into them.
