### ISSUE TITLE
Icon request: supabase

### ISSUE THREAD

**Issue by bubbzDotDev** [devicons/devicon#952]
### About the icon

New alternative to Firebase

### Links and sources

https://supabase.com/
https://github.com/supabase/supabase
https://supabase.com/brand-assets

**Comment by danielcranney** [comment]
Seconded! It's becoming more widely used now, so would be great to add.

**Comment by Snailedlt** [comment]
Official SVG icons from https://supabase.com/brand-assets

![supabase-logo-wordmark--dark](https://user-images.githubusercontent.com/43886029/193656304-3c7b166f-36d1-430b-9721-1325c16affd1.svg)
![supabase-logo-wordmark--light](https://user-images.githubusercontent.com/43886029/193656307-7c83bd9f-de6a-4129-b31b-5a36d1997c47.svg)
![supabase-logo-icon](https://user-images.githubusercontent.com/43886029/193656310-3e373b20-d996-4c68-980c-7965dca709d5.svg)
