### ISSUE TITLE
[BUG] No connection could be made because the target machine actively refused it. (os error 10061)

### ISSUE THREAD

**Issue by Thomas-Boi** [devicons/devicon#964]
### Bug description

This bug is sometimes found when running the `peek-bot` Action. When this bug occurs, the following error is shown:
![image](https://user-images.githubusercontent.com/43018778/145949515-1198b90f-1564-4373-9c31-b3d1ad23bb6c.png)

This bug is usually resolved by rerunning the script. However, this can take up to 3-5 times of retrying before the script works. 

Before, this issue was hypothesized to be caused by Icomoon's security system. We thought that it was the site's anti-spam blocking the connection. The OS error listed was usually caused by firewall or the server is rejecting the request (see [this](https://answers.microsoft.com/en-us/windows/forum/all/win-error-10061/eb766631-331f-4cf8-bd43-80b219a0ccc5)). Thus, we thought Icomoon's server was blocking our request

However, after rechecking the code, this was incorrect. The code that triggers the error is creating a new `WebDriver` instance, not getting the URL (which is actually the next command). Thus, the issue is not related to Icomoon's security as we thought before.

After more research into the Selenium repo (which is the library that causes the error), I found that the code actually requires a local port to be opened on the machine (think `http://localhost:8080`). By default, the code would get a random open port and host a server on the GitHub hosted-runners (see [this](https://github.com/SeleniumHQ/selenium/blob/4cc82845e9a2e8038111086ce42fa2ded60175c8/py/selenium/webdriver/firefox/service.py#L26))
![image](https://user-images.githubusercontent.com/43018778/145950553-022dfc7e-a585-47b2-b1f0-4e1bb87f3993.png)

However, I'm guessing that the port (even though it's supposed to be open) was blocked by GitHub's firewall. This matches with the random pattern of how the script fails. Sometimes, a port that's not blocked would be chosen => the script will run fine. However, other times, a port would be chosen but it's actually inaccessible. 

### Possible fixes or solutions

I'm updating `peek-bot` to try by default port 8080. This port is usually used as a freeport for programming and hopefully the GitHub runners won't block it. If that doesn't work, I have a piece of code that will retry the script 5 times with a random port number. I'll log these ports and use them as the default from now on. 

In the worst case that the ports are blocked randomly each time (which should not exist but just in case), I'll just let the script retry the port 5-10 times until it works. This would save maintainers from re-running the script multiple times.

### Additional information

I'm now figuring out how to specify a specific port for the Selenium server. Hopefully, a fix will be pushed within the next 2 days.

**Comment by amacado** [comment]
Great deep dive @Thomas-Boi! Thanks for the investigation, this looks promising! 🚀

**Comment by Thomas-Boi** [comment]
I believe the issue is now fixed. Please see #965 to see the result of the fix and #966 for the PR containing the fix itself
