### ISSUE TITLE
[FEATURE REQUEST] <Copy To Clipboard Icon HTML>

### ISSUE THREAD

**Issue by Alirezaaraby** [devicons/devicon#968]
### Problem

For the coping the icon HTML, there is no copy to the clipboard button.

### Suggested feature

your website is like below:

`<i class="devicon-angularjs-plain"></i>`

My suggestion is make it like below:

    <i class="devicon-angularjs-plain"></i>

### Why should we have this feature?

because it makes your site easier to use and makes it more powerful.

**Comment by Thomas-Boi** [comment]
Thank you for your suggestion. This is actually in our backlog of features and will be implemented in the near future.
