### ISSUE TITLE
Question about displaying license for print media

### ISSUE THREAD

**Issue by sapics** [devicons/devicon#97]
First of all, thanks for your awesome icons and fonts.

I have a question about displaying LICENSE for print media.
In my design, it is difficult to display license file in print media.
https://github.com/konpa/devicon/blob/master/LICENSE

Are there any suggested methods to use your icons or fonts in print media?

**Comment by iamclaytonray** [comment]
Hey @sapics! Thanks for filing an issue! I know it's a little old but I'd like to help if I can and if you still want/need an answer. Do you mind clarifying your question? Are you asking whether or not you're supposed to give `devicon` creative attributes, like in the Creative Commons / Creative Commons Attribution licenses?

**Comment by sapics** [comment]
@iamclaytonray Thanks for your answer!
I have a plan to create an vector editor by html5 which has a feature drag and drop svg icon.
My user can create their own design in editor.
So, my question is, "If my user create a design which includes devicon, do they need write down license attribution in thier design?"
I will write a license attribution as is obvious in my html5 files.

I guess that my user should include license attribution in thier design, if the icon license is [creative commons](https://creativecommons.org/licenses/by/4.0/).
But, I cannot judge about MIT License.

 Thanks for reading my bad English 👍

**Comment by Thomas-Boi** [comment]
I believe that when contributors contribute icons to the icon, they understand that the repo is freeware and is under the MIT license. This means that while attribution is great, it is not necessary.

**Comment by sapics** [comment]
@ Thomas-Boi Thank you for your clear answer!
Of course I set attribusion for my service 👍
