### ISSUE TITLE
[FEATURE REQUEST] <Change The Location Of CDN Of Devicon>

### ISSUE THREAD

**Issue by Alirezaaraby** [devicons/devicon#971]
### Problem

The location that "Place this in your header" placed is confusing when the user is working so fast.

### I think it's better to change the location of "Place this in your header" because it's so close to the icon class names and it's confusing. My Suggestion Is Place It Above Of "Font versions" Part.

![image](https://user-images.githubusercontent.com/45128978/146509987-8734bbbe-124b-4407-b19b-5816ecdcdcf1.png)

### Why should we have this feature?

I think this feature can make your website more friendly with users.

**Comment by Thomas-Boi** [comment]
I'll look into this issue for the website upgrade. Thank you for the suggestion 👍
