### ISSUE TITLE
[FEATURE REQUEST] "Report abuse" 

### ISSUE THREAD

**Issue by amacado** [devicons/devicon#972]
### Problem

Since devicon.dev is publishing icons of companies (which have copyrights) there should be an easy way of reporting an abuse in f.e. in order to request a takedown. Of course this can already be done by creating a GitHub issue but a more convenient way would be nice.

### Suggested feature

I suggest to add a "report abuse" button/link somewhere on the page footer which opens a dialog explaining the project in a few words, providing additional information, a contact mail (info@devicon.dev) and maybe a contact form?

### Additional information

We can discuss who should receive the emails for info@devicon.dev

**Comment by Panquesito7** [comment]
Do you think this could help? https://github.com/devicons/devicon/security

**Comment by Thomas-Boi** [comment]
> Do you think this could help? https://github.com/devicons/devicon/security

@Panquesito7 I think this is for security issues only.

> I suggest to add a "report abuse" button/link somewhere on the page footer which opens a dialog explaining the project in a few words, providing additional information, a contact mail (info@devicon.dev) and maybe a contact form?

@amacado that sounds good. I'm working on updating the website to add #968 and the colored icon feature suggested from the discord. I can look into making a contact form and emailing it to us as well.

**Comment by Thomas-Boi** [comment]
Hi amacado,

I'm looking into making a contact form that would email issues to us. However, I'm wondering whether it's enough to just display our email address and people can just email us directly. This should reduce spamming via bots as well (unless we set up Captcha etc.). I'm leaning more towards this option.

If you really want a contact form, perhaps we can use [emailJS](https://www.emailjs.com/pricing/)'s free tier.
