### ISSUE TITLE
[FEATURE REQUEST] <bootstrap-original.svg>

### ISSUE THREAD

**Issue by ghost** [devicons/devicon#976]
### Problem

[Original doesn't look like Bootstrap logo](https://github.com/devicons/devicon/blob/master/icons/bootstrap/bootstrap-original.svg)

### Suggested feature

[Bootstrap logo](https://commons.wikimedia.org/wiki/File:Bootstrap_logo.svg)

### Why should we have this feature?

make the icon more like the original

**Comment by Thomas-Boi** [comment]
Seems like our icon is a bit squished. I'll look into this.
