### ISSUE TITLE
[ICON REQUEST]: prisma

### ISSUE THREAD

**Issue by gustavohma** [devicons/devicon#984]
### About the icon

Next-generation Node.js and TypeScript ORM Prisma helps app developers build faster and make fewer errors with an open source database toolkit for PostgreSQL, MySQL, SQL Server, and SQLite.  Try Prisma in the Cloud Try locally

### Links and sources

https://worldvectorlogo.com/pt/logo/prisma-2

**Comment by Snailedlt** [comment]
https://www.prisma.io/

## SVG (Official from website)
![image](https://website-v9.vercel.app/logo-dark.svg)

**Comment by Snailedlt** [comment]
Created a non-wordmark version from the official one:
![prisma](https://user-images.githubusercontent.com/43886029/180629558-30632e74-1fa9-496f-8c27-2c9a0a5dc645.svg)
