### ISSUE TITLE
[FEATURE REQUEST] Update AngularJS icon to Angular

### ISSUE THREAD

**Issue by ghost** [devicons/devicon#991]
### Problem

[Upgrading from AngularJS to Angular](https://angular.io/guide/upgrade) with new icon

### Suggested feature

[Full color logo](https://angular.io/presskit#full-color-logo)

**Comment by Thomas-Boi** [comment]
It might be a good idea to make a new folder for `angular` rather than overriding the current `angularjs`. Some people might still use the old icon or the old framework.

**Comment by BenSouchet** [comment]
Since the logo haven't changed & you can find the logo when you tape "angular", I don't think it a good idea to create a new folder and duplicate files.
And Renaming isn't a good solution because after users using the term `angularjs` will have an error since the name won't be valid anymore.

**Comment by Thomas-Boi** [comment]
> Since the logo haven't changed & you can find the logo when you tape "angular", I don't think it a good idea to create a new folder and duplicate files. 

I was thinking of making two folders: one for `angular` and one for `angularjs`. Now, when someone types `angular` in the search bar, they'll see both versions and decide which one they'd like to use.

> And Renaming isn't a good solution because after users using the term angularjs will have an error since the name won't be valid anymore.

I agree. I was thinking of removing the old version but was pleasantly surprised to see quite a few AngularJS apps floating around (including our own website)
