### ISSUE TITLE
[FEATURE REQUEST] GitHub Mark logo

### ISSUE THREAD

**Issue by ghost** [devicons/devicon#992]
### About the icon

GitHub Mark Light logo

### Links and sources

https://github.com/logos
![GitHub-Mark-Light-120px-plus](https://user-images.githubusercontent.com/96730029/147625303-aa09f307-6171-4b71-8bf3-aeb857a93bd3.png)
at [devicon/icons/github/](https://github.com/devicons/devicon/tree/master/icons/github)

**Comment by kilian-paquier** [comment]
Related to https://github.com/devicons/devicon/issues/977 cause it's the same icon as those registered today with inverted colors.

**Comment by lunatic-fox** [comment]
I agree with @kilianpaquier. Maybe #1383 solves it.

**Comment by Snailedlt** [comment]
duplicate of #977
