### ISSUE TITLE
[FEATURE REQUEST] Update Twitter logo

### ISSUE THREAD

**Issue by ghost** [devicons/devicon#993]
### Problem

some quiet small at [devicon/icons/twitter/twitter-original.svg](https://github.com/devicons/devicon/blob/master/icons/twitter/twitter-original.svg)

### Suggested feature

![2021 Twitter logo - blue](https://user-images.githubusercontent.com/96730029/147627723-fcb0f4bf-510b-43ac-a0d0-86e2607c5907.png)

### Additional information

https://about.twitter.com/en/who-we-are/brand-toolkit

**Comment by Thomas-Boi** [comment]
In case anyone else understands the question, can you elaborate on the issue about the current Twitter SVG?
